### My implementation of penalized regressions
In this notebook, I provide improvements and extensions to the original implementation of penalized regressions presented in the book. These include:
* Bayesian optimization of hyperparameters using optuna.
* Walk-forward optimization.
* Additional Feature Engineering: including lags.

  
For training time purposes, I reduce the number of features (use features_short) and use only 20% of the stock_ids_short list. I also perform training using ElasticNet only.

I do not provide code on sparse portfolio optimization.

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
np.random.seed(123)
os.chdir('C:\\Users\\ferna\\OneDrive\\Downloads\\Code\\Python\\ML_Factor')

### 1) Data

In [90]:
from data.data_load import *

In [91]:
# Selection of 20% of stock_ids_short (Careful in real application, has survivorship bias. I use only for simplification).
stock_ids_selected = selected = random.sample(stock_ids_short, k=int(0.2 * len(stock_ids_short)))
len(stock_ids_selected)

158

In [92]:
# Filtering for stock_ids_selected and features_short
data_ml_selected = data_ml.loc[data_ml['stock_id'].isin(stock_ids_selected), ['date', 'stock_id','R1M_Usd'] + features_short]
data_ml_selected = data_ml_selected.sort_values(by=['date', 'stock_id'], ascending=True)
data_ml_selected.index = range(data_ml_selected.shape[0])
data_ml_selected.iloc[[0,1,2,-2,-1]]

,date,stock_id,R1M_Usd,Div_Yld,Eps,Mkt_Cap_12M_Usd,Mom_11M_Usd,Ocf,Pb,Vol1Y_Usd
0,2000-01-31,24,0.222,0.12,0.32,0.29,0.50,0.20,0.66,0.68
1,2000-01-31,34,0.587,0.16,0.15,0.17,0.47,0.22,0.64,0.88
2,2000-01-31,41,0.051,0.73,0.78,0.54,0.42,0.54,0.61,0.15
36022,2018-12-31,1195,0.157,0.24,0.64,0.77,0.50,0.76,0.62,0.49
36023,2018-12-31,1212,0.222,0.13,0.99,0.72,0.09,0.87,0.73,0.88

In [93]:
# Adding lags of dependent variable - may introduce endogeneity if the errors are serially correlated.
# Add 4 lags
data_ml_selected_lags = data_ml_selected.copy()
nlags = 4
for ll in range(1,nlags+1):
    data_ml_selected_lags[f'Lag{ll}_R1M_Usd'] = data_ml_selected.groupby('stock_id')['R1M_Usd'].shift(ll)

In [94]:
# REMOVE NAN
data_ml_selected_lags = data_ml_selected_lags.dropna()

In [95]:
data_ml_selected_lags.iloc[[0,1,2,-2,-1]]

,date,stock_id,R1M_Usd,Div_Yld,Eps,Mkt_Cap_12M_Usd,Mom_11M_Usd,Ocf,Pb,Vol1Y_Usd,Lag1_R1M_Usd,Lag2_R1M_Usd,Lag3_R1M_Usd,Lag4_R1M_Usd
632,2000-05-31,24,0.083,0.21,0.36,0.31,0.87,0.36,0.65,0.76,-0.070,0.098,-0.026,0.222
633,2000-05-31,34,0.299,0.28,0.16,0.25,0.97,0.20,0.79,0.78,0.290,0.040,-0.048,0.587
634,2000-05-31,41,0.021,0.79,0.78,0.52,0.30,0.58,0.53,0.15,0.058,-0.178,0.183,0.051
36022,2018-12-31,1195,0.157,0.24,0.64,0.77,0.50,0.76,0.62,0.49,-0.180,0.050,-0.250,0.031
36023,2018-12-31,1212,0.222,0.13,0.99,0.72,0.09,0.87,0.73,0.88,-0.125,0.013,-0.266,0.044

### 2) Elastic Net training

In [96]:
import optuna
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import ElasticNet

In [97]:
# Functions for walk-forward optimization.

def prepare_data(data_ml_selected_lags, features, y_name , train_tuple, val_tuple, test_tuple):

    """
    Split panel data into training, validation, and test sets by date.
    Returns (X, y) pairs as arrays for each period.
    """
    
    idx_train = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= train_tuple[0]) & 
        (data_ml_selected_lags['date'] < train_tuple[1])
    ]

    idx_val  = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= val_tuple[0]) & 
        (data_ml_selected_lags['date'] < val_tuple[1])
    ]

    idx_test  = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= test_tuple[0]) & 
        (data_ml_selected_lags['date'] <= test_tuple[1])
    ]

    X_train = data_ml_selected_lags.loc[idx_train,:][features].values
    X_val   = data_ml_selected_lags.loc[idx_val,:][features].values
    X_test  = data_ml_selected_lags.loc[idx_test,:][features].values

    y_train = data_ml_selected_lags.loc[idx_train,:][y_name].values
    y_val   = data_ml_selected_lags.loc[idx_val,:][y_name].values
    y_test  = data_ml_selected_lags.loc[idx_test,:][y_name].values

    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

def optimize_hyperparameters(X_train, y_train, X_val, y_val, n_trials=150):

    def objective(trial):

        alpha = trial.suggest_float("alpha", 1e-7, 1e2, log=True)
        l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)

        model = ElasticNet(
            alpha=alpha,
            l1_ratio=l1_ratio,
            max_iter=10000
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_val)

        return mean_squared_error(y_val, y_pred)

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials)

    return study

In [98]:
dates = data_ml_selected_lags['date'].sort_values().unique()

init_train = 120
init_val = 150
retrain_step = 6

features = data_ml_selected_lags.columns.drop(['date', 'stock_id', 'R1M_Usd'])
y_name = 'R1M_Usd'

results = []
hyperparameters = []

for i in range(0, len(dates) - init_val, retrain_step):

    print(i)

    # Preparando dados
    
    train_tuple = (dates[i], dates[i + init_train])
    val_tuple = (dates[i + init_train], dates[i + init_val])

    test_end = min(i + init_val + retrain_step, len(dates))
    test_tuple = (dates[i + init_val], dates[test_end - 1])

    train, val, test = prepare_data(
        data_ml_selected_lags, features, y_name,
        train_tuple, val_tuple, test_tuple
    )

    
    # Hyperparameter optimization

    study = optimize_hyperparameters(train[0], train[1], val[0], val[1], n_trials=200)
    
    best_alpha    = study.best_params["alpha"]
    best_l1_ratio = study.best_params["l1_ratio"]

    # Model: fit on train+val, test on test.
    
    X_fit = np.concatenate([train[0], val[0]], axis=0)
    y_fit = np.concatenate([train[1], val[1]], axis=0)

    model = ElasticNet(**study.best_params, max_iter=10000)
    model.fit(X_fit, y_fit)

    # OOS
    y_pred = model.predict(test[0])
    
    test_dates = dates[i + init_val : i + init_val + retrain_step]

    test_df = data_ml_selected_lags.loc[
        data_ml_selected_lags['date'].isin(test_dates),
        ['date', 'stock_id', y_name]
    ].copy()

    test_df['y_pred'] = y_pred
    results.append(test_df)

    # Store hyperparameters
    hyperparameters.append({
        'date': test_dates[0],
        **study.best_params,
        'validation_mse': study.best_value
    })

# Combine results
results_df = pd.concat(results, ignore_index=True)
hyperparameters_df = pd.DataFrame(hyperparameters)

[I 2026-10-08 19:49:11,084] A new study created in memory with name: no-name-7684a27d-b4ca-4205-b208-17d7d5d4d788
[I 2026-10-08 19:49:11,092] Trial 0 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.719901313179744, 'l1_ratio': 0.407379015415652}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,097] Trial 1 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.1173388171856373, 'l1_ratio': 0.6278021787412205}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,104] Trial 2 finished with value: 0.011978801899755536 and parameters: {'alpha': 0.007143080084788142, 'l1_ratio': 0.07983347377042715}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,112] Trial 3 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.0302114872942971, 'l1_ratio': 0.5900075844886727}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,122] Trial 4 finished with value: 0.012178871987754154 and parameters: {'alpha': 2.462034216812596e-07, 'l1_ratio': 0.460663885312103}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,131] Trial 5 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.15386552428601824, 'l1_ratio': 0.39277431178187183}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,139] Trial 6 finished with value: 0.01217663120504067 and parameters: {'alpha': 0.0002662173974829623, 'l1_ratio': 0.0010596698637255209}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,146] Trial 7 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.2788430494026636, 'l1_ratio': 0.3127700486781477}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,156] Trial 8 finished with value: 0.012177080769394645 and parameters: {'alpha': 5.965555325386553e-06, 'l1_ratio': 0.9062394191955269}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,163] Trial 9 finished with value: 0.011727920757891362 and parameters: {'alpha': 4.528275677701789, 'l1_ratio': 0.6949468488908876}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,175] Trial 10 finished with value: 0.011727920757891362 and parameters: {'alpha': 99.84118781078436, 'l1_ratio': 0.9634830712607105}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,188] Trial 11 finished with value: 0.011851355197000054 and parameters: {'alpha': 0.0018653490753118916, 'l1_ratio': 0.6773754308329667}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,197] Trial 12 finished with value: 0.011727920757891362 and parameters: {'alpha': 13.781751194364848, 'l1_ratio': 0.2471679163672909}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,207] Trial 13 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.029071599038806604, 'l1_ratio': 0.5442090367216209}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,219] Trial 14 finished with value: 0.012133138621919367 and parameters: {'alpha': 0.00016872723287293646, 'l1_ratio': 0.8252928605307444}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,229] Trial 15 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.06426085910581224, 'l1_ratio': 0.2163373799677999}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,239] Trial 16 finished with value: 0.011727920757891362 and parameters: {'alpha': 2.75010518675829, 'l1_ratio': 0.7882705209479299}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,248] Trial 17 finished with value: 0.011727920757891362 and parameters: {'alpha': 61.693097943904604, 'l1_ratio': 0.48924884748265973}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,257] Trial 18 finished with value: 0.011732067625189194 and parameters: {'alpha': 0.004032469162497845, 'l1_ratio': 0.643399139262759}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,268] Trial 19 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.7560607831025977, 'l1_ratio': 0.3845514043260603}. Best is trial 0 with value: 0.011727920757891362.

0

[I 2026-10-08 19:49:11,282] Trial 20 finished with value: 0.012168235396680124 and parameters: {'alpha': 0.00017944784015637346, 'l1_ratio': 0.15702071909582255}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,293] Trial 21 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.1019284486855672, 'l1_ratio': 0.6003787383155171}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,304] Trial 22 finished with value: 0.011727920757891362 and parameters: {'alpha': 13.343304413048958, 'l1_ratio': 0.7530503503574287}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,313] Trial 23 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.03636822476552237, 'l1_ratio': 0.47226452261269136}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,321] Trial 24 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.3118035276980204, 'l1_ratio': 0.5546281162355016}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,331] Trial 25 finished with value: 0.011727920757891362 and parameters: {'alpha': 4.804392959140595, 'l1_ratio': 0.38319841732202753}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,342] Trial 26 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.015268041501893191, 'l1_ratio': 0.6085522217458516}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,354] Trial 27 finished with value: 0.011996822172916394 and parameters: {'alpha': 0.0008355859038679673, 'l1_ratio': 0.7287110431015956}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,364] Trial 28 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.8961619359770323, 'l1_ratio': 0.5430414856057731}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,373] Trial 29 finished with value: 0.011731538788449479 and parameters: {'alpha': 0.00814591885935037, 'l1_ratio': 0.32029076366503034}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,382] Trial 30 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.10652321094675532, 'l1_ratio': 0.8280006784375643}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,393] Trial 31 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.1699454509655615, 'l1_ratio': 0.39937488428973744}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,402] Trial 32 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.39664858446572937, 'l1_ratio': 0.43671012090722633}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,412] Trial 33 finished with value: 0.011727920757891362 and parameters: {'alpha': 20.086003998813876, 'l1_ratio': 0.34048124602591007}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,424] Trial 34 finished with value: 0.012178906888400636 and parameters: {'alpha': 1.2216598047928538e-07, 'l1_ratio': 0.09240161492730098}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,434] Trial 35 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.209171670351988, 'l1_ratio': 0.2648557377087808}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,444] Trial 36 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.11575385057653458, 'l1_ratio': 0.5219169562540243}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,455] Trial 37 finished with value: 0.012176072688742727 and parameters: {'alpha': 1.8685830430241883e-05, 'l1_ratio': 0.4365967056034376}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,467] Trial 38 finished with value: 0.011727920757891362 and parameters: {'alpha': 2.549612668412484, 'l1_ratio': 0.5938015275866185}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,477] Trial 39 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.014608224671351127, 'l1_ratio': 0.6860359141108283}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,488] Trial 40 finished with value: 0.011727920757891362 and parameters: {'alpha': 5.400075347232829, 'l1_ratio': 0.4894328172594137}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,497] Trial 41 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.3045916330191191, 'l1_ratio': 0.30874949348594366}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,506] Trial 42 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.058295741243475425, 'l1_ratio': 0.17788931396990143}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,517] Trial 43 finished with value: 0.012178761679956388 and parameters: {'alpha': 1.4702009756064474e-06, 'l1_ratio': 0.28272144260241044}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,527] Trial 44 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.2278211671805015, 'l1_ratio': 0.35548830410822274}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,538] Trial 45 finished with value: 0.011727920757891362 and parameters: {'alpha': 34.17652300291143, 'l1_ratio': 0.219968820240457}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,547] Trial 46 finished with value: 0.01173192925674162 and parameters: {'alpha': 0.0040382040546573334, 'l1_ratio': 0.6449630183745747}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,556] Trial 47 finished with value: 0.011727920757891362 and parameters: {'alpha': 7.72207737821862, 'l1_ratio': 0.4197547824470833}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,567] Trial 48 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.9026328824232568, 'l1_ratio': 0.9786338989176813}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,578] Trial 49 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.6136986258310286, 'l1_ratio': 0.9069427217968247}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,588] Trial 50 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.025854526452910493, 'l1_ratio': 0.5050743971513632}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,598] Trial 51 finished with value: 0.011727920757891362 and parameters: {'alpha': 2.7390036580633956, 'l1_ratio': 0.6905538380641857}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,608] Trial 52 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.06155175318420495, 'l1_ratio': 0.7912032816851593}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,618] Trial 53 finished with value: 0.011727920757891362 and parameters: {'alpha': 64.84846567889086, 'l1_ratio': 0.7279591698926582}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,628] Trial 54 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.5586656507900609, 'l1_ratio': 0.5861432887601076}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,640] Trial 55 finished with value: 0.011727920757891362 and parameters: {'alpha': 11.506129021166924, 'l1_ratio': 0.6544661423593302}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,650] Trial 56 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.5236657052474019, 'l1_ratio': 0.45597254805356713}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,659] Trial 57 finished with value: 0.011727920757891362 and parameters: {'alpha': 5.016212603869714, 'l1_ratio': 0.562711812887013}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,669] Trial 58 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.14342006609805152, 'l1_ratio': 0.8585925595664963}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,679] Trial 59 finished with value: 0.012080473922458371 and parameters: {'alpha': 0.0008156304555917003, 'l1_ratio': 0.3705213779678671}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,689] Trial 60 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.6369664583813482, 'l1_ratio': 0.733072831283286}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,700] Trial 61 finished with value: 0.011727920757891362 and parameters: {'alpha': 89.80915614112936, 'l1_ratio': 0.9200731686167307}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,710] Trial 62 finished with value: 0.011727920757891362 and parameters: {'alpha': 28.49527327034425, 'l1_ratio': 0.9848749482131112}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,721] Trial 63 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.2731414586619501, 'l1_ratio': 0.2998722879364381}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,731] Trial 64 finished with value: 0.011727920757891362 and parameters: {'alpha': 9.937362925506992, 'l1_ratio': 0.7812488070169064}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,741] Trial 65 finished with value: 0.011727920757891362 and parameters: {'alpha': 35.669475097822954, 'l1_ratio': 0.11604001568411276}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,752] Trial 66 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.09688657792657464, 'l1_ratio': 0.23117510161213736}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,763] Trial 67 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.026257105780233034, 'l1_ratio': 0.6218324294383331}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,773] Trial 68 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.1386776409256214, 'l1_ratio': 0.002893884196250862}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,784] Trial 69 finished with value: 0.011727920757891362 and parameters: {'alpha': 3.7128372593392363, 'l1_ratio': 0.8598266927805739}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,794] Trial 70 finished with value: 0.011727920757891362 and parameters: {'alpha': 17.471408866081195, 'l1_ratio': 0.40404451579571926}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,805] Trial 71 finished with value: 0.011727920757891362 and parameters: {'alpha': 8.710190824471294, 'l1_ratio': 0.2534445243271607}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,815] Trial 72 finished with value: 0.011727920757891362 and parameters: {'alpha': 40.89922937882972, 'l1_ratio': 0.32924224175211736}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,826] Trial 73 finished with value: 0.011727920757891362 and parameters: {'alpha': 2.26275509657682, 'l1_ratio': 0.5334527519627124}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,837] Trial 74 finished with value: 0.011727920757891362 and parameters: {'alpha': 19.05808878409866, 'l1_ratio': 0.15721251176433548}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,847] Trial 75 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.46960791677460023, 'l1_ratio': 0.3603380078558841}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,856] Trial 76 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.9505466154159864, 'l1_ratio': 0.46088751807854567}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,868] Trial 77 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.04382357223720493, 'l1_ratio': 0.18503629906872765}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,880] Trial 78 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.18027766628703096, 'l1_ratio': 0.9470638679612032}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,891] Trial 79 finished with value: 0.011727920757891362 and parameters: {'alpha': 96.1626101484365, 'l1_ratio': 0.2755109754734321}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,902] Trial 80 finished with value: 0.011727920757891362 and parameters: {'alpha': 5.689403498834859, 'l1_ratio': 0.5668622339916851}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,912] Trial 81 finished with value: 0.01174232451562285 and parameters: {'alpha': 0.004241765289392518, 'l1_ratio': 0.5065153852604591}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,922] Trial 82 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.01982998511925665, 'l1_ratio': 0.6284254903270656}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,934] Trial 83 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.00823979529726952, 'l1_ratio': 0.3887885975329429}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,945] Trial 84 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.30886000084221377, 'l1_ratio': 0.7031936775845151}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,955] Trial 85 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.07814096644556912, 'l1_ratio': 0.6648226742159667}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,967] Trial 86 finished with value: 0.011727920757891362 and parameters: {'alpha': 3.448346684467773, 'l1_ratio': 0.5927707425400139}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,978] Trial 87 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.581148937123199, 'l1_ratio': 0.4379043525895467}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,989] Trial 88 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.12050408502118272, 'l1_ratio': 0.49109167476263815}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:11,997] Trial 89 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.04100547114706905, 'l1_ratio': 0.3027572375139744}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,008] Trial 90 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.3822590133808234, 'l1_ratio': 0.24725879947997223}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,019] Trial 91 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.062310501608480305, 'l1_ratio': 0.33794507236089066}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,029] Trial 92 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.1558562310478817, 'l1_ratio': 0.5402970062288166}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,040] Trial 93 finished with value: 0.01180168299756166 and parameters: {'alpha': 0.007815252436057386, 'l1_ratio': 0.19677436947251833}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,051] Trial 94 finished with value: 0.011728864953931606 and parameters: {'alpha': 0.014075256854967029, 'l1_ratio': 0.2043172065703689}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,062] Trial 95 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.7350510805067276, 'l1_ratio': 0.12453527566055975}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,072] Trial 96 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.028944976259031474, 'l1_ratio': 0.279688649393079}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,081] Trial 97 finished with value: 0.011727920757891362 and parameters: {'alpha': 53.669766549698736, 'l1_ratio': 0.6159086295064929}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,094] Trial 98 finished with value: 0.012168394030776717 and parameters: {'alpha': 7.260069222769138e-05, 'l1_ratio': 0.4179018609315089}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,105] Trial 99 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.19203436666070978, 'l1_ratio': 0.5833088233326008}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,115] Trial 100 finished with value: 0.011727920757891362 and parameters: {'alpha': 15.553608013153433, 'l1_ratio': 0.7597405586705098}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,126] Trial 101 finished with value: 0.011727920757891362 and parameters: {'alpha': 6.4376533697003, 'l1_ratio': 0.8259792072041159}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,137] Trial 102 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.8090156814966993, 'l1_ratio': 0.8633498060849298}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,147] Trial 103 finished with value: 0.011727920757891362 and parameters: {'alpha': 3.63537175513505, 'l1_ratio': 0.6393758797251458}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,157] Trial 104 finished with value: 0.011727920757891362 and parameters: {'alpha': 25.481997461512655, 'l1_ratio': 0.6745603590525159}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,168] Trial 105 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.9510058704436434, 'l1_ratio': 0.22074585666589713}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,178] Trial 106 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.4116957786102339, 'l1_ratio': 0.70227546039817}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,191] Trial 107 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.24213686125427927, 'l1_ratio': 0.7217304729867049}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,200] Trial 108 finished with value: 0.011727920757891362 and parameters: {'alpha': 2.486511915322411, 'l1_ratio': 0.24788805769955277}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,210] Trial 109 finished with value: 0.011727920757891362 and parameters: {'alpha': 1.290556929808566, 'l1_ratio': 0.8062189464700394}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,222] Trial 110 finished with value: 0.012178764978030074 and parameters: {'alpha': 1.301249759424045e-06, 'l1_ratio': 0.31498970946769456}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,233] Trial 111 finished with value: 0.011727920757891362 and parameters: {'alpha': 41.227402608055506, 'l1_ratio': 0.5580376575707763}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,244] Trial 112 finished with value: 0.011727920757891362 and parameters: {'alpha': 0.08784485776089299, 'l1_ratio': 0.4938185824932024}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,254] Trial 113 finished with value: 0.011727920757891362 and parameters: {'alpha': 69.49955883052814, 'l1_ratio': 0.5279114189175724}. Best is trial 0 with value: 0.011727920757891362.
[I 2026-10-08 19:49:12,264] Trial 114 finished with value: 0.011727920757891362 and parameters: {'alpha': 12.086480998873023, 'l1_ratio': 0.37752149255816897}. Best is trial 0 with value: 0.011727920757891362.

6

[I 2026-10-08 19:49:13,408] Trial 20 finished with value: 0.010779957100354688 and parameters: {'alpha': 0.0007005535462404282, 'l1_ratio': 0.46534038497585184}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,423] Trial 21 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.3467624527471806, 'l1_ratio': 0.6145700605912499}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,436] Trial 22 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.1439655920530598, 'l1_ratio': 0.5181079990010701}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,445] Trial 23 finished with value: 0.010587203443717287 and parameters: {'alpha': 19.22740278413437, 'l1_ratio': 0.6529649860156896}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,454] Trial 24 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.011084218350176244, 'l1_ratio': 0.9056478792288737}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,461] Trial 25 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.07928377123233, 'l1_ratio': 0.5303993843988778}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,470] Trial 26 finished with value: 0.010587203443717287 and parameters: {'alpha': 4.4683422722094095, 'l1_ratio': 0.3779254920419084}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,484] Trial 27 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.17662459700567673, 'l1_ratio': 0.7619375093622703}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,497] Trial 28 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.007800019821353392, 'l1_ratio': 0.6682824364715699}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,508] Trial 29 finished with value: 0.010587203443717287 and parameters: {'alpha': 20.8795778150068, 'l1_ratio': 0.4747183608758311}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,518] Trial 30 finished with value: 0.010838625836786481 and parameters: {'alpha': 9.25804275701506e-05, 'l1_ratio': 0.8537484345206473}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,528] Trial 31 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.01714179726529892, 'l1_ratio': 0.3029439058829911}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,539] Trial 32 finished with value: 0.01082137788702839 and parameters: {'alpha': 0.002618738725848695, 'l1_ratio': 0.037674562405054624}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,548] Trial 33 finished with value: 0.010837586704339215 and parameters: {'alpha': 0.00023111436952365984, 'l1_ratio': 0.34750937552257516}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,558] Trial 34 finished with value: 0.01085885922030549 and parameters: {'alpha': 1.2601382368438343e-07, 'l1_ratio': 0.6158590188642906}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,566] Trial 35 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.5980439563356366, 'l1_ratio': 0.20716971378817378}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,576] Trial 36 finished with value: 0.010858555645091725 and parameters: {'alpha': 8.164749464443985e-06, 'l1_ratio': 0.11944906871352046}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,585] Trial 37 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.37521353711263933, 'l1_ratio': 0.28390133441896964}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,593] Trial 38 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.08090240705336452, 'l1_ratio': 0.42235459697448746}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,601] Trial 39 finished with value: 0.010587203443717287 and parameters: {'alpha': 67.30901718382788, 'l1_ratio': 0.7489061357690323}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,609] Trial 40 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.02549090666286607, 'l1_ratio': 0.9861210448172906}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,618] Trial 41 finished with value: 0.010587203443717287 and parameters: {'alpha': 3.620075757108327, 'l1_ratio': 0.3954104644093263}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,626] Trial 42 finished with value: 0.010587203443717287 and parameters: {'alpha': 7.433747330369316, 'l1_ratio': 0.25657671570589957}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,635] Trial 43 finished with value: 0.010587203443717287 and parameters: {'alpha': 49.46017620387784, 'l1_ratio': 0.5226827744879007}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,644] Trial 44 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.17965329234717478, 'l1_ratio': 0.42330455195031835}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,653] Trial 45 finished with value: 0.010587203443717287 and parameters: {'alpha': 2.2014848836170953, 'l1_ratio': 0.7044157981056156}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,662] Trial 46 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.4145027336225425, 'l1_ratio': 0.5771938188265373}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,671] Trial 47 finished with value: 0.010587203443717287 and parameters: {'alpha': 9.270266960307788, 'l1_ratio': 0.494286072690703}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,679] Trial 48 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.006025222850823137, 'l1_ratio': 0.641573253291992}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,687] Trial 49 finished with value: 0.010587203443717287 and parameters: {'alpha': 32.15327289490943, 'l1_ratio': 0.35139887252464197}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,696] Trial 50 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.06152826307238038, 'l1_ratio': 0.5652934889281404}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,705] Trial 51 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.6444602232727656, 'l1_ratio': 0.2381669449811366}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,714] Trial 52 finished with value: 0.010587203443717287 and parameters: {'alpha': 2.62342857024252, 'l1_ratio': 0.16557237389334456}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,722] Trial 53 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.6301521956547118, 'l1_ratio': 0.128335160225693}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,731] Trial 54 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.16318631953569296, 'l1_ratio': 0.700744489537715}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,739] Trial 55 finished with value: 0.010587203443717287 and parameters: {'alpha': 5.734196643943771, 'l1_ratio': 0.8080229355285647}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,748] Trial 56 finished with value: 0.010587203443717287 and parameters: {'alpha': 15.955968227107029, 'l1_ratio': 0.4350397480088869}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,756] Trial 57 finished with value: 0.010736515610112329 and parameters: {'alpha': 0.0008690567541541488, 'l1_ratio': 0.6309746214629433}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,765] Trial 58 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.7845477681644973, 'l1_ratio': 0.3282626881384011}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,773] Trial 59 finished with value: 0.010587203443717287 and parameters: {'alpha': 99.4269843605846, 'l1_ratio': 0.5476135407188056}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,780] Trial 60 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.1867447154043559, 'l1_ratio': 0.4959184755022718}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,787] Trial 61 finished with value: 0.010587203443717287 and parameters: {'alpha': 40.0375224173106, 'l1_ratio': 0.9641318976304555}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,795] Trial 62 finished with value: 0.010587203443717287 and parameters: {'alpha': 11.25009370784284, 'l1_ratio': 0.9232874031500435}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,804] Trial 63 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.8647459262515957, 'l1_ratio': 0.7352769512570123}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,814] Trial 64 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.03520871886695158, 'l1_ratio': 0.8608583615816525}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,823] Trial 65 finished with value: 0.010587203443717287 and parameters: {'alpha': 32.06196307620845, 'l1_ratio': 0.7856641598798804}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,832] Trial 66 finished with value: 0.010853137290520657 and parameters: {'alpha': 3.6706899398990536e-05, 'l1_ratio': 0.5912689458906589}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,840] Trial 67 finished with value: 0.010587203443717287 and parameters: {'alpha': 5.750526023390609, 'l1_ratio': 0.37006442803947476}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,849] Trial 68 finished with value: 0.010587203443717287 and parameters: {'alpha': 18.637486320270263, 'l1_ratio': 0.6864147950252504}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,857] Trial 69 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.7050704580959541, 'l1_ratio': 0.28048171426403534}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,865] Trial 70 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.2934723579462904, 'l1_ratio': 0.20457760356949553}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,874] Trial 71 finished with value: 0.010587203443717287 and parameters: {'alpha': 99.33304395703206, 'l1_ratio': 0.6512710367033666}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,882] Trial 72 finished with value: 0.010587203443717287 and parameters: {'alpha': 31.10665673536445, 'l1_ratio': 0.8661325320084268}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,890] Trial 73 finished with value: 0.010587203443717287 and parameters: {'alpha': 4.0690571615806075, 'l1_ratio': 0.7213214935927607}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,898] Trial 74 finished with value: 0.010587203443717287 and parameters: {'alpha': 11.834136616261805, 'l1_ratio': 0.7999135022657543}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,905] Trial 75 finished with value: 0.010587203443717287 and parameters: {'alpha': 70.81926536040066, 'l1_ratio': 0.45859234814155403}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,913] Trial 76 finished with value: 0.010587203443717287 and parameters: {'alpha': 1.1361449391307985, 'l1_ratio': 0.062261906396643585}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,920] Trial 77 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.1171859659389649, 'l1_ratio': 0.8308706238292104}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,929] Trial 78 finished with value: 0.010587203443717287 and parameters: {'alpha': 3.6285119075699868, 'l1_ratio': 0.6706474440700003}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,938] Trial 79 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.017194544400103273, 'l1_ratio': 0.608245658626848}. Best is trial 0 with value: 0.010587203443717287.
[I 2026-10-08 19:49:13,946] Trial 80 finished with value: 0.010584163623244089 and parameters: {'alpha': 0.0040716006107164955, 'l1_ratio': 0.5487185786961952}. Best is trial 80 with value: 0.010584163623244089.
[I 2026-10-08 19:49:13,954] Trial 81 finished with value: 0.010585308798376427 and parameters: {'alpha': 0.003652460079216825, 'l1_ratio': 0.5316037438155186}. Best is trial 80 with value: 0.010584163623244089.
[I 2026-10-08 19:49:13,963] Trial 82 finished with value: 0.010593140312551838 and parameters: {'alpha': 0.0032341912834921143, 'l1_ratio': 0.5351883173828167}. Best is trial 80 with value: 0.010584163623244089.
[I 2026-10-08 19:49:13,975] Trial 83 finished with value: 0.01073136985315655 and parameters: {'alpha': 0.0011712349894043167, 'l1_ratio': 0.4885722344340318}. Best is trial 80 with value: 0.010584163623244089.
[I 2026-10-08 19:49:13,985] Trial 84 finished with value: 0.010586115101286804 and parameters: {'alpha': 0.004655926539371783, 'l1_ratio': 0.40420123843786604}. Best is trial 80 with value: 0.010584163623244089.
[I 2026-10-08 19:49:13,995] Trial 85 finished with value: 0.010583763966089376 and parameters: {'alpha': 0.00521290230003654, 'l1_ratio': 0.39738959931579765}. Best is trial 85 with value: 0.010583763966089376.
[I 2026-10-08 19:49:14,004] Trial 86 finished with value: 0.010587139112256005 and parameters: {'alpha': 0.004692338208335635, 'l1_ratio': 0.3933030452517401}. Best is trial 85 with value: 0.010583763966089376.
[I 2026-10-08 19:49:14,017] Trial 87 finished with value: 0.010828390569669059 and parameters: {'alpha': 0.0002957878823025678, 'l1_ratio': 0.39601443790609125}. Best is trial 85 with value: 0.010583763966089376.
[I 2026-10-08 19:49:14,028] Trial 88 finished with value: 0.01058364902256037 and parameters: {'alpha': 0.006955108924232015, 'l1_ratio': 0.31584612578678656}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,037] Trial 89 finished with value: 0.010583892544091545 and parameters: {'alpha': 0.004963531349236925, 'l1_ratio': 0.41372204132369483}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,047] Trial 90 finished with value: 0.01058466707095213 and parameters: {'alpha': 0.004962538430679568, 'l1_ratio': 0.3968081312649312}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,057] Trial 91 finished with value: 0.010585875038817123 and parameters: {'alpha': 0.004910062818986772, 'l1_ratio': 0.3852268837540185}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,066] Trial 92 finished with value: 0.01058747427665954 and parameters: {'alpha': 0.0046390820737882855, 'l1_ratio': 0.39622045025263786}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,076] Trial 93 finished with value: 0.01072567606814331 and parameters: {'alpha': 0.0018178225352590892, 'l1_ratio': 0.3267955661740532}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,089] Trial 94 finished with value: 0.010809478122871839 and parameters: {'alpha': 0.0005294092306344882, 'l1_ratio': 0.36572746843323284}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,098] Trial 95 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.010257420050714285, 'l1_ratio': 0.44284256541633543}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,109] Trial 96 finished with value: 0.010597339799905667 and parameters: {'alpha': 0.003975447418700319, 'l1_ratio': 0.4153672499370774}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,119] Trial 97 finished with value: 0.0105843272157376 and parameters: {'alpha': 0.007040451730742349, 'l1_ratio': 0.3472632921589174}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,127] Trial 98 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.017564799158898435, 'l1_ratio': 0.289531637567336}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,134] Trial 99 finished with value: 0.010584620745791229 and parameters: {'alpha': 0.007407993431735816, 'l1_ratio': 0.35231717028834464}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,144] Trial 100 finished with value: 0.01058494706034029 and parameters: {'alpha': 0.008090484219363557, 'l1_ratio': 0.3434804443979479}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,154] Trial 101 finished with value: 0.010585673508664937 and parameters: {'alpha': 0.008357614668181858, 'l1_ratio': 0.34910396062371307}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,163] Trial 102 finished with value: 0.01058454438003862 and parameters: {'alpha': 0.007334684757523889, 'l1_ratio': 0.31395728146925683}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,173] Trial 103 finished with value: 0.010584993429854164 and parameters: {'alpha': 0.008066049320771667, 'l1_ratio': 0.34602271151416164}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,181] Trial 104 finished with value: 0.010729401813649994 and parameters: {'alpha': 0.002221683640686145, 'l1_ratio': 0.2542615966988098}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,190] Trial 105 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.012962423791159259, 'l1_ratio': 0.3027963198506924}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,198] Trial 106 finished with value: 0.010742813509191013 and parameters: {'alpha': 0.0015060637815299605, 'l1_ratio': 0.33299571909456116}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,207] Trial 107 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.024677910594214102, 'l1_ratio': 0.3131985514962077}. Best is trial 88 with value: 0.01058364902256037.
[I 2026-10-08 19:49:14,215] Trial 108 finished with value: 0.010583336958219478 and parameters: {'alpha': 0.00797144840726183, 'l1_ratio': 0.26692941133671794}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,223] Trial 109 finished with value: 0.010584756315887862 and parameters: {'alpha': 0.007522856126920568, 'l1_ratio': 0.36142766576731006}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,232] Trial 110 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.02947188224451115, 'l1_ratio': 0.26718864915616897}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,240] Trial 111 finished with value: 0.010584522522977763 and parameters: {'alpha': 0.007094042872907347, 'l1_ratio': 0.3560030590146537}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,249] Trial 112 finished with value: 0.010663267696754644 and parameters: {'alpha': 0.0025897684664103397, 'l1_ratio': 0.3725871508958521}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,258] Trial 113 finished with value: 0.010606823463784476 and parameters: {'alpha': 0.006263987984540326, 'l1_ratio': 0.23608524176872514}. Best is trial 108 with value: 0.010583336958219478.
[I 2026-10-08 19:49:14,265] Trial 114 finished with value: 0.010587203443717287 and parameters: {'alpha': 0.05610632010032089, 'l1_ratio': 0.30051636319302166}. Best is trial 108 with value: 0.010583336958219478.

12

[I 2026-10-08 19:49:15,302] Trial 23 finished with value: 0.010943849760129824 and parameters: {'alpha': 0.00015764900085731896, 'l1_ratio': 0.4820017995721416}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,310] Trial 24 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.09523941727466612, 'l1_ratio': 0.6748716548942513}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,318] Trial 25 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.004217506942017572, 'l1_ratio': 0.8574390374836929}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,327] Trial 26 finished with value: 0.010962713456887159 and parameters: {'alpha': 1.4206050105944055e-05, 'l1_ratio': 0.3300895849263917}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,334] Trial 27 finished with value: 0.01090301670887193 and parameters: {'alpha': 0.00032072462952348384, 'l1_ratio': 0.9263197752279629}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,342] Trial 28 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.40351820948803446, 'l1_ratio': 0.5528438807832364}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,349] Trial 29 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.04671892012021058, 'l1_ratio': 0.6606610849025982}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,358] Trial 30 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.01702962424532031, 'l1_ratio': 0.425932787627193}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,367] Trial 31 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.021103177035405776, 'l1_ratio': 0.507242809669338}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,375] Trial 32 finished with value: 0.010769069235165305 and parameters: {'alpha': 4.535235838514712, 'l1_ratio': 0.3099193915223865}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,383] Trial 33 finished with value: 0.010932277249827748 and parameters: {'alpha': 0.0017892752363889148, 'l1_ratio': 0.058363733374615534}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,393] Trial 34 finished with value: 0.010906900987303418 and parameters: {'alpha': 0.0005886523123054587, 'l1_ratio': 0.4570986261396043}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,401] Trial 35 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.47116043938480373, 'l1_ratio': 0.5382807745437195}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,409] Trial 36 finished with value: 0.010948715055947385 and parameters: {'alpha': 0.0001534830717043936, 'l1_ratio': 0.35911186839597187}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,418] Trial 37 finished with value: 0.010963154869840714 and parameters: {'alpha': 1.2931800661697463e-05, 'l1_ratio': 0.2407614776914513}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,425] Trial 38 finished with value: 0.010764670293379228 and parameters: {'alpha': 0.004248426915702532, 'l1_ratio': 0.6282240540856492}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,433] Trial 39 finished with value: 0.010768006191073402 and parameters: {'alpha': 0.004194323223455638, 'l1_ratio': 0.7192281243555556}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,442] Trial 40 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.00822790661408101, 'l1_ratio': 0.7155141072641024}. Best is trial 13 with value: 0.010762668752247288.
[I 2026-10-08 19:49:15,449] Trial 41 finished with value: 0.010762103334047339 and parameters: {'alpha': 0.0024210703509890716, 'l1_ratio': 0.7973317802311022}. Best is trial 41 with value: 0.010762103334047339.
[I 2026-10-08 19:49:15,460] Trial 42 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.04841224880906964, 'l1_ratio': 0.6245529619043417}. Best is trial 41 with value: 0.010762103334047339.
[I 2026-10-08 19:49:15,468] Trial 43 finished with value: 0.01088595561851882 and parameters: {'alpha': 0.0005158929908987001, 'l1_ratio': 0.7756861240357406}. Best is trial 41 with value: 0.010762103334047339.
[I 2026-10-08 19:49:15,475] Trial 44 finished with value: 0.010936211412022188 and parameters: {'alpha': 0.00014153678305494523, 'l1_ratio': 0.8166371555742442}. Best is trial 41 with value: 0.010762103334047339.
[I 2026-10-08 19:49:15,483] Trial 45 finished with value: 0.010761172464075812 and parameters: {'alpha': 0.003115417500373509, 'l1_ratio': 0.7376929687456882}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,491] Trial 46 finished with value: 0.010797627559393902 and parameters: {'alpha': 0.0017023101238602973, 'l1_ratio': 0.6332558217370783}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,498] Trial 47 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.008969112485526018, 'l1_ratio': 0.5565798255200385}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,506] Trial 48 finished with value: 0.010954570229583863 and parameters: {'alpha': 4.6476447693537685e-05, 'l1_ratio': 0.7390627888682934}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,514] Trial 49 finished with value: 0.010919642165383086 and parameters: {'alpha': 0.0002895022765722174, 'l1_ratio': 0.6973059572184974}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,521] Trial 50 finished with value: 0.010829222941499714 and parameters: {'alpha': 0.0010305509008308586, 'l1_ratio': 0.7703398986885462}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,532] Trial 51 finished with value: 0.01076131279442757 and parameters: {'alpha': 0.002820175797836101, 'l1_ratio': 0.8262821203984847}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,539] Trial 52 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.00922856038461617, 'l1_ratio': 0.8134805084939629}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,547] Trial 53 finished with value: 0.010764899509269302 and parameters: {'alpha': 0.003024664867792608, 'l1_ratio': 0.896765294974248}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,555] Trial 54 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.03189887592240033, 'l1_ratio': 0.8818740765964357}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,564] Trial 55 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.131237377547884, 'l1_ratio': 0.8719223833713298}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,573] Trial 56 finished with value: 0.010817728470567592 and parameters: {'alpha': 0.0008982370205243677, 'l1_ratio': 0.9897975631742122}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,582] Trial 57 finished with value: 0.010761347389146357 and parameters: {'alpha': 0.002923023090907472, 'l1_ratio': 0.7997157769386484}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,589] Trial 58 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.010405326395247978, 'l1_ratio': 0.8401981740715881}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,598] Trial 59 finished with value: 0.01094806758878264 and parameters: {'alpha': 7.447418292696831e-05, 'l1_ratio': 0.7930983251629495}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,609] Trial 60 finished with value: 0.010964040953197205 and parameters: {'alpha': 1.6449677301779163e-07, 'l1_ratio': 0.9528661085408305}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,619] Trial 61 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.003836794728515529, 'l1_ratio': 0.9054806795876555}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,628] Trial 62 finished with value: 0.010762898046476739 and parameters: {'alpha': 0.002175138956703718, 'l1_ratio': 0.749452172164468}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,636] Trial 63 finished with value: 0.01078762983144533 and parameters: {'alpha': 0.0017430018425168118, 'l1_ratio': 0.6849762439077974}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,645] Trial 64 finished with value: 0.010900951520392372 and parameters: {'alpha': 0.00047441647832545386, 'l1_ratio': 0.6464124787126044}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,655] Trial 65 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.020765330311060547, 'l1_ratio': 0.7528819356738126}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,664] Trial 66 finished with value: 0.010925285002045027 and parameters: {'alpha': 0.0002889511480412905, 'l1_ratio': 0.5913493746651899}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,672] Trial 67 finished with value: 0.010831893478504906 and parameters: {'alpha': 0.0009757577729023009, 'l1_ratio': 0.7931419206751998}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,679] Trial 68 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.005355213905144734, 'l1_ratio': 0.8481796136063324}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,688] Trial 69 finished with value: 0.010769069235165305 and parameters: {'alpha': 47.02388335923806, 'l1_ratio': 0.7013508023296293}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,695] Trial 70 finished with value: 0.010761795625653377 and parameters: {'alpha': 0.0025054075721883565, 'l1_ratio': 0.7506702491123172}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,704] Trial 71 finished with value: 0.01076208443508801 and parameters: {'alpha': 0.002594064802918414, 'l1_ratio': 0.760996311418546}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,712] Trial 72 finished with value: 0.010770443913221718 and parameters: {'alpha': 0.0019257702897455737, 'l1_ratio': 0.7479541808638399}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,733] Trial 73 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.056116990286407764, 'l1_ratio': 0.813336914872869}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,761] Trial 74 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.016512208515669494, 'l1_ratio': 0.7352794640004764}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,775] Trial 75 finished with value: 0.010762284070564829 and parameters: {'alpha': 0.0024695097709754353, 'l1_ratio': 0.7904901941471097}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,792] Trial 76 finished with value: 0.010870516759973366 and parameters: {'alpha': 0.0005991281953409498, 'l1_ratio': 0.8408955550037717}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,804] Trial 77 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.006381723021953954, 'l1_ratio': 0.7747322825249142}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,814] Trial 78 finished with value: 0.010788061180961872 and parameters: {'alpha': 0.001288801749438688, 'l1_ratio': 0.9258949778881241}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,822] Trial 79 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.012883062755984132, 'l1_ratio': 0.6664556692137599}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,835] Trial 80 finished with value: 0.010764475135174503 and parameters: {'alpha': 0.0030533843729423165, 'l1_ratio': 0.8637031099836618}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,846] Trial 81 finished with value: 0.010761861684362625 and parameters: {'alpha': 0.002365095083287405, 'l1_ratio': 0.799564520973684}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,855] Trial 82 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.030766687322048455, 'l1_ratio': 0.7999977626929703}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,864] Trial 83 finished with value: 0.010923474638735144 and parameters: {'alpha': 0.00021877824396856975, 'l1_ratio': 0.8322864744677593}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,873] Trial 84 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.00588497731115447, 'l1_ratio': 0.7758010282501929}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,883] Trial 85 finished with value: 0.010761801794708833 and parameters: {'alpha': 0.002626261805887311, 'l1_ratio': 0.7181241190502703}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,893] Trial 86 finished with value: 0.010861642674954854 and parameters: {'alpha': 0.0007856938774270758, 'l1_ratio': 0.7191291153221211}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,902] Trial 87 finished with value: 0.010900430134964405 and parameters: {'alpha': 0.0004449531344206436, 'l1_ratio': 0.6975333049031337}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,911] Trial 88 finished with value: 0.010796353851865292 and parameters: {'alpha': 0.0014419743151659079, 'l1_ratio': 0.7593837861452922}. Best is trial 45 with value: 0.010761172464075812.
[I 2026-10-08 19:49:15,920] Trial 89 finished with value: 0.010761021478402077 and parameters: {'alpha': 0.002730908784328585, 'l1_ratio': 0.8047665752334959}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,929] Trial 90 finished with value: 0.010941614909744659 and parameters: {'alpha': 0.00010787095008670863, 'l1_ratio': 0.819050785123358}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,939] Trial 91 finished with value: 0.010761624203134729 and parameters: {'alpha': 0.0027898385787179366, 'l1_ratio': 0.7274790410027345}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,947] Trial 92 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.006461335061309893, 'l1_ratio': 0.7254121203229307}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,957] Trial 93 finished with value: 0.010761697183263858 and parameters: {'alpha': 0.0026219813590970206, 'l1_ratio': 0.6830189967055328}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,965] Trial 94 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.010774758252456268, 'l1_ratio': 0.6751038549128839}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,973] Trial 95 finished with value: 0.010761825382650608 and parameters: {'alpha': 0.0039043756530029957, 'l1_ratio': 0.6176671026254236}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,981] Trial 96 finished with value: 0.010766757430699738 and parameters: {'alpha': 0.004479726096583666, 'l1_ratio': 0.6509479610904091}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,989] Trial 97 finished with value: 0.010877894064281714 and parameters: {'alpha': 0.0007417516866032191, 'l1_ratio': 0.606873054251646}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:15,997] Trial 98 finished with value: 0.010814035331297274 and parameters: {'alpha': 0.001324364797897701, 'l1_ratio': 0.6917993452024438}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,004] Trial 99 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.01365403548335169, 'l1_ratio': 0.7119546626995658}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,013] Trial 100 finished with value: 0.010768068624686235 and parameters: {'alpha': 0.004152765028520156, 'l1_ratio': 0.7275301130015612}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,022] Trial 101 finished with value: 0.010761937257702598 and parameters: {'alpha': 0.0030977463504265677, 'l1_ratio': 0.6196675786449832}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,030] Trial 102 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.02529035317665674, 'l1_ratio': 0.6089437356065612}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,039] Trial 103 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.007553799856821675, 'l1_ratio': 0.6407962668592463}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,048] Trial 104 finished with value: 0.010761567997349165 and parameters: {'alpha': 0.003208577617046454, 'l1_ratio': 0.5648633128489707}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,058] Trial 105 finished with value: 0.010862726014401407 and parameters: {'alpha': 0.0010705897037513693, 'l1_ratio': 0.5156877765908364}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,066] Trial 106 finished with value: 0.010809914739802364 and parameters: {'alpha': 0.0019975943154441713, 'l1_ratio': 0.4741673592022835}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,076] Trial 107 finished with value: 0.010899344256787577 and parameters: {'alpha': 0.00042712068407261926, 'l1_ratio': 0.7428768759413792}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,084] Trial 108 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.00897422286092474, 'l1_ratio': 0.5721926211232392}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,094] Trial 109 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.003728831605075492, 'l1_ratio': 0.8988737275969607}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,103] Trial 110 finished with value: 0.01077828529864452 and parameters: {'alpha': 0.0732875361736174, 'l1_ratio': 0.010078403141345005}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,115] Trial 111 finished with value: 0.010761596542297362 and parameters: {'alpha': 0.0034499632325312416, 'l1_ratio': 0.5398260739007805}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,125] Trial 112 finished with value: 0.010835005818805308 and parameters: {'alpha': 0.001404204750090271, 'l1_ratio': 0.5302751557304759}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,134] Trial 113 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.006354432030147725, 'l1_ratio': 0.5790483468030283}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,143] Trial 114 finished with value: 0.010894342510138115 and parameters: {'alpha': 0.0007583379685839497, 'l1_ratio': 0.45111586204745685}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,153] Trial 115 finished with value: 0.010777944481305621 and parameters: {'alpha': 0.0024014057829912965, 'l1_ratio': 0.5484640608652889}. Best is trial 89 with value: 0.010761021478402077.
[I 2026-10-08 19:49:16,161] Trial 116 finished with value: 0.010769069235165305 and parameters: {'alpha': 0.005245662251465178, 'l1_ratio': 0.6691288356200888}. Best is trial 89 with value: 0.010761021478402077.

18

[I 2026-10-08 19:49:17,153] Trial 26 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.00825712193239068, 'l1_ratio': 0.37406497574329706}. Best is trial 16 with value: 0.007904417115161298.
[I 2026-10-08 19:49:17,160] Trial 27 finished with value: 0.007936126868023287 and parameters: {'alpha': 3.3472347223483325, 'l1_ratio': 0.06727020158745134}. Best is trial 16 with value: 0.007904417115161298.
[I 2026-10-08 19:49:17,168] Trial 28 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.09424398882709331, 'l1_ratio': 0.201373663787195}. Best is trial 16 with value: 0.007904417115161298.
[I 2026-10-08 19:49:17,176] Trial 29 finished with value: 0.00798608733057766 and parameters: {'alpha': 0.000455050322421627, 'l1_ratio': 0.5344832610042977}. Best is trial 16 with value: 0.007904417115161298.
[I 2026-10-08 19:49:17,183] Trial 30 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.2157829511659931, 'l1_ratio': 0.3024953154039792}. Best is trial 16 with value: 0.007904417115161298.
[I 2026-10-08 19:49:17,192] Trial 31 finished with value: 0.007904150759169714 and parameters: {'alpha': 0.009136514285586914, 'l1_ratio': 0.18038151124853563}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,200] Trial 32 finished with value: 0.007935641710361705 and parameters: {'alpha': 0.031013259474128536, 'l1_ratio': 0.014147052006991206}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,208] Trial 33 finished with value: 0.007935512737631073 and parameters: {'alpha': 0.006593308236964542, 'l1_ratio': 0.1097604703264228}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,218] Trial 34 finished with value: 0.008009246055155933 and parameters: {'alpha': 0.0003677576291562891, 'l1_ratio': 0.21102268664536086}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,225] Trial 35 finished with value: 0.007905809003542671 and parameters: {'alpha': 0.004654893000269689, 'l1_ratio': 0.3764814180104308}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,232] Trial 36 finished with value: 0.007960685623853107 and parameters: {'alpha': 0.031138258159337035, 'l1_ratio': 0.00201813524032457}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,242] Trial 37 finished with value: 0.008023716678215014 and parameters: {'alpha': 3.6169628208577327e-05, 'l1_ratio': 0.2577878494666825}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,250] Trial 38 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.1250586395245405, 'l1_ratio': 0.07187156519666679}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,257] Trial 39 finished with value: 0.007936126868023287 and parameters: {'alpha': 6.569185400829865, 'l1_ratio': 0.17660626285789968}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,264] Trial 40 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.8919019155776087, 'l1_ratio': 0.3186429909975577}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,271] Trial 41 finished with value: 0.007904425817335671 and parameters: {'alpha': 0.0038609843531040734, 'l1_ratio': 0.37560893568154907}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,279] Trial 42 finished with value: 0.007916565891652367 and parameters: {'alpha': 0.0036357470180053185, 'l1_ratio': 0.5907330068277192}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,287] Trial 43 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.021422271075134044, 'l1_ratio': 0.28729784381164375}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,295] Trial 44 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.08572567423866766, 'l1_ratio': 0.3843093637846769}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,304] Trial 45 finished with value: 0.007965472233304282 and parameters: {'alpha': 0.0009810960426247007, 'l1_ratio': 0.43619190369211436}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,313] Trial 46 finished with value: 0.007995086202749042 and parameters: {'alpha': 0.0026951800461786704, 'l1_ratio': 0.04929179098973541}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,321] Trial 47 finished with value: 0.008017621466226617 and parameters: {'alpha': 0.000295546710061519, 'l1_ratio': 0.11640348617329037}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,329] Trial 48 finished with value: 0.007936126868023287 and parameters: {'alpha': 95.21045021764824, 'l1_ratio': 0.6401892777755109}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,342] Trial 49 finished with value: 0.008023839372381101 and parameters: {'alpha': 1.8555411886088087e-05, 'l1_ratio': 0.48932977256087995}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,351] Trial 50 finished with value: 0.007935253140009441 and parameters: {'alpha': 0.011396321083390396, 'l1_ratio': 0.23839623504834861}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,360] Trial 51 finished with value: 0.00790525836806332 and parameters: {'alpha': 0.003759997418889398, 'l1_ratio': 0.37422629930174917}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,369] Trial 52 finished with value: 0.007940286631272537 and parameters: {'alpha': 0.0020710273181568004, 'l1_ratio': 0.34133744379243103}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,377] Trial 53 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.043408311775667646, 'l1_ratio': 0.17623790377876286}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,385] Trial 54 finished with value: 0.007939972689402764 and parameters: {'alpha': 0.0007594246875123365, 'l1_ratio': 0.9586680049201937}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,393] Trial 55 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.014266026792033525, 'l1_ratio': 0.27726651992456486}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,402] Trial 56 finished with value: 0.007928720800072188 and parameters: {'alpha': 0.00620459624698273, 'l1_ratio': 0.1343814191004273}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,414] Trial 57 finished with value: 0.00794842858716562 and parameters: {'alpha': 0.0014938481043378846, 'l1_ratio': 0.40659250031021515}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,423] Trial 58 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.24613552122339954, 'l1_ratio': 0.49568505775187527}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,431] Trial 59 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.05153901344741519, 'l1_ratio': 0.197842826014157}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,440] Trial 60 finished with value: 0.007987285019422915 and parameters: {'alpha': 0.0038469059287777516, 'l1_ratio': 0.046247765812349906}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,449] Trial 61 finished with value: 0.007908709531828078 and parameters: {'alpha': 0.005043482108471516, 'l1_ratio': 0.3653817210712851}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,458] Trial 62 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.015281776421199874, 'l1_ratio': 0.41496909933471643}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,516] Trial 63 finished with value: 0.007967607907796983 and parameters: {'alpha': 0.0016856901537955584, 'l1_ratio': 0.2340568462394766}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,545] Trial 64 finished with value: 0.008005782897580771 and parameters: {'alpha': 0.0002118730643526636, 'l1_ratio': 0.470902926615389}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,557] Trial 65 finished with value: 0.00798872191744473 and parameters: {'alpha': 0.000626287417271174, 'l1_ratio': 0.3487855570972437}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,566] Trial 66 finished with value: 0.00793237804910851 and parameters: {'alpha': 0.00787040202348909, 'l1_ratio': 0.09645867808391773}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,586] Trial 67 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.021326113996280496, 'l1_ratio': 0.15331677518561948}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,599] Trial 68 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.06570677768073423, 'l1_ratio': 0.30947061775720924}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,609] Trial 69 finished with value: 0.007906571836697646 and parameters: {'alpha': 0.003372551610843959, 'l1_ratio': 0.5290899313375881}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,619] Trial 70 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.17161788377276793, 'l1_ratio': 0.3909693916980457}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,630] Trial 71 finished with value: 0.007911454306051077 and parameters: {'alpha': 0.0033858286662556995, 'l1_ratio': 0.5812918839325255}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,641] Trial 72 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.004984388843763546, 'l1_ratio': 0.6664547716111455}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,651] Trial 73 finished with value: 0.00795351117975941 and parameters: {'alpha': 0.0010096951021104797, 'l1_ratio': 0.548825325248269}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,662] Trial 74 finished with value: 0.008016107495531229 and parameters: {'alpha': 8.784194152025065e-05, 'l1_ratio': 0.5217464632727086}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,670] Trial 75 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.022960830362104737, 'l1_ratio': 0.740606735054662}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,681] Trial 76 finished with value: 0.007922534785105764 and parameters: {'alpha': 0.008678324356643488, 'l1_ratio': 0.2657656890111092}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,691] Trial 77 finished with value: 0.007963314878103228 and parameters: {'alpha': 0.002251726695690785, 'l1_ratio': 0.19141351026386477}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,703] Trial 78 finished with value: 0.008025839471770616 and parameters: {'alpha': 1.2016320573861624e-07, 'l1_ratio': 0.45582463651563904}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,714] Trial 79 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.4888294289986958, 'l1_ratio': 0.847845923701291}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,723] Trial 80 finished with value: 0.007917072650853809 and parameters: {'alpha': 0.013952218106731664, 'l1_ratio': 0.15214585310908046}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,732] Trial 81 finished with value: 0.007910436079383817 and parameters: {'alpha': 0.005204538882225884, 'l1_ratio': 0.3679468312136719}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,741] Trial 82 finished with value: 0.00790967861849159 and parameters: {'alpha': 0.0035729466467661463, 'l1_ratio': 0.34881124385169593}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,750] Trial 83 finished with value: 0.007988876929366602 and parameters: {'alpha': 0.0005280473572552264, 'l1_ratio': 0.4143318892547224}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,759] Trial 84 finished with value: 0.007979776984187089 and parameters: {'alpha': 0.0012521600938712198, 'l1_ratio': 0.2276286750036669}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,769] Trial 85 finished with value: 0.007928912805774358 and parameters: {'alpha': 0.026617059982344156, 'l1_ratio': 0.09201484861022106}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,779] Trial 86 finished with value: 0.007928165495593009 and parameters: {'alpha': 0.009616592497902017, 'l1_ratio': 0.25641076695583526}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,789] Trial 87 finished with value: 0.007933196362610681 and parameters: {'alpha': 0.002641231513478156, 'l1_ratio': 0.30315936441063485}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,799] Trial 88 finished with value: 0.007984208237065834 and parameters: {'alpha': 0.005059089817316391, 'l1_ratio': 0.03656476584075802}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,809] Trial 89 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.04533595633613715, 'l1_ratio': 0.12328211835829639}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,818] Trial 90 finished with value: 0.007936126868023287 and parameters: {'alpha': 28.20337148668364, 'l1_ratio': 0.4321226844699056}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,828] Trial 91 finished with value: 0.007917726409646534 and parameters: {'alpha': 0.0030141304504761207, 'l1_ratio': 0.34971790830133725}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,837] Trial 92 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.018646821280114884, 'l1_ratio': 0.3574642599601798}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,849] Trial 93 finished with value: 0.008025702042355918 and parameters: {'alpha': 1.9449003679274528e-06, 'l1_ratio': 0.3385465586187738}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,859] Trial 94 finished with value: 0.00791581609303184 and parameters: {'alpha': 0.006624559032013488, 'l1_ratio': 0.16192291830959493}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,869] Trial 95 finished with value: 0.007951485009408916 and parameters: {'alpha': 0.0019722166891962983, 'l1_ratio': 0.28621220703203787}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,879] Trial 96 finished with value: 0.007971650904317356 and parameters: {'alpha': 0.0009286439908764138, 'l1_ratio': 0.3942497255398347}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,889] Trial 97 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.011722285157643274, 'l1_ratio': 0.5018873967628112}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,899] Trial 98 finished with value: 0.007905941171272378 and parameters: {'alpha': 0.0042589571950119014, 'l1_ratio': 0.3232674562735922}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,909] Trial 99 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.08012980382100796, 'l1_ratio': 0.3235196664851438}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,918] Trial 100 finished with value: 0.007919928307487235 and parameters: {'alpha': 0.004714804566149025, 'l1_ratio': 0.21188330457143867}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,928] Trial 101 finished with value: 0.007945509442161405 and parameters: {'alpha': 0.0014826106905122972, 'l1_ratio': 0.4344133107115766}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,939] Trial 102 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.007919849024416446, 'l1_ratio': 0.36674343570203277}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,949] Trial 103 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.03429548207137948, 'l1_ratio': 0.4614204165353303}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,959] Trial 104 finished with value: 0.007907621409904829 and parameters: {'alpha': 0.003456644660371725, 'l1_ratio': 0.3796659671401877}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,970] Trial 105 finished with value: 0.007997090245415029 and parameters: {'alpha': 0.000400048448721645, 'l1_ratio': 0.3887399964970236}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,980] Trial 106 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.016072588289184512, 'l1_ratio': 0.3288518178247204}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:17,990] Trial 107 finished with value: 0.00796204712804172 and parameters: {'alpha': 0.002399801057252575, 'l1_ratio': 0.18444011027459087}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,000] Trial 108 finished with value: 0.007932205655564819 and parameters: {'alpha': 0.008656896269105738, 'l1_ratio': 0.0870740943082992}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,010] Trial 109 finished with value: 0.00799097867735687 and parameters: {'alpha': 0.0006829607532080078, 'l1_ratio': 0.29147708510970716}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,021] Trial 110 finished with value: 0.007919521922259006 and parameters: {'alpha': 0.003985721032044204, 'l1_ratio': 0.25390836208107986}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,031] Trial 111 finished with value: 0.007905956988715875 and parameters: {'alpha': 0.0036605379803410117, 'l1_ratio': 0.37584255622240037}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,041] Trial 112 finished with value: 0.007928521890482449 and parameters: {'alpha': 0.0061303082805425485, 'l1_ratio': 0.4061016402929921}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,051] Trial 113 finished with value: 0.007952660586442593 and parameters: {'alpha': 0.0014810062905006782, 'l1_ratio': 0.3764002132140454}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,061] Trial 114 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.030193680770763665, 'l1_ratio': 0.47772080579565324}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,071] Trial 115 finished with value: 0.007936126868023287 and parameters: {'alpha': 0.011698055439671408, 'l1_ratio': 0.4316781687980976}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,080] Trial 116 finished with value: 0.007963816412015611 and parameters: {'alpha': 0.00306867835902803, 'l1_ratio': 0.1345331196362401}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,091] Trial 117 finished with value: 0.00794740242370481 and parameters: {'alpha': 0.0019433160883274736, 'l1_ratio': 0.3160204957095153}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,102] Trial 118 finished with value: 0.008019508210761193 and parameters: {'alpha': 0.00023204913737510049, 'l1_ratio': 0.11241207557366795}. Best is trial 31 with value: 0.007904150759169714.
[I 2026-10-08 19:49:18,113] Trial 119 finished with value: 0.007946819436504231 and parameters: {'alpha': 0.0010210753408571038, 'l1_ratio': 0.6204414611758514}. Best is trial 31 with value: 0.007904150759169714.

24

[I 2026-10-08 19:49:19,106] Trial 27 finished with value: 0.008106750788625026 and parameters: {'alpha': 2.530447508445605e-05, 'l1_ratio': 0.4192682195297081}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,113] Trial 28 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.22017306119799152, 'l1_ratio': 0.18852485046846407}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,124] Trial 29 finished with value: 0.008095569445079326 and parameters: {'alpha': 0.0005868668024769008, 'l1_ratio': 0.0864242668290368}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,132] Trial 30 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.02049021986302749, 'l1_ratio': 0.3404196026934618}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,141] Trial 31 finished with value: 0.007995786004181164 and parameters: {'alpha': 0.12244719586886584, 'l1_ratio': 0.0024897215034576994}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,149] Trial 32 finished with value: 0.007983071612369705 and parameters: {'alpha': 0.01178640064938925, 'l1_ratio': 0.137211508889846}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,160] Trial 33 finished with value: 0.007999562496342363 and parameters: {'alpha': 0.015592054138818277, 'l1_ratio': 0.14598281248105832}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,167] Trial 34 finished with value: 0.007984722708102158 and parameters: {'alpha': 0.00673633398809172, 'l1_ratio': 0.26150885729316176}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,176] Trial 35 finished with value: 0.00800465991115712 and parameters: {'alpha': 0.002951514010591274, 'l1_ratio': 0.2864629167815746}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,184] Trial 36 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.0532503906700502, 'l1_ratio': 0.3913467995274721}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,192] Trial 37 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.4737433100653175, 'l1_ratio': 0.0602198265640467}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,200] Trial 38 finished with value: 0.008075366512627047 and parameters: {'alpha': 0.000336934870874872, 'l1_ratio': 0.48061950060079495}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,209] Trial 39 finished with value: 0.008018307823354519 and parameters: {'alpha': 5.00747918931499, 'l1_ratio': 0.23546866653844017}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,217] Trial 40 finished with value: 0.007996359416168478 and parameters: {'alpha': 0.00583272408997877, 'l1_ratio': 0.38026541316625195}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,226] Trial 41 finished with value: 0.007983575043490888 and parameters: {'alpha': 0.008078652016331185, 'l1_ratio': 0.1552391422397002}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,233] Trial 42 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.11383387892063665, 'l1_ratio': 0.13475891238918145}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,242] Trial 43 finished with value: 0.008107609204077612 and parameters: {'alpha': 8.756865903859537e-05, 'l1_ratio': 0.06355027862002062}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,252] Trial 44 finished with value: 0.008056363786353472 and parameters: {'alpha': 0.0010893379384479796, 'l1_ratio': 0.2751244673868738}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,260] Trial 45 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.040369509465062306, 'l1_ratio': 0.1584838361998825}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,269] Trial 46 finished with value: 0.008020196660834094 and parameters: {'alpha': 0.002838819642477436, 'l1_ratio': 0.225362261028948}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,278] Trial 47 finished with value: 0.007993708094197938 and parameters: {'alpha': 0.010715548907877103, 'l1_ratio': 0.09284268362229978}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,287] Trial 48 finished with value: 0.008021385679551858 and parameters: {'alpha': 0.0010279418418950128, 'l1_ratio': 0.6276552200066551}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,295] Trial 49 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.24072240821653795, 'l1_ratio': 0.032761349637146636}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,302] Trial 50 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.031611800267067995, 'l1_ratio': 0.469513772409925}. Best is trial 15 with value: 0.007982432942413867.
[I 2026-10-08 19:49:19,310] Trial 51 finished with value: 0.00798134677363006 and parameters: {'alpha': 0.008043386571778494, 'l1_ratio': 0.19032506470425048}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,318] Trial 52 finished with value: 0.007981485826004794 and parameters: {'alpha': 0.006883312329928072, 'l1_ratio': 0.19616735451601458}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,325] Trial 53 finished with value: 0.008007874211485234 and parameters: {'alpha': 0.0025513323282933195, 'l1_ratio': 0.9974107986902154}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,333] Trial 54 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.01496121166629625, 'l1_ratio': 0.2017893064755618}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,343] Trial 55 finished with value: 0.008103218440833206 and parameters: {'alpha': 0.00013774678322789468, 'l1_ratio': 0.1733648891952906}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,357] Trial 56 finished with value: 0.008072118856979964 and parameters: {'alpha': 0.0005605744255730522, 'l1_ratio': 0.31788745793908535}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,366] Trial 57 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.07999006985721381, 'l1_ratio': 0.11626376472088094}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,374] Trial 58 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.005741463042965109, 'l1_ratio': 0.7429987970315515}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,383] Trial 59 finished with value: 0.008043644051367699 and parameters: {'alpha': 0.0018316606570669665, 'l1_ratio': 0.22329393443657386}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,391] Trial 60 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.5641990458007621, 'l1_ratio': 0.04595645033559871}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,400] Trial 61 finished with value: 0.007985657829925205 and parameters: {'alpha': 0.007089370769986958, 'l1_ratio': 0.25508072521140773}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,409] Trial 62 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.0216083002013083, 'l1_ratio': 0.14439507888806133}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,418] Trial 63 finished with value: 0.007982906575419937 and parameters: {'alpha': 0.004526756970342657, 'l1_ratio': 0.28187213160802427}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,428] Trial 64 finished with value: 0.008075622969020861 and parameters: {'alpha': 0.0005088728077774708, 'l1_ratio': 0.3102059848234151}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,437] Trial 65 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.013147644636259883, 'l1_ratio': 0.3688465652528867}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,446] Trial 66 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.0368206944110934, 'l1_ratio': 0.10242020335147539}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,456] Trial 67 finished with value: 0.008009081625148776 and parameters: {'alpha': 0.004209765528885858, 'l1_ratio': 0.18231936291687326}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,467] Trial 68 finished with value: 0.008046270499280089 and parameters: {'alpha': 0.0018108432349711661, 'l1_ratio': 0.2127103563354485}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,475] Trial 69 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.16688821453217534, 'l1_ratio': 0.28429149614754673}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,483] Trial 70 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.07554866852848041, 'l1_ratio': 0.338802783434934}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,491] Trial 71 finished with value: 0.00799777958405792 and parameters: {'alpha': 0.00840361459059889, 'l1_ratio': 0.2677100486246666}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,501] Trial 72 finished with value: 0.008020523153106347 and parameters: {'alpha': 0.0038181418554629172, 'l1_ratio': 0.16388006810838734}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,509] Trial 73 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.022819058712709683, 'l1_ratio': 0.24107861321437227}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,521] Trial 74 finished with value: 0.00810927689526419 and parameters: {'alpha': 1.215609960926765e-06, 'l1_ratio': 0.19865666123970577}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,530] Trial 75 finished with value: 0.00803427481791983 and parameters: {'alpha': 0.006415164070227928, 'l1_ratio': 0.06938085435277913}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,540] Trial 76 finished with value: 0.008078504437502082 and parameters: {'alpha': 0.0009639643632470274, 'l1_ratio': 0.13916287457575882}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,550] Trial 77 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.05123467415491858, 'l1_ratio': 0.29175727556380476}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,560] Trial 78 finished with value: 0.007984342431313197 and parameters: {'alpha': 0.012004975039685962, 'l1_ratio': 0.10226244798984468}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,569] Trial 79 finished with value: 0.00805396758365407 and parameters: {'alpha': 0.01834880059543449, 'l1_ratio': 0.003792843708386895}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,579] Trial 80 finished with value: 0.008069092224805802 and parameters: {'alpha': 0.0016237956200746786, 'l1_ratio': 0.11233874405967323}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,588] Trial 81 finished with value: 0.008005052700206634 and parameters: {'alpha': 0.009414697676390242, 'l1_ratio': 0.08306441040261466}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,598] Trial 82 finished with value: 0.00801502361431005 and parameters: {'alpha': 0.0040275421422020785, 'l1_ratio': 0.17147263858728437}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,608] Trial 83 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.03992129155916876, 'l1_ratio': 0.25041475683444314}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,618] Trial 84 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.013549598810427861, 'l1_ratio': 0.21359936681938593}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,628] Trial 85 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.02832563329868213, 'l1_ratio': 0.1262091620855094}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,639] Trial 86 finished with value: 0.00810606831030731 and parameters: {'alpha': 0.0002856521843131397, 'l1_ratio': 0.02846431991714945}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,647] Trial 87 finished with value: 0.008033183483389099 and parameters: {'alpha': 0.0031519476646594286, 'l1_ratio': 0.1569114409378688}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,657] Trial 88 finished with value: 0.008069898842482165 and parameters: {'alpha': 0.0008075699154158282, 'l1_ratio': 0.23358806191385348}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,668] Trial 89 finished with value: 0.007988910367630608 and parameters: {'alpha': 0.005734398548847644, 'l1_ratio': 0.3424411305372739}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,679] Trial 90 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.3473471657970138, 'l1_ratio': 0.05215039769122948}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,715] Trial 91 finished with value: 0.00800323555307305 and parameters: {'alpha': 0.009147762722398102, 'l1_ratio': 0.26195083711973616}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,730] Trial 92 finished with value: 0.008041054741635958 and parameters: {'alpha': 0.002242162163220951, 'l1_ratio': 0.19092883663123}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,744] Trial 93 finished with value: 0.00799196418861906 and parameters: {'alpha': 0.006630366222602745, 'l1_ratio': 0.3126247528822405}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,756] Trial 94 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.013377122171950175, 'l1_ratio': 0.3586240533990468}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,767] Trial 95 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.11529493327857017, 'l1_ratio': 0.2698612125712002}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,776] Trial 96 finished with value: 0.00801222094917523 and parameters: {'alpha': 0.026993691105936832, 'l1_ratio': 0.09790315264822858}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,788] Trial 97 finished with value: 0.008066214340692626 and parameters: {'alpha': 0.0014666410083653948, 'l1_ratio': 0.1411718265322317}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,801] Trial 98 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.053757211702504755, 'l1_ratio': 0.2519944637031114}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,811] Trial 99 finished with value: 0.007984578237164341 and parameters: {'alpha': 0.004127644720655046, 'l1_ratio': 0.29795925885918445}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,820] Trial 100 finished with value: 0.008001717254681873 and parameters: {'alpha': 0.0030466692007635973, 'l1_ratio': 0.2944399991119587}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,829] Trial 101 finished with value: 0.007988502881720328 and parameters: {'alpha': 0.005300984584985768, 'l1_ratio': 0.21338517714949737}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,838] Trial 102 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.01011916611676034, 'l1_ratio': 0.40429704391208443}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,847] Trial 103 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.017892469409062386, 'l1_ratio': 0.32480927859329023}. Best is trial 51 with value: 0.00798134677363006.
[I 2026-10-08 19:49:19,856] Trial 104 finished with value: 0.00798071598628549 and parameters: {'alpha': 0.008133684108433637, 'l1_ratio': 0.1793536464852905}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,865] Trial 105 finished with value: 0.008010933843070552 and parameters: {'alpha': 0.003970623560004288, 'l1_ratio': 0.18748658792535547}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,873] Trial 106 finished with value: 0.008046596758999446 and parameters: {'alpha': 0.0024157568736196578, 'l1_ratio': 0.1544894080728154}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,882] Trial 107 finished with value: 0.008099994624599248 and parameters: {'alpha': 0.00044076526774730786, 'l1_ratio': 0.07380250330093799}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,892] Trial 108 finished with value: 0.008087269635075958 and parameters: {'alpha': 0.0007298324639368961, 'l1_ratio': 0.1231683408061935}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,899] Trial 109 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.012465993414329616, 'l1_ratio': 0.23136956416055982}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,908] Trial 110 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.06782716592531779, 'l1_ratio': 0.4331240643137523}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,917] Trial 111 finished with value: 0.007989565114182567 and parameters: {'alpha': 0.007181307146774625, 'l1_ratio': 0.27583324218531113}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,924] Trial 112 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.020073184150007837, 'l1_ratio': 0.2013929846206636}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,933] Trial 113 finished with value: 0.008003870994619685 and parameters: {'alpha': 0.004849037441439501, 'l1_ratio': 0.1733801009104719}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,941] Trial 114 finished with value: 0.007997298001249854 and parameters: {'alpha': 0.009047870298082834, 'l1_ratio': 0.24680842268466807}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,949] Trial 115 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.032150315093128025, 'l1_ratio': 0.10984209176613063}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,958] Trial 116 finished with value: 0.008038682671036917 and parameters: {'alpha': 0.0015342915054823568, 'l1_ratio': 0.29949157673117915}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,967] Trial 117 finished with value: 0.008030343426086462 and parameters: {'alpha': 0.002302652502251522, 'l1_ratio': 0.23180636093943358}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,975] Trial 118 finished with value: 0.008018307823354519 and parameters: {'alpha': 0.015702105804751943, 'l1_ratio': 0.5630327903379629}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,983] Trial 119 finished with value: 0.007981330814113782 and parameters: {'alpha': 0.0041566536042552775, 'l1_ratio': 0.32547610157842927}. Best is trial 104 with value: 0.00798071598628549.
[I 2026-10-08 19:49:19,991] Trial 120 finished with value: 0.007983286520209538 and parameters: {'alpha': 0.003859525344880759, 'l1_ratio': 0.32787553941449493}. Best is trial 104 with value: 0.00798071598628549.

30

[I 2026-10-08 19:49:20,974] Trial 26 finished with value: 0.007632249251900514 and parameters: {'alpha': 21.245483109191326, 'l1_ratio': 0.12153210697774364}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:20,983] Trial 27 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.12100405002755274, 'l1_ratio': 0.3702365044006678}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:20,991] Trial 28 finished with value: 0.007632249251900514 and parameters: {'alpha': 6.4511371291217285, 'l1_ratio': 0.10074730248472022}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,001] Trial 29 finished with value: 0.007725773433594408 and parameters: {'alpha': 2.070770710166487e-05, 'l1_ratio': 0.23388562091126455}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,009] Trial 30 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.8364063708047161, 'l1_ratio': 0.01449847776884565}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,016] Trial 31 finished with value: 0.007621141707051104 and parameters: {'alpha': 0.002378225065505633, 'l1_ratio': 0.8350618056804454}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,024] Trial 32 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.00662602763073875, 'l1_ratio': 0.9965627431419457}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,032] Trial 33 finished with value: 0.007652162847537244 and parameters: {'alpha': 0.0007154762832313111, 'l1_ratio': 0.7898968170981858}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,041] Trial 34 finished with value: 0.0077003444264288545 and parameters: {'alpha': 0.00014947139835831035, 'l1_ratio': 0.8627816974462075}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,050] Trial 35 finished with value: 0.007614173235469327 and parameters: {'alpha': 0.0034666394088088454, 'l1_ratio': 0.4500378225828198}. Best is trial 4 with value: 0.00761305483717862.
[I 2026-10-08 19:49:21,058] Trial 36 finished with value: 0.007612794534682749 and parameters: {'alpha': 0.002519294360388008, 'l1_ratio': 0.5808710995456547}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,068] Trial 37 finished with value: 0.007725197579903488 and parameters: {'alpha': 1.3164255058551446e-05, 'l1_ratio': 0.5741834473540314}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,075] Trial 38 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.010663483481889073, 'l1_ratio': 0.44035404557933727}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,083] Trial 39 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.05370266024695254, 'l1_ratio': 0.6493564255267976}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,092] Trial 40 finished with value: 0.007722098033356573 and parameters: {'alpha': 4.2512762108262113e-05, 'l1_ratio': 0.49327593117589735}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,100] Trial 41 finished with value: 0.007613962040106099 and parameters: {'alpha': 0.002071760770083771, 'l1_ratio': 0.7479684270065047}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,108] Trial 42 finished with value: 0.007680336857826516 and parameters: {'alpha': 0.00037515812517176255, 'l1_ratio': 0.7396412141508998}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,117] Trial 43 finished with value: 0.007627720695919227 and parameters: {'alpha': 0.0014829692590864673, 'l1_ratio': 0.5628522145778005}. Best is trial 36 with value: 0.007612794534682749.
[I 2026-10-08 19:49:21,127] Trial 44 finished with value: 0.0076125482051887985 and parameters: {'alpha': 0.0042538086999970364, 'l1_ratio': 0.3375413202577807}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,138] Trial 45 finished with value: 0.007726770923342192 and parameters: {'alpha': 2.4932102004914073e-06, 'l1_ratio': 0.3268699124569072}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,147] Trial 46 finished with value: 0.007617248380238678 and parameters: {'alpha': 0.0041018725223258435, 'l1_ratio': 0.4365759025902742}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,159] Trial 47 finished with value: 0.0076962043345778835 and parameters: {'alpha': 0.0002331031303068376, 'l1_ratio': 0.6509515794016709}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,168] Trial 48 finished with value: 0.007668462582861941 and parameters: {'alpha': 0.000756387146351761, 'l1_ratio': 0.524049147536553}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,178] Trial 49 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.05616857733083652, 'l1_ratio': 0.3500297194771827}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,186] Trial 50 finished with value: 0.0076146568793580985 and parameters: {'alpha': 0.003425399832507044, 'l1_ratio': 0.4695519952488645}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,194] Trial 51 finished with value: 0.007613515770068218 and parameters: {'alpha': 0.0027159955551281693, 'l1_ratio': 0.4712981443474525}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,203] Trial 52 finished with value: 0.0076671452745743825 and parameters: {'alpha': 0.0013642602259880256, 'l1_ratio': 0.2949449475023533}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,213] Trial 53 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.016441648555485404, 'l1_ratio': 0.5954672262742644}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,223] Trial 54 finished with value: 0.007629681766869419 and parameters: {'alpha': 0.005764210184211582, 'l1_ratio': 0.41964436804908484}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,232] Trial 55 finished with value: 0.00769751630213285 and parameters: {'alpha': 0.00030064776582402884, 'l1_ratio': 0.4756693384829501}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,241] Trial 56 finished with value: 0.007673594007400685 and parameters: {'alpha': 0.000873252024753628, 'l1_ratio': 0.38778299358234625}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,248] Trial 57 finished with value: 0.007630218024267583 and parameters: {'alpha': 0.0033798752527031324, 'l1_ratio': 0.7239807650226586}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,255] Trial 58 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.07622870400983535, 'l1_ratio': 0.6809081236956575}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,265] Trial 59 finished with value: 0.007722988960229348 and parameters: {'alpha': 6.338020177658445e-05, 'l1_ratio': 0.26017807378495}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,273] Trial 60 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.3834549196295082, 'l1_ratio': 0.5442790096489442}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,282] Trial 61 finished with value: 0.007616596466623216 and parameters: {'alpha': 0.0036340530363044884, 'l1_ratio': 0.4823615230745531}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,291] Trial 62 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.025754201642763323, 'l1_ratio': 0.32463088676275104}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,300] Trial 63 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.01151099261784344, 'l1_ratio': 0.5026183354359846}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,309] Trial 64 finished with value: 0.007612934005190371 and parameters: {'alpha': 0.0029405408907440464, 'l1_ratio': 0.44648655683524835}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,318] Trial 65 finished with value: 0.007632581180640213 and parameters: {'alpha': 0.0019377066359650382, 'l1_ratio': 0.3970623769241571}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,325] Trial 66 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.006424510471562913, 'l1_ratio': 0.4465724906887578}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,334] Trial 67 finished with value: 0.007636149804239676 and parameters: {'alpha': 0.00120108254765169, 'l1_ratio': 0.6093675793668311}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,343] Trial 68 finished with value: 0.007693948442986278 and parameters: {'alpha': 0.0001793715834154816, 'l1_ratio': 0.9262834150656252}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,357] Trial 69 finished with value: 0.007726958085840135 and parameters: {'alpha': 1.618150872167323e-07, 'l1_ratio': 0.2510231054253772}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,366] Trial 70 finished with value: 0.007689831151848504 and parameters: {'alpha': 0.0005438009276996331, 'l1_ratio': 0.34483160155327375}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,374] Trial 71 finished with value: 0.0076154650293544625 and parameters: {'alpha': 0.002556622679341758, 'l1_ratio': 0.4585968055729101}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,382] Trial 72 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.014929486752079993, 'l1_ratio': 0.3710877824311494}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,390] Trial 73 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.028136622983886327, 'l1_ratio': 0.5079264754893921}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,398] Trial 74 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.00575995313119802, 'l1_ratio': 0.5531798433020093}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,405] Trial 75 finished with value: 0.00762790838469188 and parameters: {'alpha': 0.001989921483953873, 'l1_ratio': 0.4163371671893299}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,413] Trial 76 finished with value: 0.007674376660892778 and parameters: {'alpha': 0.00044036086340065055, 'l1_ratio': 0.7650219848581558}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,422] Trial 77 finished with value: 0.00762476956466405 and parameters: {'alpha': 0.004040505624194969, 'l1_ratio': 0.5321555443992787}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,432] Trial 78 finished with value: 0.007632114691251627 and parameters: {'alpha': 0.008261570742273754, 'l1_ratio': 0.3062642362255099}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,441] Trial 79 finished with value: 0.007670376386297249 and parameters: {'alpha': 0.0010374021590576709, 'l1_ratio': 0.3575219501069228}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,450] Trial 80 finished with value: 0.007717149953778379 and parameters: {'alpha': 9.424483370362396e-05, 'l1_ratio': 0.45699102090199106}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,459] Trial 81 finished with value: 0.007614136138311823 and parameters: {'alpha': 0.0033808391268491385, 'l1_ratio': 0.46054333969819056}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,467] Trial 82 finished with value: 0.0076544103149140345 and parameters: {'alpha': 0.0024468266602292914, 'l1_ratio': 0.21546941467687414}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,475] Trial 83 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.014270522983992952, 'l1_ratio': 0.57365769822579}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,485] Trial 84 finished with value: 0.007617890172986183 and parameters: {'alpha': 0.0044971589763876775, 'l1_ratio': 0.40595692609399847}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,494] Trial 85 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.03597689133600321, 'l1_ratio': 0.4287881338151541}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,503] Trial 86 finished with value: 0.007668910526021171 and parameters: {'alpha': 0.0007631182424876131, 'l1_ratio': 0.5126960315022977}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,513] Trial 87 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.007796240081850799, 'l1_ratio': 0.46865074286498787}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,523] Trial 88 finished with value: 0.007618334408591475 and parameters: {'alpha': 0.00276368751183298, 'l1_ratio': 0.37926018614318346}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,533] Trial 89 finished with value: 0.007696551459424918 and parameters: {'alpha': 0.00024726092956134263, 'l1_ratio': 0.6045273588916917}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,544] Trial 90 finished with value: 0.007621782689811797 and parameters: {'alpha': 0.0014477471739908346, 'l1_ratio': 0.6542559485285484}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,552] Trial 91 finished with value: 0.007613007133952481 and parameters: {'alpha': 0.002828047356245697, 'l1_ratio': 0.46268348724195213}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,561] Trial 92 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.017600435796822623, 'l1_ratio': 0.485677515115971}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,570] Trial 93 finished with value: 0.00761467777911694 and parameters: {'alpha': 0.004170475899374131, 'l1_ratio': 0.2907254460178963}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,580] Trial 94 finished with value: 0.007660201816867939 and parameters: {'alpha': 0.0005701855158406264, 'l1_ratio': 0.8579413476642805}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,589] Trial 95 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.009693688745207851, 'l1_ratio': 0.5278669244005555}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,599] Trial 96 finished with value: 0.007663323573284129 and parameters: {'alpha': 0.0010359843556169196, 'l1_ratio': 0.4363300390740034}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,607] Trial 97 finished with value: 0.0076382891430488275 and parameters: {'alpha': 0.0017062706302455879, 'l1_ratio': 0.41266866461099233}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,618] Trial 98 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.005982082439142374, 'l1_ratio': 0.584538453539223}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,629] Trial 99 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.06150055226463535, 'l1_ratio': 0.6908582053344048}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,641] Trial 100 finished with value: 0.007694359043008956 and parameters: {'alpha': 0.00034889478463444697, 'l1_ratio': 0.46225964489361826}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,675] Trial 101 finished with value: 0.007624376115286503 and parameters: {'alpha': 0.0030069491010861283, 'l1_ratio': 0.29324773665596504}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,710] Trial 102 finished with value: 0.007615608055255006 and parameters: {'alpha': 0.0043433490692350776, 'l1_ratio': 0.2665572912385521}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,728] Trial 103 finished with value: 0.007642854495794819 and parameters: {'alpha': 0.0020058804711050844, 'l1_ratio': 0.32466667607759975}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,738] Trial 104 finished with value: 0.007618298434775983 and parameters: {'alpha': 0.009671146397362839, 'l1_ratio': 0.18922246122629643}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,748] Trial 105 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.005289075183245582, 'l1_ratio': 0.49123991810438733}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,758] Trial 106 finished with value: 0.007621491443916348 and parameters: {'alpha': 0.0030700694135795256, 'l1_ratio': 0.30753244787381395}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,773] Trial 107 finished with value: 0.00768338093078964 and parameters: {'alpha': 0.0009760860904395336, 'l1_ratio': 0.2447264310053203}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,784] Trial 108 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.01396924140169424, 'l1_ratio': 0.34308705199772005}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,794] Trial 109 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.034592980419805935, 'l1_ratio': 0.39065469648922174}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,803] Trial 110 finished with value: 0.00766851341155156 and parameters: {'alpha': 0.0013785743304964395, 'l1_ratio': 0.28043483850137857}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,814] Trial 111 finished with value: 0.007617557333387128 and parameters: {'alpha': 0.002422054975945597, 'l1_ratio': 0.4456322738114959}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,825] Trial 112 finished with value: 0.00762136504898266 and parameters: {'alpha': 0.0036534465323974164, 'l1_ratio': 0.545365979656039}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,835] Trial 113 finished with value: 0.007677749597240256 and parameters: {'alpha': 0.000649780741914975, 'l1_ratio': 0.46025662119933686}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,844] Trial 114 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.00654938211884883, 'l1_ratio': 0.6288413187281899}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,852] Trial 115 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.023364269017264537, 'l1_ratio': 0.3681866506527256}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,863] Trial 116 finished with value: 0.007631633135462971 and parameters: {'alpha': 0.0015438996850767636, 'l1_ratio': 0.5072443480570742}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,872] Trial 117 finished with value: 0.007632249251900514 and parameters: {'alpha': 0.009381882611656647, 'l1_ratio': 0.42638772838563366}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,882] Trial 118 finished with value: 0.007614180075576895 and parameters: {'alpha': 0.0032008891411570302, 'l1_ratio': 0.4880236244389627}. Best is trial 44 with value: 0.0076125482051887985.
[I 2026-10-08 19:49:21,892] Trial 119 finished with value: 0.007624138548576038 and parameters: {'alpha': 0.004307346168776326, 'l1_ratio': 0.48896223761983504}. Best is trial 44 with value: 0.0076125482051887985.

36

[I 2026-10-08 19:49:22,875] Trial 27 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.46086624739316306, 'l1_ratio': 0.5871084944990393}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,882] Trial 28 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.0796072973258572, 'l1_ratio': 0.2118191793536932}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,890] Trial 29 finished with value: 0.01111882734058437 and parameters: {'alpha': 0.0007618621276627622, 'l1_ratio': 0.4481546907735562}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,902] Trial 30 finished with value: 0.011163474809883127 and parameters: {'alpha': 7.97473884847014e-06, 'l1_ratio': 0.3539355026193618}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,911] Trial 31 finished with value: 0.011042547056185908 and parameters: {'alpha': 24.518611197676726, 'l1_ratio': 0.5291916094701026}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,919] Trial 32 finished with value: 0.011042547056185908 and parameters: {'alpha': 30.40987148333197, 'l1_ratio': 0.48937383651483013}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,928] Trial 33 finished with value: 0.011042547056185908 and parameters: {'alpha': 3.640612172345815, 'l1_ratio': 0.6884279602421441}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,936] Trial 34 finished with value: 0.011042547056185908 and parameters: {'alpha': 99.64499377407496, 'l1_ratio': 0.4590235501552613}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,944] Trial 35 finished with value: 0.011042547056185908 and parameters: {'alpha': 7.84634834651854, 'l1_ratio': 0.5785574588764062}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,952] Trial 36 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.6448681690704436, 'l1_ratio': 0.8016582730483821}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,961] Trial 37 finished with value: 0.0111601293111643 and parameters: {'alpha': 3.3263837420118665e-05, 'l1_ratio': 0.6498610061841432}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,969] Trial 38 finished with value: 0.011042547056185908 and parameters: {'alpha': 26.19922468674829, 'l1_ratio': 0.04808036122054832}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,977] Trial 39 finished with value: 0.011042547056185908 and parameters: {'alpha': 2.4692113841629597, 'l1_ratio': 0.2818115962707969}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,984] Trial 40 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.19986988756592933, 'l1_ratio': 0.5056746491955152}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,991] Trial 41 finished with value: 0.011042547056185908 and parameters: {'alpha': 40.61396770662296, 'l1_ratio': 0.8861694138503269}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:22,999] Trial 42 finished with value: 0.011042547056185908 and parameters: {'alpha': 84.32607491912137, 'l1_ratio': 0.999022658852084}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,008] Trial 43 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.2370374100796113, 'l1_ratio': 0.08724915729603977}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,015] Trial 44 finished with value: 0.011042547056185908 and parameters: {'alpha': 8.576346968868062, 'l1_ratio': 0.7324945556201761}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,023] Trial 45 finished with value: 0.011042547056185908 and parameters: {'alpha': 3.6811084188171237, 'l1_ratio': 0.41573894101469194}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,031] Trial 46 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.036898558811770975, 'l1_ratio': 0.1888621097030636}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,039] Trial 47 finished with value: 0.011042547056185908 and parameters: {'alpha': 49.94734709418329, 'l1_ratio': 0.6089125814830348}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,050] Trial 48 finished with value: 0.011163982220959358 and parameters: {'alpha': 1.4319511544171246e-07, 'l1_ratio': 0.8942931819274081}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,057] Trial 49 finished with value: 0.011042547056185908 and parameters: {'alpha': 13.028670639862575, 'l1_ratio': 0.659831264769971}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,065] Trial 50 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.2207905568426225, 'l1_ratio': 0.9892374485180675}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,073] Trial 51 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.1487547888874021, 'l1_ratio': 0.3555606893186899}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,080] Trial 52 finished with value: 0.011042547056185908 and parameters: {'alpha': 5.605664577230557, 'l1_ratio': 0.306255231561105}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,088] Trial 53 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.21490126101078533, 'l1_ratio': 0.1504362044694706}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,095] Trial 54 finished with value: 0.011042547056185908 and parameters: {'alpha': 18.069328102590642, 'l1_ratio': 0.5498316310821303}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,105] Trial 55 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.9029353894343681, 'l1_ratio': 0.4253520429923575}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,116] Trial 56 finished with value: 0.011058778008142199 and parameters: {'alpha': 0.003921527416737534, 'l1_ratio': 0.24574258368699475}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,124] Trial 57 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.12596857300630535, 'l1_ratio': 0.372787182636018}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,138] Trial 58 finished with value: 0.011163926179860341 and parameters: {'alpha': 5.641208738275254e-07, 'l1_ratio': 0.7689977614140024}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,145] Trial 59 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.42199068922705957, 'l1_ratio': 0.832117941084936}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,155] Trial 60 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.7077881915479676, 'l1_ratio': 0.5253046231722877}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,163] Trial 61 finished with value: 0.011042547056185908 and parameters: {'alpha': 4.29240421022892, 'l1_ratio': 0.7022229151437853}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,171] Trial 62 finished with value: 0.011042547056185908 and parameters: {'alpha': 14.436277037035222, 'l1_ratio': 0.9577201203361313}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,181] Trial 63 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.014625966589045674, 'l1_ratio': 0.6124581287438408}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,190] Trial 64 finished with value: 0.011042547056185908 and parameters: {'alpha': 49.85044998505244, 'l1_ratio': 0.5464918268073197}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,200] Trial 65 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.05729071022016019, 'l1_ratio': 0.4960135854340938}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,209] Trial 66 finished with value: 0.011042547056185908 and parameters: {'alpha': 8.691550962238002, 'l1_ratio': 0.5848026872435336}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,216] Trial 67 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.9874635186682428, 'l1_ratio': 0.44524825571160037}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,224] Trial 68 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.7961908342300474, 'l1_ratio': 0.668495010675487}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,234] Trial 69 finished with value: 0.011042547056185908 and parameters: {'alpha': 55.913392686926706, 'l1_ratio': 0.7210620706970133}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,242] Trial 70 finished with value: 0.011042547056185908 and parameters: {'alpha': 20.14963693798924, 'l1_ratio': 0.8617449280567111}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,249] Trial 71 finished with value: 0.011042547056185908 and parameters: {'alpha': 2.0993101550755364, 'l1_ratio': 0.3885738595689163}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,258] Trial 72 finished with value: 0.011042547056185908 and parameters: {'alpha': 8.048132698512147, 'l1_ratio': 0.31056070913426476}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,267] Trial 73 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.3160129105372974, 'l1_ratio': 0.4656960818260385}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,277] Trial 74 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.12961511504159412, 'l1_ratio': 0.3354383712972466}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,285] Trial 75 finished with value: 0.011042547056185908 and parameters: {'alpha': 4.445453075939392, 'l1_ratio': 0.2782602412229422}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,293] Trial 76 finished with value: 0.011042547056185908 and parameters: {'alpha': 30.845688315099512, 'l1_ratio': 0.6342896606182857}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,301] Trial 77 finished with value: 0.011042547056185908 and parameters: {'alpha': 2.74336370605939, 'l1_ratio': 0.3950023082239569}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,310] Trial 78 finished with value: 0.011042547056185908 and parameters: {'alpha': 11.270728876260435, 'l1_ratio': 0.5551656185353513}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,320] Trial 79 finished with value: 0.011042547056185908 and parameters: {'alpha': 80.40097692532697, 'l1_ratio': 0.48533858260059587}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,328] Trial 80 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.4274492309471472, 'l1_ratio': 0.4426739848826596}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,336] Trial 81 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.04061080167059014, 'l1_ratio': 0.941501453091073}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,345] Trial 82 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.005654720446562199, 'l1_ratio': 0.7791298339393153}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,355] Trial 83 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.5967167499366256, 'l1_ratio': 0.8378109333512553}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,364] Trial 84 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.015202901594610813, 'l1_ratio': 0.9234895593222847}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,372] Trial 85 finished with value: 0.011042547056185908 and parameters: {'alpha': 6.010032755916936, 'l1_ratio': 0.8026110968484179}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,380] Trial 86 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.08790645374351504, 'l1_ratio': 0.5148114776565381}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,388] Trial 87 finished with value: 0.011133806436748212 and parameters: {'alpha': 0.00029342713947290216, 'l1_ratio': 0.7342597190971902}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,395] Trial 88 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.18805320546277, 'l1_ratio': 0.6092816981165888}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,406] Trial 89 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.9621693254138959, 'l1_ratio': 0.2631882253652651}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,415] Trial 90 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.38540491485334477, 'l1_ratio': 0.23141668771700516}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,425] Trial 91 finished with value: 0.011042547056185908 and parameters: {'alpha': 30.26579699540871, 'l1_ratio': 0.5744927968140029}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,433] Trial 92 finished with value: 0.011052356883570497 and parameters: {'alpha': 0.0016765409880211482, 'l1_ratio': 0.676005716860408}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,441] Trial 93 finished with value: 0.011042547056185908 and parameters: {'alpha': 87.21147410869735, 'l1_ratio': 0.6193384485040778}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,448] Trial 94 finished with value: 0.011042547056185908 and parameters: {'alpha': 12.86603099917285, 'l1_ratio': 0.649268261764945}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,455] Trial 95 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.02600167117587972, 'l1_ratio': 0.5383592990453249}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,463] Trial 96 finished with value: 0.011042547056185908 and parameters: {'alpha': 36.762925898360535, 'l1_ratio': 0.7086187690999466}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,470] Trial 97 finished with value: 0.011042547056185908 and parameters: {'alpha': 19.849329899431606, 'l1_ratio': 0.5724874697934407}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,477] Trial 98 finished with value: 0.011042547056185908 and parameters: {'alpha': 3.7217116254772313, 'l1_ratio': 0.7423216241912209}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,484] Trial 99 finished with value: 0.011042547056185908 and parameters: {'alpha': 59.83846708929976, 'l1_ratio': 0.5948766473622543}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,494] Trial 100 finished with value: 0.011042547056185908 and parameters: {'alpha': 23.236925278639227, 'l1_ratio': 0.9757168610115384}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,503] Trial 101 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.010108604975794836, 'l1_ratio': 0.4239046113161705}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,512] Trial 102 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.06214980608428983, 'l1_ratio': 0.4963748910679906}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,520] Trial 103 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.09750436906186691, 'l1_ratio': 0.4708636899421237}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,531] Trial 104 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.2851032097491023, 'l1_ratio': 0.35111851075596173}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,541] Trial 105 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.5380919195885014, 'l1_ratio': 0.38127495721809257}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,549] Trial 106 finished with value: 0.011042547056185908 and parameters: {'alpha': 6.607699987436155, 'l1_ratio': 0.5187257723601674}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,557] Trial 107 finished with value: 0.011042547056185908 and parameters: {'alpha': 1.6477079938773342, 'l1_ratio': 0.5563883294265086}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,565] Trial 108 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.033133190874408594, 'l1_ratio': 0.406861199714978}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,573] Trial 109 finished with value: 0.011042547056185908 and parameters: {'alpha': 2.6504493616369444, 'l1_ratio': 0.44221829542973157}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,582] Trial 110 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.18129424703136487, 'l1_ratio': 0.33393940028798047}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,591] Trial 111 finished with value: 0.011042547056185908 and parameters: {'alpha': 10.207102262554438, 'l1_ratio': 0.860814180685832}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,599] Trial 112 finished with value: 0.011042547056185908 and parameters: {'alpha': 5.49000754467438, 'l1_ratio': 0.9166898986649744}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,607] Trial 113 finished with value: 0.011042547056185908 and parameters: {'alpha': 15.250401607254465, 'l1_ratio': 0.9622860765174217}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,629] Trial 114 finished with value: 0.011042547056185908 and parameters: {'alpha': 57.02826305100248, 'l1_ratio': 0.8878316010457158}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,656] Trial 115 finished with value: 0.011042547056185908 and parameters: {'alpha': 3.2455612807126175, 'l1_ratio': 0.8179091162610341}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,673] Trial 116 finished with value: 0.011042547056185908 and parameters: {'alpha': 34.715131195370056, 'l1_ratio': 0.784005908484124}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,685] Trial 117 finished with value: 0.011042547056185908 and parameters: {'alpha': 10.48118157952646, 'l1_ratio': 0.2869026460741106}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,697] Trial 118 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.8778429757336735, 'l1_ratio': 0.9314795027172107}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,707] Trial 119 finished with value: 0.011042547056185908 and parameters: {'alpha': 19.681139564022445, 'l1_ratio': 0.6353852352285483}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,716] Trial 120 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.1309233426859873, 'l1_ratio': 0.7544079019415565}. Best is trial 0 with value: 0.011042547056185908.
[I 2026-10-08 19:49:23,728] Trial 121 finished with value: 0.011042547056185908 and parameters: {'alpha': 0.06237244709543489, 'l1_ratio': 0.6011259028178269}. Best is trial 0 with value: 0.011042547056185908.

42

[I 2026-10-08 19:49:24,691] Trial 25 finished with value: 0.01235027068378465 and parameters: {'alpha': 11.684426935892475, 'l1_ratio': 0.9182891293661086}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,700] Trial 26 finished with value: 0.012429659053924699 and parameters: {'alpha': 0.00017624908121331606, 'l1_ratio': 0.5256038350273321}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,708] Trial 27 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.15413338112402888, 'l1_ratio': 0.7899306318701348}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,717] Trial 28 finished with value: 0.01235027068378465 and parameters: {'alpha': 4.241520995009572, 'l1_ratio': 0.9099900931635597}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,725] Trial 29 finished with value: 0.01235027068378465 and parameters: {'alpha': 27.471409895820546, 'l1_ratio': 0.49423977669225966}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,732] Trial 30 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.004799144442531405, 'l1_ratio': 0.6741271877531441}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,742] Trial 31 finished with value: 0.01243357671582169 and parameters: {'alpha': 0.00017061683502761648, 'l1_ratio': 0.37074329718609156}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,750] Trial 32 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.12882944519358475, 'l1_ratio': 0.1768829763457937}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,758] Trial 33 finished with value: 0.012351319755916582 and parameters: {'alpha': 0.020080293735114493, 'l1_ratio': 0.06304392228432049}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,768] Trial 34 finished with value: 0.012440747929821968 and parameters: {'alpha': 6.186789433308623e-05, 'l1_ratio': 0.2722830116927624}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,777] Trial 35 finished with value: 0.01235027068378465 and parameters: {'alpha': 2.3456744243760155, 'l1_ratio': 0.4525403067123291}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,786] Trial 36 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.23480653047124275, 'l1_ratio': 0.794578006767815}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,797] Trial 37 finished with value: 0.012442627218477218 and parameters: {'alpha': 8.541905107759273e-06, 'l1_ratio': 0.7130848573301461}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,806] Trial 38 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.0076601895476248886, 'l1_ratio': 0.6293337998706026}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,815] Trial 39 finished with value: 0.01235027068378465 and parameters: {'alpha': 21.43314956679145, 'l1_ratio': 0.3516540025715872}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,825] Trial 40 finished with value: 0.012443391745517377 and parameters: {'alpha': 1.7335848681869717e-06, 'l1_ratio': 0.9124774355645752}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,834] Trial 41 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.4992613152203013, 'l1_ratio': 0.9961318154361537}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,842] Trial 42 finished with value: 0.01235027068378465 and parameters: {'alpha': 93.40478225191889, 'l1_ratio': 0.8565709817617823}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,850] Trial 43 finished with value: 0.01235027068378465 and parameters: {'alpha': 75.43300962293574, 'l1_ratio': 0.8840020642515936}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,859] Trial 44 finished with value: 0.01235027068378465 and parameters: {'alpha': 19.69344516951803, 'l1_ratio': 0.7577191221571408}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,866] Trial 45 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.04467046890103577, 'l1_ratio': 0.8396390206624601}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,875] Trial 46 finished with value: 0.01235027068378465 and parameters: {'alpha': 2.859338191529381, 'l1_ratio': 0.9518973654693504}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,885] Trial 47 finished with value: 0.01235027068378465 and parameters: {'alpha': 54.93139655319257, 'l1_ratio': 0.1924119578898491}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,893] Trial 48 finished with value: 0.01235027068378465 and parameters: {'alpha': 1.055913827542871, 'l1_ratio': 0.7007048974302315}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,903] Trial 49 finished with value: 0.012427483183254647 and parameters: {'alpha': 0.0036722445944024607, 'l1_ratio': 0.01650825156567093}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,911] Trial 50 finished with value: 0.01235027068378465 and parameters: {'alpha': 6.326362291878298, 'l1_ratio': 0.10755938993503561}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,919] Trial 51 finished with value: 0.01235027068378465 and parameters: {'alpha': 26.956697637549784, 'l1_ratio': 0.9462154251039404}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,928] Trial 52 finished with value: 0.01235027068378465 and parameters: {'alpha': 51.29069911455451, 'l1_ratio': 0.9660558202977559}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,935] Trial 53 finished with value: 0.01235027068378465 and parameters: {'alpha': 8.400381481459696, 'l1_ratio': 0.8873720855531956}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,942] Trial 54 finished with value: 0.012396309765714417 and parameters: {'alpha': 0.0004973055499739469, 'l1_ratio': 0.821915601080021}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,951] Trial 55 finished with value: 0.01235027068378465 and parameters: {'alpha': 39.29880730821212, 'l1_ratio': 0.7516663401165627}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,958] Trial 56 finished with value: 0.01235027068378465 and parameters: {'alpha': 13.022690111016889, 'l1_ratio': 0.9796798699646044}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,967] Trial 57 finished with value: 0.01235027068378465 and parameters: {'alpha': 1.977955930201502, 'l1_ratio': 0.6090684815247285}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,975] Trial 58 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.43879057416387873, 'l1_ratio': 0.9182746097338146}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,983] Trial 59 finished with value: 0.01235027068378465 and parameters: {'alpha': 91.21295600256359, 'l1_ratio': 0.8655788660000412}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:24,992] Trial 60 finished with value: 0.01235027068378465 and parameters: {'alpha': 5.029441826863457, 'l1_ratio': 0.5686651706153136}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,000] Trial 61 finished with value: 0.01235027068378465 and parameters: {'alpha': 1.1049764792084535, 'l1_ratio': 0.7990122966715403}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,008] Trial 62 finished with value: 0.012360486300582268 and parameters: {'alpha': 0.0014708859062970137, 'l1_ratio': 0.703666220477323}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,017] Trial 63 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.07539380481319022, 'l1_ratio': 0.7711864630361667}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,024] Trial 64 finished with value: 0.01235027068378465 and parameters: {'alpha': 14.654861601275911, 'l1_ratio': 0.9289063780850622}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,032] Trial 65 finished with value: 0.01235027068378465 and parameters: {'alpha': 36.025895612841666, 'l1_ratio': 0.8268280479858352}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,041] Trial 66 finished with value: 0.01235027068378465 and parameters: {'alpha': 4.021064188265274, 'l1_ratio': 0.7252502308871075}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,049] Trial 67 finished with value: 0.01235027068378465 and parameters: {'alpha': 8.89531396145918, 'l1_ratio': 0.8889618596411533}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,059] Trial 68 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.009098059289350735, 'l1_ratio': 0.4087152616261648}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,066] Trial 69 finished with value: 0.012417558967686548 and parameters: {'alpha': 0.000733390042249008, 'l1_ratio': 0.27284479160949565}. Best is trial 19 with value: 0.01234991384261075.
[I 2026-10-08 19:49:25,075] Trial 70 finished with value: 0.012346470878154553 and parameters: {'alpha': 0.003172063154569611, 'l1_ratio': 0.6755350650167566}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,084] Trial 71 finished with value: 0.012422306720878044 and parameters: {'alpha': 0.00023687632921806848, 'l1_ratio': 0.6615585004729795}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,093] Trial 72 finished with value: 0.012353487621098433 and parameters: {'alpha': 0.002330012615963987, 'l1_ratio': 0.538732812398308}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,104] Trial 73 finished with value: 0.012434702858826375 and parameters: {'alpha': 5.7083634307872336e-05, 'l1_ratio': 0.9976871002495793}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,112] Trial 74 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.035397742209249156, 'l1_ratio': 0.6807668768492169}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,120] Trial 75 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.015073725298839496, 'l1_ratio': 0.8516660783493667}. Best is trial 70 with value: 0.012346470878154553.
[I 2026-10-08 19:49:25,128] Trial 76 finished with value: 0.012345032538119945 and parameters: {'alpha': 0.003957758298317599, 'l1_ratio': 0.5034082674722331}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,137] Trial 77 finished with value: 0.012350952913044505 and parameters: {'alpha': 0.002887026133102219, 'l1_ratio': 0.46780731940157105}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,146] Trial 78 finished with value: 0.012405286589629092 and parameters: {'alpha': 0.00098876099681191, 'l1_ratio': 0.3161273508080419}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,155] Trial 79 finished with value: 0.012418560263802269 and parameters: {'alpha': 0.0003827997295166224, 'l1_ratio': 0.5107137684459375}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,163] Trial 80 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.004680962130743647, 'l1_ratio': 0.6324369202579426}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,171] Trial 81 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.0075196329287798465, 'l1_ratio': 0.7832386036167975}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,179] Trial 82 finished with value: 0.01235027068378465 and parameters: {'alpha': 59.55977160326696, 'l1_ratio': 0.8086101171596084}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,188] Trial 83 finished with value: 0.01235027068378465 and parameters: {'alpha': 24.19937794051727, 'l1_ratio': 0.4104350371474815}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,198] Trial 84 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.0210226143567104, 'l1_ratio': 0.741801438053135}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,206] Trial 85 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.2533176141521967, 'l1_ratio': 0.9418851737175752}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,215] Trial 86 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.06910256564531603, 'l1_ratio': 0.5999255158462443}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,223] Trial 87 finished with value: 0.01235027068378465 and parameters: {'alpha': 14.86873149649122, 'l1_ratio': 0.45189592159258185}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,231] Trial 88 finished with value: 0.01234543077253752 and parameters: {'alpha': 0.0018950434051770426, 'l1_ratio': 0.8934120164284876}. Best is trial 76 with value: 0.012345032538119945.
[I 2026-10-08 19:49:25,240] Trial 89 finished with value: 0.012344926507707058 and parameters: {'alpha': 0.0022146982533365034, 'l1_ratio': 0.8975191967618437}. Best is trial 89 with value: 0.012344926507707058.
[I 2026-10-08 19:49:25,250] Trial 90 finished with value: 0.012349814132537839 and parameters: {'alpha': 0.001574162033972326, 'l1_ratio': 0.8914103028122916}. Best is trial 89 with value: 0.012344926507707058.
[I 2026-10-08 19:49:25,261] Trial 91 finished with value: 0.012346361447245994 and parameters: {'alpha': 0.0017890375865427788, 'l1_ratio': 0.8983756480661832}. Best is trial 89 with value: 0.012344926507707058.
[I 2026-10-08 19:49:25,281] Trial 92 finished with value: 0.012344315822726236 and parameters: {'alpha': 0.0020680925100335723, 'l1_ratio': 0.8985702621672895}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,293] Trial 93 finished with value: 0.012347647518429249 and parameters: {'alpha': 0.0017191603446131654, 'l1_ratio': 0.8805589720875132}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,302] Trial 94 finished with value: 0.012347691124924294 and parameters: {'alpha': 0.0016881133247162346, 'l1_ratio': 0.8950948040504662}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,313] Trial 95 finished with value: 0.012346020854870698 and parameters: {'alpha': 0.0018092310372096543, 'l1_ratio': 0.904323306001624}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,322] Trial 96 finished with value: 0.012346152750140844 and parameters: {'alpha': 0.0023560368922596795, 'l1_ratio': 0.8984043835955199}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,331] Trial 97 finished with value: 0.012365087118988299 and parameters: {'alpha': 0.0010257244448441183, 'l1_ratio': 0.9041831548977508}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,340] Trial 98 finished with value: 0.012411895859382358 and parameters: {'alpha': 0.0003047047110802357, 'l1_ratio': 0.8448367165019057}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,351] Trial 99 finished with value: 0.012349997278029561 and parameters: {'alpha': 0.002754928157688439, 'l1_ratio': 0.8698883336099106}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,361] Trial 100 finished with value: 0.01237478144459505 and parameters: {'alpha': 0.0007038550791230123, 'l1_ratio': 0.9715359868011038}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,369] Trial 101 finished with value: 0.012346223037446789 and parameters: {'alpha': 0.001799040933337976, 'l1_ratio': 0.8997553872124435}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,378] Trial 102 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.005080720534720575, 'l1_ratio': 0.9093802190622856}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,390] Trial 103 finished with value: 0.012429217028417448 and parameters: {'alpha': 0.00010486225531462568, 'l1_ratio': 0.9266806285201197}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,398] Trial 104 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.010104592211351748, 'l1_ratio': 0.9367616433048892}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,407] Trial 105 finished with value: 0.012346545115003108 and parameters: {'alpha': 0.0019250284214562985, 'l1_ratio': 0.8272855126498144}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,415] Trial 106 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.0037472217954787326, 'l1_ratio': 0.8259936919488232}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,425] Trial 107 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.006192104714035583, 'l1_ratio': 0.87001171721852}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,435] Trial 108 finished with value: 0.01234665644590957 and parameters: {'alpha': 0.0022406135122532873, 'l1_ratio': 0.9647782977137654}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,445] Trial 109 finished with value: 0.01237154116133498 and parameters: {'alpha': 0.0007819488446766003, 'l1_ratio': 0.9764806677897321}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,455] Trial 110 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.013718180331284463, 'l1_ratio': 0.9589077202269509}. Best is trial 92 with value: 0.012344315822726236.
[I 2026-10-08 19:49:25,464] Trial 111 finished with value: 0.012344234991223899 and parameters: {'alpha': 0.0022134638241255652, 'l1_ratio': 0.8504528035404783}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,473] Trial 112 finished with value: 0.012345812722289568 and parameters: {'alpha': 0.0024498851058140977, 'l1_ratio': 0.8505858780863621}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,482] Trial 113 finished with value: 0.012392704540835093 and parameters: {'alpha': 0.000527088907705019, 'l1_ratio': 0.8434688863238777}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,491] Trial 114 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.003415060605785438, 'l1_ratio': 0.8131501423335912}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,501] Trial 115 finished with value: 0.012368898570995528 and parameters: {'alpha': 0.000965413534227791, 'l1_ratio': 0.8646362187099377}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,511] Trial 116 finished with value: 0.012352795687717542 and parameters: {'alpha': 0.0014033623983199127, 'l1_ratio': 0.914965178862949}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,521] Trial 117 finished with value: 0.012345933741376075 and parameters: {'alpha': 0.002515522225327605, 'l1_ratio': 0.8329950935085711}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,529] Trial 118 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.004814572022256322, 'l1_ratio': 0.7656565076721742}. Best is trial 111 with value: 0.012344234991223899.
[I 2026-10-08 19:49:25,540] Trial 119 finished with value: 0.01235027068378465 and parameters: {'alpha': 0.010969162682376521, 'l1_ratio': 0.8499149285834405}. Best is trial 111 with value: 0.012344234991223899.

48

[I 2026-10-08 19:49:26,615] Trial 23 finished with value: 0.013520773752080856 and parameters: {'alpha': 0.000559115558660153, 'l1_ratio': 0.6213839986894629}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,622] Trial 24 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.030511573850563717, 'l1_ratio': 0.637954171648216}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,632] Trial 25 finished with value: 0.013536140032846387 and parameters: {'alpha': 0.00014135856354062314, 'l1_ratio': 0.8306747682132736}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,641] Trial 26 finished with value: 0.013519273994438882 and parameters: {'alpha': 0.000660728122884833, 'l1_ratio': 0.5724795780190902}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,649] Trial 27 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.2571393352866058, 'l1_ratio': 0.2394185564494577}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,658] Trial 28 finished with value: 0.013533362584680275 and parameters: {'alpha': 2.587907435511095, 'l1_ratio': 0.47146592232994783}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,667] Trial 29 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.009750524616589101, 'l1_ratio': 0.519969912263853}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,679] Trial 30 finished with value: 0.013546960444292397 and parameters: {'alpha': 3.721859231697365e-05, 'l1_ratio': 0.9947720280655898}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,689] Trial 31 finished with value: 0.0135217062603767 and parameters: {'alpha': 0.0007713512170763801, 'l1_ratio': 0.4213687057088603}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,698] Trial 32 finished with value: 0.013515451274477374 and parameters: {'alpha': 0.0017983460475669095, 'l1_ratio': 0.5986211557633946}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,707] Trial 33 finished with value: 0.013523192767975811 and parameters: {'alpha': 0.002797705351780883, 'l1_ratio': 0.6829886437455739}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,721] Trial 34 finished with value: 0.01355292502193893 and parameters: {'alpha': 1.3377719831156458e-07, 'l1_ratio': 0.5541796470792332}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,746] Trial 35 finished with value: 0.013552821543663253 and parameters: {'alpha': 3.469635253782074e-06, 'l1_ratio': 0.18185316321034606}. Best is trial 11 with value: 0.013513209341047607.
[I 2026-10-08 19:49:26,757] Trial 36 finished with value: 0.013513108389543812 and parameters: {'alpha': 0.0024213866861834393, 'l1_ratio': 0.31196683554985516}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,766] Trial 37 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.0208130755427031, 'l1_ratio': 0.2846473985994417}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,776] Trial 38 finished with value: 0.013518280891714286 and parameters: {'alpha': 0.0023528821835694, 'l1_ratio': 0.15910697485820327}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,788] Trial 39 finished with value: 0.013551592655688522 and parameters: {'alpha': 0.00018875216595365879, 'l1_ratio': 0.024743549706779056}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,797] Trial 40 finished with value: 0.013518064086035647 and parameters: {'alpha': 0.004547002997840984, 'l1_ratio': 0.309713096958184}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,806] Trial 41 finished with value: 0.013524538098890952 and parameters: {'alpha': 0.004592099782127724, 'l1_ratio': 0.4297174215850162}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,814] Trial 42 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.05333095920301873, 'l1_ratio': 0.31844583905280205}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,824] Trial 43 finished with value: 0.013516017474465921 and parameters: {'alpha': 0.002018021349096742, 'l1_ratio': 0.2164360520670786}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,835] Trial 44 finished with value: 0.013521330045652867 and parameters: {'alpha': 0.0016315707652844224, 'l1_ratio': 0.195630718386891}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,845] Trial 45 finished with value: 0.013547738982141596 and parameters: {'alpha': 0.0002694290867712778, 'l1_ratio': 0.10339836530300958}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,855] Trial 46 finished with value: 0.013515236153839188 and parameters: {'alpha': 0.0013563126013601441, 'l1_ratio': 0.772183746289278}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,866] Trial 47 finished with value: 0.013533362584680275 and parameters: {'alpha': 73.64585665178127, 'l1_ratio': 0.7719640508753036}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,876] Trial 48 finished with value: 0.013550347757698245 and parameters: {'alpha': 6.74325696365211e-05, 'l1_ratio': 0.21669972652511926}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,884] Trial 49 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.011662780008293407, 'l1_ratio': 0.93013237604393}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,893] Trial 50 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.15611385768923372, 'l1_ratio': 0.6967215946481898}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,903] Trial 51 finished with value: 0.013517085097852927 and parameters: {'alpha': 0.001351426791811656, 'l1_ratio': 0.9146206273824028}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,912] Trial 52 finished with value: 0.013517088587488244 and parameters: {'alpha': 0.0014989345794973955, 'l1_ratio': 0.8252465052013541}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,922] Trial 53 finished with value: 0.013524371659130398 and parameters: {'alpha': 0.0003656679352392732, 'l1_ratio': 0.7418722898932788}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,931] Trial 54 finished with value: 0.013517567754533272 and parameters: {'alpha': 0.001518345731516081, 'l1_ratio': 0.8905106645556591}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,940] Trial 55 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.02832849490723996, 'l1_ratio': 0.9318373596210674}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,948] Trial 56 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.009182224717831864, 'l1_ratio': 0.7973160728866742}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,959] Trial 57 finished with value: 0.013550842909169308 and parameters: {'alpha': 8.790268800548296e-05, 'l1_ratio': 0.12683051680328966}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,968] Trial 58 finished with value: 0.013517984746864286 and parameters: {'alpha': 0.0053453286717293925, 'l1_ratio': 0.06297043001920333}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,978] Trial 59 finished with value: 0.013552316250571366 and parameters: {'alpha': 9.885063570990146e-06, 'l1_ratio': 0.35918236520910063}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,988] Trial 60 finished with value: 0.01353052232131833 and parameters: {'alpha': 0.00040163768681056365, 'l1_ratio': 0.42142859536310356}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:26,997] Trial 61 finished with value: 0.013517087335320064 and parameters: {'alpha': 0.0014889530311156859, 'l1_ratio': 0.8288182131445216}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,006] Trial 62 finished with value: 0.013514559495792739 and parameters: {'alpha': 0.0009838829603369275, 'l1_ratio': 0.9004818651571043}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,014] Trial 63 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.0034042749115763106, 'l1_ratio': 0.9046793895915218}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,022] Trial 64 finished with value: 0.013514955211087622 and parameters: {'alpha': 0.0010204568411455118, 'l1_ratio': 0.9579316180462182}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,029] Trial 65 finished with value: 0.01351349687996765 and parameters: {'alpha': 0.000819601812573392, 'l1_ratio': 0.9632610421627601}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,039] Trial 66 finished with value: 0.013529848174677233 and parameters: {'alpha': 0.00018443018241796587, 'l1_ratio': 0.9765370329768657}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,047] Trial 67 finished with value: 0.013514008317028892 and parameters: {'alpha': 0.0006031257420409076, 'l1_ratio': 0.8656708886277419}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,057] Trial 68 finished with value: 0.013548403258702562 and parameters: {'alpha': 2.8924856339092894e-05, 'l1_ratio': 0.9573074718028669}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,067] Trial 69 finished with value: 0.013513123158047173 and parameters: {'alpha': 0.0006304666399971973, 'l1_ratio': 0.8784383901453037}. Best is trial 36 with value: 0.013513108389543812.
[I 2026-10-08 19:49:27,074] Trial 70 finished with value: 0.013513073592047169 and parameters: {'alpha': 0.0008032211823030206, 'l1_ratio': 0.8524463664036657}. Best is trial 70 with value: 0.013513073592047169.
[I 2026-10-08 19:49:27,082] Trial 71 finished with value: 0.01351227578214879 and parameters: {'alpha': 0.0007074747956298857, 'l1_ratio': 0.8603407911912432}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,091] Trial 72 finished with value: 0.013517617900741062 and parameters: {'alpha': 0.0004881334559137838, 'l1_ratio': 0.8606979723919694}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,101] Trial 73 finished with value: 0.013538864747156654 and parameters: {'alpha': 0.00010825345015051995, 'l1_ratio': 0.8772601740476007}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,109] Trial 74 finished with value: 0.013529003842018777 and parameters: {'alpha': 0.00022485521094174456, 'l1_ratio': 0.8436601762924402}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,117] Trial 75 finished with value: 0.013514644360824633 and parameters: {'alpha': 0.0006918884582095135, 'l1_ratio': 0.7219848714307374}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,127] Trial 76 finished with value: 0.013547292749452452 and parameters: {'alpha': 4.334833876808852e-05, 'l1_ratio': 0.8007826532799395}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,135] Trial 77 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.008393466393197421, 'l1_ratio': 0.9555437602992543}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,143] Trial 78 finished with value: 0.013512853844003381 and parameters: {'alpha': 0.00066700842673299, 'l1_ratio': 0.9951146615649018}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,152] Trial 79 finished with value: 0.01352407455465859 and parameters: {'alpha': 0.00028153171903538745, 'l1_ratio': 0.9975340666007445}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,160] Trial 80 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.003289755080875601, 'l1_ratio': 0.8685275031317519}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,169] Trial 81 finished with value: 0.01351255358868414 and parameters: {'alpha': 0.0006781064225698139, 'l1_ratio': 0.9405078292305074}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,178] Trial 82 finished with value: 0.013512999918452501 and parameters: {'alpha': 0.0007188838630941434, 'l1_ratio': 0.9413956984626899}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,187] Trial 83 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.019140324613544684, 'l1_ratio': 0.9438551173767878}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,197] Trial 84 finished with value: 0.01351951653715691 and parameters: {'alpha': 0.0003874609164370618, 'l1_ratio': 0.9736076729332356}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,208] Trial 85 finished with value: 0.01353703821737483 and parameters: {'alpha': 0.00011989295569403043, 'l1_ratio': 0.9170505864040903}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,216] Trial 86 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.0027021975637721283, 'l1_ratio': 0.9747943126406582}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,226] Trial 87 finished with value: 0.013545532482503087 and parameters: {'alpha': 5.7740170294491514e-05, 'l1_ratio': 0.8023336767994655}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,237] Trial 88 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.006544452162636494, 'l1_ratio': 0.6573544564705108}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,247] Trial 89 finished with value: 0.013550235790381485 and parameters: {'alpha': 1.8176071049954664e-05, 'l1_ratio': 0.8913300366694721}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,258] Trial 90 finished with value: 0.013514023555376712 and parameters: {'alpha': 0.0009058728082229473, 'l1_ratio': 0.9331624001671431}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,268] Trial 91 finished with value: 0.013512541416592838 and parameters: {'alpha': 0.0007280522924329612, 'l1_ratio': 0.8773797137965119}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,278] Trial 92 finished with value: 0.01352685224316376 and parameters: {'alpha': 0.0002193767168673038, 'l1_ratio': 0.9978001248918499}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,288] Trial 93 finished with value: 0.013515874301465568 and parameters: {'alpha': 0.0005467124417579552, 'l1_ratio': 0.8510381754940748}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,297] Trial 94 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.003992254413828975, 'l1_ratio': 0.8856505118749132}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,306] Trial 95 finished with value: 0.013526126899546222 and parameters: {'alpha': 0.0022499627664679745, 'l1_ratio': 0.9152397711887379}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,316] Trial 96 finished with value: 0.01351338475426589 and parameters: {'alpha': 0.0008193955622977888, 'l1_ratio': 0.9432613257058549}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,327] Trial 97 finished with value: 0.013526742071832095 and parameters: {'alpha': 0.0002669305093072792, 'l1_ratio': 0.8233453602642049}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,338] Trial 98 finished with value: 0.013546530137660287 and parameters: {'alpha': 0.0001410222994670065, 'l1_ratio': 0.27046269588107946}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,347] Trial 99 finished with value: 0.013515148829558593 and parameters: {'alpha': 0.0010971472405822376, 'l1_ratio': 0.9404114786603938}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,359] Trial 100 finished with value: 0.013532064601137738 and parameters: {'alpha': 0.0003994905521274266, 'l1_ratio': 0.3820622876205727}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,369] Trial 101 finished with value: 0.013512549344762715 and parameters: {'alpha': 0.0006580894373930268, 'l1_ratio': 0.9671310224067435}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,379] Trial 102 finished with value: 0.013512980033909933 and parameters: {'alpha': 0.0023626425189188283, 'l1_ratio': 0.30634773586359787}. Best is trial 71 with value: 0.01351227578214879.
[I 2026-10-08 19:49:27,389] Trial 103 finished with value: 0.01351221027824664 and parameters: {'alpha': 0.002162515358742725, 'l1_ratio': 0.30661071385855826}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,399] Trial 104 finished with value: 0.013524372666344393 and parameters: {'alpha': 0.002178828363547945, 'l1_ratio': 0.9065146815939834}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,406] Trial 105 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.015420698421448857, 'l1_ratio': 0.4485262488878936}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,414] Trial 106 finished with value: 0.013524821532755837 and parameters: {'alpha': 0.006559805514973646, 'l1_ratio': 0.3018036891737338}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,423] Trial 107 finished with value: 0.013528785368028708 and parameters: {'alpha': 0.0005510233452003462, 'l1_ratio': 0.34061814292822057}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,432] Trial 108 finished with value: 0.01351652066661015 and parameters: {'alpha': 0.0035707518582375483, 'l1_ratio': 0.32686090406832286}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,440] Trial 109 finished with value: 0.01352101005492141 and parameters: {'alpha': 0.0013240838671631512, 'l1_ratio': 0.24959811092452422}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,451] Trial 110 finished with value: 0.013538954092326836 and parameters: {'alpha': 0.00032372785506283434, 'l1_ratio': 0.28108230278034807}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,461] Trial 111 finished with value: 0.013512417259521346 and parameters: {'alpha': 0.0024750983908994294, 'l1_ratio': 0.2207825943357793}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,470] Trial 112 finished with value: 0.013521934377973839 and parameters: {'alpha': 0.0019312236818782515, 'l1_ratio': 0.15492538700566838}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,479] Trial 113 finished with value: 0.013531480919188255 and parameters: {'alpha': 0.0006783973974939212, 'l1_ratio': 0.22827697662461066}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,488] Trial 114 finished with value: 0.013533362584680275 and parameters: {'alpha': 0.004847971263100054, 'l1_ratio': 0.50571696959185}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,497] Trial 115 finished with value: 0.013525255352934138 and parameters: {'alpha': 0.0011937430227724158, 'l1_ratio': 0.19382828871530267}. Best is trial 103 with value: 0.01351221027824664.
[I 2026-10-08 19:49:27,509] Trial 116 finished with value: 0.013552325924908138 and parameters: {'alpha': 0.00016057604978820796, 'l1_ratio': 0.004393032527963303}. Best is trial 103 with value: 0.01351221027824664.

54

[I 2026-10-08 19:49:28,551] Trial 23 finished with value: 0.013506991908735045 and parameters: {'alpha': 0.0009189392063339386, 'l1_ratio': 0.11595132375984218}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,562] Trial 24 finished with value: 0.013514588284929005 and parameters: {'alpha': 5.927209927526083e-05, 'l1_ratio': 0.5983851900332179}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,571] Trial 25 finished with value: 0.013510337719865994 and parameters: {'alpha': 0.005203339163762094, 'l1_ratio': 0.4338542943668338}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,582] Trial 26 finished with value: 0.013510448310898837 and parameters: {'alpha': 0.0002738924056899977, 'l1_ratio': 0.2693879327545573}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,591] Trial 27 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.020140559599619846, 'l1_ratio': 0.7256858619471043}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,599] Trial 28 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.0027169811691121165, 'l1_ratio': 0.9224232239767937}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,607] Trial 29 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.053302230541146536, 'l1_ratio': 0.5703368400287908}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,617] Trial 30 finished with value: 0.013517552695413847 and parameters: {'alpha': 2.172331162092947e-05, 'l1_ratio': 0.4607778799583291}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,626] Trial 31 finished with value: 0.013498004830939964 and parameters: {'alpha': 0.0008237810827520111, 'l1_ratio': 0.5202999435354688}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,637] Trial 32 finished with value: 0.013502777213892548 and parameters: {'alpha': 0.0006220443470286849, 'l1_ratio': 0.3121841378851441}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,646] Trial 33 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.008388748057929562, 'l1_ratio': 0.8232800969823619}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,656] Trial 34 finished with value: 0.013516846880291351 and parameters: {'alpha': 9.737416140140212e-05, 'l1_ratio': 0.14810236781738495}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,665] Trial 35 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.10100072067190746, 'l1_ratio': 0.6914089457884783}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,675] Trial 36 finished with value: 0.01351506082387536 and parameters: {'alpha': 0.0003867520478946563, 'l1_ratio': 0.0632157869816741}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,685] Trial 37 finished with value: 0.013505357631340106 and parameters: {'alpha': 0.0021121450388135415, 'l1_ratio': 0.40881747131424184}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,694] Trial 38 finished with value: 0.01351813160400425 and parameters: {'alpha': 1.0107177308556151e-05, 'l1_ratio': 0.5397444291879083}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,704] Trial 39 finished with value: 0.013512007004586605 and parameters: {'alpha': 1.7620068426286548, 'l1_ratio': 0.7287738136913626}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,715] Trial 40 finished with value: 0.01351184620807765 and parameters: {'alpha': 0.00012990502983473257, 'l1_ratio': 0.4711613813464278}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,726] Trial 41 finished with value: 0.013500302437811569 and parameters: {'alpha': 0.0005193378604133491, 'l1_ratio': 0.6231135793216718}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,737] Trial 42 finished with value: 0.013500216807780064 and parameters: {'alpha': 0.0005123731228310298, 'l1_ratio': 0.6382535196288266}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,748] Trial 43 finished with value: 0.01350035602038051 and parameters: {'alpha': 0.0005069722414129279, 'l1_ratio': 0.6347585007125603}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,760] Trial 44 finished with value: 0.013515890776760398 and parameters: {'alpha': 4.435806758735447e-05, 'l1_ratio': 0.5390062697000588}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,772] Trial 45 finished with value: 0.013503022504114047 and parameters: {'alpha': 0.00025329424206879344, 'l1_ratio': 0.7698812813923437}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,784] Trial 46 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.006538235151601458, 'l1_ratio': 0.6486093668831518}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,796] Trial 47 finished with value: 0.013518461077804605 and parameters: {'alpha': 4.913500579769662e-06, 'l1_ratio': 0.5843192275713632}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,807] Trial 48 finished with value: 0.013499240602087802 and parameters: {'alpha': 0.000719910865956378, 'l1_ratio': 0.5053896089090205}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,820] Trial 49 finished with value: 0.013498276160672494 and parameters: {'alpha': 0.0012032124152939274, 'l1_ratio': 0.48937175557366863}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,830] Trial 50 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.02962435564670365, 'l1_ratio': 0.47048446008939954}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,841] Trial 51 finished with value: 0.013499925642254192 and parameters: {'alpha': 0.0013392241895402537, 'l1_ratio': 0.4925530393777917}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,852] Trial 52 finished with value: 0.01350024595569867 and parameters: {'alpha': 0.0013341010317993497, 'l1_ratio': 0.503159883546535}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,863] Trial 53 finished with value: 0.013508174340583759 and parameters: {'alpha': 0.0028780449774492263, 'l1_ratio': 0.38953194783413614}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,875] Trial 54 finished with value: 0.013514703124962746 and parameters: {'alpha': 9.391924406074664e-05, 'l1_ratio': 0.35879431353815733}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,887] Trial 55 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.010254776491389079, 'l1_ratio': 0.312831431195856}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,897] Trial 56 finished with value: 0.013497776596768719 and parameters: {'alpha': 0.0009812859571801335, 'l1_ratio': 0.5703805583524617}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,907] Trial 57 finished with value: 0.013510609187228646 and parameters: {'alpha': 0.004118288634013329, 'l1_ratio': 0.5539138125816802}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,919] Trial 58 finished with value: 0.013510567925165726 and parameters: {'alpha': 0.0001755644349188925, 'l1_ratio': 0.42294210699952967}. Best is trial 9 with value: 0.013497393575647988.
[I 2026-10-08 19:49:28,929] Trial 59 finished with value: 0.01349707496621243 and parameters: {'alpha': 0.001135076337002901, 'l1_ratio': 0.44319965380056414}. Best is trial 59 with value: 0.01349707496621243.
[I 2026-10-08 19:49:28,940] Trial 60 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.020301212083235324, 'l1_ratio': 0.9567644327248281}. Best is trial 59 with value: 0.01349707496621243.
[I 2026-10-08 19:49:28,951] Trial 61 finished with value: 0.013496981468618763 and parameters: {'alpha': 0.0011803963465980385, 'l1_ratio': 0.43672583589834735}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:28,959] Trial 62 finished with value: 0.013498598463856978 and parameters: {'alpha': 0.0013786310241125238, 'l1_ratio': 0.4397778728092162}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:28,970] Trial 63 finished with value: 0.013504439171663149 and parameters: {'alpha': 0.000275135568035029, 'l1_ratio': 0.5848649241804964}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:28,980] Trial 64 finished with value: 0.013507565388587073 and parameters: {'alpha': 0.004591298328289622, 'l1_ratio': 0.3381673334723426}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:28,991] Trial 65 finished with value: 0.013515518125810264 and parameters: {'alpha': 6.725215266232061e-05, 'l1_ratio': 0.3981299753929445}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,000] Trial 66 finished with value: 0.013505443772529737 and parameters: {'alpha': 0.0009403516594900875, 'l1_ratio': 0.8835646642149125}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,012] Trial 67 finished with value: 0.013517382994032375 and parameters: {'alpha': 2.5029764496232582e-05, 'l1_ratio': 0.4543167791217121}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,020] Trial 68 finished with value: 0.013512007004586605 and parameters: {'alpha': 44.993574795304646, 'l1_ratio': 0.5237045060585939}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,029] Trial 69 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.012768549707834668, 'l1_ratio': 0.26135346785147817}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,035] Trial 70 finished with value: 0.013506791409926135 and parameters: {'alpha': 0.002459815802197369, 'l1_ratio': 0.6835823439308165}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,044] Trial 71 finished with value: 0.013498321639044412 and parameters: {'alpha': 0.0013757579051717527, 'l1_ratio': 0.4314534639396748}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,055] Trial 72 finished with value: 0.013506821921360468 and parameters: {'alpha': 0.0002487155735093379, 'l1_ratio': 0.4857133878858846}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,064] Trial 73 finished with value: 0.01349715206717574 and parameters: {'alpha': 0.000901490285146436, 'l1_ratio': 0.5585717329659191}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,072] Trial 74 finished with value: 0.01349746988446589 and parameters: {'alpha': 0.0008320299428651396, 'l1_ratio': 0.5652006082273957}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,079] Trial 75 finished with value: 0.013509429385335786 and parameters: {'alpha': 0.003925669611240661, 'l1_ratio': 0.5548667801383048}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,089] Trial 76 finished with value: 0.01350166880249596 and parameters: {'alpha': 0.00042095774644601065, 'l1_ratio': 0.6084064208394799}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,102] Trial 77 finished with value: 0.013510224085474266 and parameters: {'alpha': 0.00013870487570791907, 'l1_ratio': 0.5684259412926544}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,114] Trial 78 finished with value: 0.013518821703034712 and parameters: {'alpha': 1.03884177183244e-07, 'l1_ratio': 0.5220411718705898}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,122] Trial 79 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.007640322830572394, 'l1_ratio': 0.7120914245105189}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,131] Trial 80 finished with value: 0.013497774878197399 and parameters: {'alpha': 0.0006847885441781939, 'l1_ratio': 0.6557104464401732}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,142] Trial 81 finished with value: 0.013497702675787914 and parameters: {'alpha': 0.0006842721002072473, 'l1_ratio': 0.6645966094678416}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,150] Trial 82 finished with value: 0.013507123671525295 and parameters: {'alpha': 0.0022732269935463504, 'l1_ratio': 0.8176513264390041}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,159] Trial 83 finished with value: 0.013497539394415206 and parameters: {'alpha': 0.0007109833230598431, 'l1_ratio': 0.6582006971868829}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,169] Trial 84 finished with value: 0.013502566137760331 and parameters: {'alpha': 0.00031367559034707837, 'l1_ratio': 0.6636382679679858}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,178] Trial 85 finished with value: 0.013497477910025457 and parameters: {'alpha': 0.0006903046374950156, 'l1_ratio': 0.7778381117914956}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,188] Trial 86 finished with value: 0.013512076268009083 and parameters: {'alpha': 7.945845075222551e-05, 'l1_ratio': 0.7521610799470597}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,199] Trial 87 finished with value: 0.01350663266212889 and parameters: {'alpha': 0.00014570284965277652, 'l1_ratio': 0.8609286371164311}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,209] Trial 88 finished with value: 0.013514997476546154 and parameters: {'alpha': 3.978707314125324e-05, 'l1_ratio': 0.8061702856701577}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,218] Trial 89 finished with value: 0.013509276378209194 and parameters: {'alpha': 0.001988838860992198, 'l1_ratio': 0.7047495989935396}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,227] Trial 90 finished with value: 0.013499906946371626 and parameters: {'alpha': 0.00045126831262702784, 'l1_ratio': 0.7545286441848792}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,236] Trial 91 finished with value: 0.013498110228987682 and parameters: {'alpha': 0.0005719605684228042, 'l1_ratio': 0.9969927182753732}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,247] Trial 92 finished with value: 0.013497258118772133 and parameters: {'alpha': 0.0007509816501364192, 'l1_ratio': 0.6609922869299265}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,258] Trial 93 finished with value: 0.013507415687509428 and parameters: {'alpha': 0.00018423409020145606, 'l1_ratio': 0.6155573821041711}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,266] Trial 94 finished with value: 0.013510049255957904 and parameters: {'alpha': 0.003020357852649376, 'l1_ratio': 0.7404198985628219}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,275] Trial 95 finished with value: 0.01349714042312106 and parameters: {'alpha': 0.0007593356779492661, 'l1_ratio': 0.6752976000958703}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,285] Trial 96 finished with value: 0.013506142812294125 and parameters: {'alpha': 0.0016304775048368652, 'l1_ratio': 0.6016911875339676}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,294] Trial 97 finished with value: 0.013499994802414851 and parameters: {'alpha': 0.0003720002240507905, 'l1_ratio': 0.9099040661008078}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,303] Trial 98 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.006215053767638945, 'l1_ratio': 0.7821772089653898}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,313] Trial 99 finished with value: 0.013500108223702944 and parameters: {'alpha': 0.0009477613547019023, 'l1_ratio': 0.6982655270965903}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,322] Trial 100 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.003788820495130266, 'l1_ratio': 0.6336028249550392}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,332] Trial 101 finished with value: 0.013497165659462932 and parameters: {'alpha': 0.0007794774910867679, 'l1_ratio': 0.6705974291273281}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,342] Trial 102 finished with value: 0.013502520300472646 and parameters: {'alpha': 0.00022261109255297055, 'l1_ratio': 0.9530535218290201}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,353] Trial 103 finished with value: 0.013500313711994635 and parameters: {'alpha': 0.0009240085270147378, 'l1_ratio': 0.7240246784347889}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,363] Trial 104 finished with value: 0.013508660931086438 and parameters: {'alpha': 0.001727982173439449, 'l1_ratio': 0.839146901429841}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,373] Trial 105 finished with value: 0.01350255226421623 and parameters: {'alpha': 0.0003041113739567263, 'l1_ratio': 0.6869237641622888}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,384] Trial 106 finished with value: 0.013498416422055258 and parameters: {'alpha': 0.0006345459156515769, 'l1_ratio': 0.6427696025884151}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,394] Trial 107 finished with value: 0.013508287646520943 and parameters: {'alpha': 0.0019312697593811953, 'l1_ratio': 0.5811384303922211}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,403] Trial 108 finished with value: 0.013497610871529167 and parameters: {'alpha': 0.0010163940930473416, 'l1_ratio': 0.5422561243188188}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,413] Trial 109 finished with value: 0.013498243139685452 and parameters: {'alpha': 0.0010700432315141192, 'l1_ratio': 0.5468551165571082}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,423] Trial 110 finished with value: 0.013510756118170774 and parameters: {'alpha': 0.00011762727206816478, 'l1_ratio': 0.6225295436054117}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,431] Trial 111 finished with value: 0.013501609324208469 and parameters: {'alpha': 0.00043768432972728837, 'l1_ratio': 0.6016372710939283}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,440] Trial 112 finished with value: 0.013506947133139678 and parameters: {'alpha': 0.0026760275927716886, 'l1_ratio': 0.6725252037202621}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,449] Trial 113 finished with value: 0.013500672135954656 and parameters: {'alpha': 0.0006804209100066945, 'l1_ratio': 0.4511102958081379}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,460] Trial 114 finished with value: 0.013507623783621152 and parameters: {'alpha': 0.00020425435516247418, 'l1_ratio': 0.5393599085638605}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,470] Trial 115 finished with value: 0.013499478488260571 and parameters: {'alpha': 0.001340746344090911, 'l1_ratio': 0.4792724596761034}. Best is trial 61 with value: 0.013496981468618763.
[I 2026-10-08 19:49:29,479] Trial 116 finished with value: 0.013512007004586605 and parameters: {'alpha': 0.0051920495684976645, 'l1_ratio': 0.586777373189126}. Best is trial 61 with value: 0.013496981468618763.

60

[I 2026-10-08 19:49:30,528] Trial 22 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.010435688853062924, 'l1_ratio': 0.49519292471619397}. Best is trial 19 with value: 0.016591968821566244.
[I 2026-10-08 19:49:30,538] Trial 23 finished with value: 0.01659180309990907 and parameters: {'alpha': 0.0006984930624187076, 'l1_ratio': 0.6380703050832495}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,548] Trial 24 finished with value: 0.016605992063702373 and parameters: {'alpha': 4.924047737219532e-05, 'l1_ratio': 0.6661807121552853}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,557] Trial 25 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.1665212538309641, 'l1_ratio': 0.8303828306156894}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,566] Trial 26 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.06067856182093552, 'l1_ratio': 0.5408871683225822}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,575] Trial 27 finished with value: 0.01659635810594967 and parameters: {'alpha': 0.0015236364430328067, 'l1_ratio': 0.6331357165126484}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,586] Trial 28 finished with value: 0.01660981637551242 and parameters: {'alpha': 1.8730345340017544e-06, 'l1_ratio': 0.33344000728698364}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,596] Trial 29 finished with value: 0.01660801841566302 and parameters: {'alpha': 7.510914873518617e-05, 'l1_ratio': 0.18879776343959076}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,607] Trial 30 finished with value: 0.01660768777695715 and parameters: {'alpha': 1.714313373582534, 'l1_ratio': 0.5109023699249757}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,617] Trial 31 finished with value: 0.016593008542055757 and parameters: {'alpha': 0.0007912455849380018, 'l1_ratio': 0.4341287997243384}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,627] Trial 32 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.006430832943627805, 'l1_ratio': 0.387121301401319}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,637] Trial 33 finished with value: 0.016596454571228415 and parameters: {'alpha': 0.000534215564329633, 'l1_ratio': 0.2709371027697986}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,648] Trial 34 finished with value: 0.01660930642184007 and parameters: {'alpha': 1.0065002196005887e-05, 'l1_ratio': 0.4583422987490094}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,658] Trial 35 finished with value: 0.01660014989251869 and parameters: {'alpha': 0.00013581898997189608, 'l1_ratio': 0.6934390669558479}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,667] Trial 36 finished with value: 0.016600420727474655 and parameters: {'alpha': 0.0021937377534774335, 'l1_ratio': 0.7662765582311901}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,675] Trial 37 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.10004642568302255, 'l1_ratio': 0.5615438829297036}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,683] Trial 38 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.02100113970007618, 'l1_ratio': 0.6407477251337763}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,694] Trial 39 finished with value: 0.01659482978286761 and parameters: {'alpha': 0.000800274635259467, 'l1_ratio': 0.9210664892975933}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,704] Trial 40 finished with value: 0.016599157884672134 and parameters: {'alpha': 0.004645559588633074, 'l1_ratio': 0.24728832186931066}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,714] Trial 41 finished with value: 0.016595186971521184 and parameters: {'alpha': 0.0004169581087295506, 'l1_ratio': 0.41911273035705465}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,723] Trial 42 finished with value: 0.016592877112671028 and parameters: {'alpha': 0.0010359023425727846, 'l1_ratio': 0.3371865362054003}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,733] Trial 43 finished with value: 0.01660947167855597 and parameters: {'alpha': 2.2142940644277533e-05, 'l1_ratio': 0.13645611063261773}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,742] Trial 44 finished with value: 0.01659294737290938 and parameters: {'alpha': 0.0009051615637248508, 'l1_ratio': 0.3438107583152131}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,753] Trial 45 finished with value: 0.016604365928014276 and parameters: {'alpha': 0.0001377731103719529, 'l1_ratio': 0.3400479369849738}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,763] Trial 46 finished with value: 0.01660079169016053 and parameters: {'alpha': 0.012546784570650357, 'l1_ratio': 0.12830097666069173}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,774] Trial 47 finished with value: 0.01660246149725204 and parameters: {'alpha': 0.0033248628735986596, 'l1_ratio': 0.004037551238076864}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,783] Trial 48 finished with value: 0.016592978514582205 and parameters: {'alpha': 0.000966480662087905, 'l1_ratio': 0.2998543843387073}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,791] Trial 49 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.5907305602282473, 'l1_ratio': 0.3803254743085705}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,802] Trial 50 finished with value: 0.016604705234201603 and parameters: {'alpha': 0.00019152338995836286, 'l1_ratio': 0.22198948993858864}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,809] Trial 51 finished with value: 0.016592803502896884 and parameters: {'alpha': 0.0011583241855364795, 'l1_ratio': 0.3004117774420996}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,819] Trial 52 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.04360914365071553, 'l1_ratio': 0.3118460022687}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,827] Trial 53 finished with value: 0.016602100016939896 and parameters: {'alpha': 0.0029361264670941024, 'l1_ratio': 0.46928710569338633}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,838] Trial 54 finished with value: 0.016607155934340055 and parameters: {'alpha': 6.258949323675082e-05, 'l1_ratio': 0.35112471881111107}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,849] Trial 55 finished with value: 0.01660226947928244 and parameters: {'alpha': 0.000276271098077826, 'l1_ratio': 0.2408992855749936}. Best is trial 23 with value: 0.01659180309990907.
[I 2026-10-08 19:49:30,857] Trial 56 finished with value: 0.016591421418078893 and parameters: {'alpha': 0.0012126405413935596, 'l1_ratio': 0.4992012962495947}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,867] Trial 57 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.012086538259478077, 'l1_ratio': 0.5193429649910246}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,876] Trial 58 finished with value: 0.01660768777695715 and parameters: {'alpha': 90.07393692814512, 'l1_ratio': 0.6090372092021421}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,886] Trial 59 finished with value: 0.01660842920328349 and parameters: {'alpha': 2.4062039709268762e-05, 'l1_ratio': 0.4845326774431183}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,896] Trial 60 finished with value: 0.016594843767898246 and parameters: {'alpha': 0.0012480100792486841, 'l1_ratio': 0.5953339235535262}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,905] Trial 61 finished with value: 0.016594143242730817 and parameters: {'alpha': 0.0017787587001193283, 'l1_ratio': 0.4081544697127522}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,915] Trial 62 finished with value: 0.01659709796217164 and parameters: {'alpha': 0.0004235971728300059, 'l1_ratio': 0.318076667558966}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,926] Trial 63 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.0067180478631228046, 'l1_ratio': 0.3712932635625163}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,938] Trial 64 finished with value: 0.016603173350555632 and parameters: {'alpha': 0.00013027853965982074, 'l1_ratio': 0.45476063492593344}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,948] Trial 65 finished with value: 0.016592432882279202 and parameters: {'alpha': 0.0013966340663292057, 'l1_ratio': 0.2821760354266965}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,959] Trial 66 finished with value: 0.016595938518389294 and parameters: {'alpha': 0.0032962246701871796, 'l1_ratio': 0.2818172461832941}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,970] Trial 67 finished with value: 0.01659533266300893 and parameters: {'alpha': 0.00031190757529840743, 'l1_ratio': 0.5546985740569546}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,981] Trial 68 finished with value: 0.016608898475878233 and parameters: {'alpha': 3.937638287980638e-05, 'l1_ratio': 0.1882321455555732}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:30,991] Trial 69 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.007098449452052654, 'l1_ratio': 0.7442649872844123}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:31,001] Trial 70 finished with value: 0.01659563017888524 and parameters: {'alpha': 0.0015324336891515996, 'l1_ratio': 0.5184627270022217}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:31,013] Trial 71 finished with value: 0.01659405202785416 and parameters: {'alpha': 0.0005350894816028988, 'l1_ratio': 0.39159330969710754}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:31,024] Trial 72 finished with value: 0.016592899985103986 and parameters: {'alpha': 0.0009565098561597759, 'l1_ratio': 0.34147233918547437}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:31,035] Trial 73 finished with value: 0.016605236880173013 and parameters: {'alpha': 8.809990943198299e-05, 'l1_ratio': 0.44514863504677415}. Best is trial 56 with value: 0.016591421418078893.
[I 2026-10-08 19:49:31,045] Trial 74 finished with value: 0.016591390414815915 and parameters: {'alpha': 0.0020570766777731706, 'l1_ratio': 0.21169715017432272}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,053] Trial 75 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.02523333985095769, 'l1_ratio': 0.2802453230777347}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,063] Trial 76 finished with value: 0.016593346358856148 and parameters: {'alpha': 0.002157164447091349, 'l1_ratio': 0.09118565795750846}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,070] Trial 77 finished with value: 0.016596498511099914 and parameters: {'alpha': 0.004152647697844038, 'l1_ratio': 0.23893399761311396}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,080] Trial 78 finished with value: 0.016599706917415784 and parameters: {'alpha': 0.0005750855550146876, 'l1_ratio': 0.16138908240850536}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,087] Trial 79 finished with value: 0.016604586960559022 and parameters: {'alpha': 0.0098703297251318, 'l1_ratio': 0.22084326912492347}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,097] Trial 80 finished with value: 0.016600375122722513 and parameters: {'alpha': 0.0002151435056787758, 'l1_ratio': 0.4184144862420615}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,107] Trial 81 finished with value: 0.0165922029579852 and parameters: {'alpha': 0.0011459582072039939, 'l1_ratio': 0.35907644654324267}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,116] Trial 82 finished with value: 0.01659457554723269 and parameters: {'alpha': 0.0019980762307541433, 'l1_ratio': 0.37183752222864436}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,125] Trial 83 finished with value: 0.016595837593021523 and parameters: {'alpha': 0.0010739547736666655, 'l1_ratio': 0.8178054714387734}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,136] Trial 84 finished with value: 0.016594840428106966 and parameters: {'alpha': 0.0006738501184605756, 'l1_ratio': 0.2658491135569102}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,145] Trial 85 finished with value: 0.01660080105420464 and parameters: {'alpha': 0.004806237117266656, 'l1_ratio': 0.32324290504998077}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,155] Trial 86 finished with value: 0.01659931215578787 and parameters: {'alpha': 0.0003479873179501662, 'l1_ratio': 0.2926395363749538}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,164] Trial 87 finished with value: 0.016602010611194117 and parameters: {'alpha': 0.002793219273953762, 'l1_ratio': 0.4982164765184712}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,172] Trial 88 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.014611922598719233, 'l1_ratio': 0.2053908172638882}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,181] Trial 89 finished with value: 0.01660768777695715 and parameters: {'alpha': 7.153401312280608, 'l1_ratio': 0.16701649251145967}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,191] Trial 90 finished with value: 0.016591798935232112 and parameters: {'alpha': 0.0014402127599957674, 'l1_ratio': 0.4362385375884702}. Best is trial 74 with value: 0.016591390414815915.
[I 2026-10-08 19:49:31,201] Trial 91 finished with value: 0.016591135281426656 and parameters: {'alpha': 0.001287197109289922, 'l1_ratio': 0.3980304808908989}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,209] Trial 92 finished with value: 0.016592443872976613 and parameters: {'alpha': 0.001496870972118215, 'l1_ratio': 0.4396080537576456}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,220] Trial 93 finished with value: 0.016592984444736805 and parameters: {'alpha': 0.0016953556499089589, 'l1_ratio': 0.402764902041837}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,231] Trial 94 finished with value: 0.01660201843076636 and parameters: {'alpha': 0.00016119477137276582, 'l1_ratio': 0.4425162191806141}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,239] Trial 95 finished with value: 0.016593054779108028 and parameters: {'alpha': 0.0007180015001946586, 'l1_ratio': 0.48094610558970435}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,248] Trial 96 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.006648306068631914, 'l1_ratio': 0.532610180046558}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,258] Trial 97 finished with value: 0.01660257331656145 and parameters: {'alpha': 9.868290991340247e-05, 'l1_ratio': 0.6712922875698392}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,267] Trial 98 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.04027495793816676, 'l1_ratio': 0.42982025772861093}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,279] Trial 99 finished with value: 0.016599371162541978 and parameters: {'alpha': 0.00026255849310786495, 'l1_ratio': 0.3900339240658493}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,289] Trial 100 finished with value: 0.016594666792240968 and parameters: {'alpha': 0.0004033164633954074, 'l1_ratio': 0.4707020735404031}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,300] Trial 101 finished with value: 0.016591837904886282 and parameters: {'alpha': 0.0011633303899336051, 'l1_ratio': 0.3707400286868012}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,310] Trial 102 finished with value: 0.016599468105609444 and parameters: {'alpha': 0.00317193779759428, 'l1_ratio': 0.3654715278846852}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,320] Trial 103 finished with value: 0.016591185358622893 and parameters: {'alpha': 0.001391267770596754, 'l1_ratio': 0.41464837795254195}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,329] Trial 104 finished with value: 0.016593604775348166 and parameters: {'alpha': 0.0005748666332368767, 'l1_ratio': 0.41087358041610206}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,338] Trial 105 finished with value: 0.016594241757486625 and parameters: {'alpha': 0.0020318117988689073, 'l1_ratio': 0.360431625517992}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,347] Trial 106 finished with value: 0.016603384976990293 and parameters: {'alpha': 0.0041504605794841064, 'l1_ratio': 0.5052230607925737}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,356] Trial 107 finished with value: 0.016591199664312283 and parameters: {'alpha': 0.0012807727385623431, 'l1_ratio': 0.38231412079186544}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,368] Trial 108 finished with value: 0.016591315689534956 and parameters: {'alpha': 0.0008895172839293887, 'l1_ratio': 0.5646079612478088}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,378] Trial 109 finished with value: 0.016593272917441088 and parameters: {'alpha': 0.00046454721805038314, 'l1_ratio': 0.6286116215737003}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,387] Trial 110 finished with value: 0.016600698380498217 and parameters: {'alpha': 0.0027295033989031673, 'l1_ratio': 0.5755553954869499}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,397] Trial 111 finished with value: 0.01659308048167154 and parameters: {'alpha': 0.0008184037150534902, 'l1_ratio': 0.46035240146972733}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,408] Trial 112 finished with value: 0.01659287683393425 and parameters: {'alpha': 0.0012540517273205943, 'l1_ratio': 0.5360937126358197}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,417] Trial 113 finished with value: 0.01660768777695715 and parameters: {'alpha': 0.009222142357369496, 'l1_ratio': 0.5823943393016958}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,428] Trial 114 finished with value: 0.016593123059413142 and parameters: {'alpha': 0.0006970824887857308, 'l1_ratio': 0.42176859700795666}. Best is trial 91 with value: 0.016591135281426656.
[I 2026-10-08 19:49:31,438] Trial 115 finished with value: 0.01659633092783577 and parameters: {'alpha': 0.00030911876740564455, 'l1_ratio': 0.4881899066668515}. Best is trial 91 with value: 0.016591135281426656.

66

[I 2026-10-08 19:49:32,521] Trial 24 finished with value: 0.014752380079226224 and parameters: {'alpha': 8.247398463503304e-06, 'l1_ratio': 0.39727769785687805}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,531] Trial 25 finished with value: 0.014736944578105024 and parameters: {'alpha': 6.606422346285988e-05, 'l1_ratio': 0.9033544412395229}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,540] Trial 26 finished with value: 0.014686860618238791 and parameters: {'alpha': 0.0013779307715767733, 'l1_ratio': 0.549466242994655}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,547] Trial 27 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.05347069584517518, 'l1_ratio': 0.7444358948731767}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,555] Trial 28 finished with value: 0.01469187559081659 and parameters: {'alpha': 0.0037884702466808814, 'l1_ratio': 0.316547761997657}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,563] Trial 29 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.42505364913493693, 'l1_ratio': 0.5212454649714384}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,572] Trial 30 finished with value: 0.014726626891769547 and parameters: {'alpha': 0.00011503544994230452, 'l1_ratio': 0.8829808119773311}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,580] Trial 31 finished with value: 0.014689904175829532 and parameters: {'alpha': 0.0006281570169095255, 'l1_ratio': 0.5887041150422383}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,587] Trial 32 finished with value: 0.014695924422926894 and parameters: {'alpha': 0.00249979765066598, 'l1_ratio': 0.6720758305090845}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,595] Trial 33 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.012975882604978726, 'l1_ratio': 0.3725222479827473}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,605] Trial 34 finished with value: 0.014715021455778179 and parameters: {'alpha': 0.00027781318407551516, 'l1_ratio': 0.5500780197784569}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,615] Trial 35 finished with value: 0.014747880370396427 and parameters: {'alpha': 4.1648075516217735e-05, 'l1_ratio': 0.4453240070632275}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,625] Trial 36 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.0256186285515809, 'l1_ratio': 0.2875636895230256}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,633] Trial 37 finished with value: 0.014695837553158475 and parameters: {'alpha': 0.0023724266573358676, 'l1_ratio': 0.7037882340468398}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,642] Trial 38 finished with value: 0.014690754153468818 and parameters: {'alpha': 0.0004306325095874511, 'l1_ratio': 0.7829092343650053}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,651] Trial 39 finished with value: 0.014704800919816203 and parameters: {'alpha': 1.1685573623973404, 'l1_ratio': 0.24547595043881132}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,660] Trial 40 finished with value: 0.014746352839483404 and parameters: {'alpha': 2.4726587363727266e-05, 'l1_ratio': 0.9964592437663828}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,670] Trial 41 finished with value: 0.014686908230509197 and parameters: {'alpha': 0.0009316676177057831, 'l1_ratio': 0.8119154628890424}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,678] Trial 42 finished with value: 0.014687339495719313 and parameters: {'alpha': 0.0009303894989204742, 'l1_ratio': 0.8366973692396432}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,689] Trial 43 finished with value: 0.014718568456151495 and parameters: {'alpha': 0.00015013412040613814, 'l1_ratio': 0.9171081591933787}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,699] Trial 44 finished with value: 0.01469326348678122 and parameters: {'alpha': 0.002053809844406866, 'l1_ratio': 0.6368043829449153}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,707] Trial 45 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.007023521388595544, 'l1_ratio': 0.719535690637702}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,715] Trial 46 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.027553378630228175, 'l1_ratio': 0.761367827503688}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,726] Trial 47 finished with value: 0.01473626618503088 and parameters: {'alpha': 0.00011339838815182317, 'l1_ratio': 0.540108989636266}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,737] Trial 48 finished with value: 0.014753358715774564 and parameters: {'alpha': 1.0102172852537374e-06, 'l1_ratio': 0.02956994560133963}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,746] Trial 49 finished with value: 0.014687461060554935 and parameters: {'alpha': 0.00092143053551687, 'l1_ratio': 0.8510996042804713}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,754] Trial 50 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.005513821063104366, 'l1_ratio': 0.6020727405994348}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,762] Trial 51 finished with value: 0.014687847194381069 and parameters: {'alpha': 0.0011641798545211405, 'l1_ratio': 0.8246048673645994}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,774] Trial 52 finished with value: 0.014689095784611453 and parameters: {'alpha': 0.0004254529146924911, 'l1_ratio': 0.9472436058597488}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,783] Trial 53 finished with value: 0.014692238400030188 and parameters: {'alpha': 0.0014254923755195735, 'l1_ratio': 0.8598487590717935}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,793] Trial 54 finished with value: 0.014702807154218438 and parameters: {'alpha': 0.00027845085060622713, 'l1_ratio': 0.7909227567991363}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,803] Trial 55 finished with value: 0.014749720490911968 and parameters: {'alpha': 8.009016840688902e-05, 'l1_ratio': 0.13455384007971555}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,816] Trial 56 finished with value: 0.014753353777203913 and parameters: {'alpha': 1.0444684282514544e-07, 'l1_ratio': 0.7021910482762115}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,824] Trial 57 finished with value: 0.014704800919816203 and parameters: {'alpha': 89.46676761247097, 'l1_ratio': 0.7339745054675654}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,833] Trial 58 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.00399746651014902, 'l1_ratio': 0.6289160232716524}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,841] Trial 59 finished with value: 0.014750590358382937 and parameters: {'alpha': 1.076077679647767e-05, 'l1_ratio': 0.889744026795977}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,850] Trial 60 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.12489540539838007, 'l1_ratio': 0.808050328674356}. Best is trial 4 with value: 0.014685929817356962.
[I 2026-10-08 19:49:32,859] Trial 61 finished with value: 0.014685550676194271 and parameters: {'alpha': 0.0006097171115402254, 'l1_ratio': 0.8535470613383231}. Best is trial 61 with value: 0.014685550676194271.
[I 2026-10-08 19:49:32,868] Trial 62 finished with value: 0.014685459220571054 and parameters: {'alpha': 0.0008443777542676602, 'l1_ratio': 0.7697921187408007}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,878] Trial 63 finished with value: 0.014688740659412045 and parameters: {'alpha': 0.0004485998429504569, 'l1_ratio': 0.9215459691189416}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,886] Trial 64 finished with value: 0.014702307680988838 and parameters: {'alpha': 0.003154598118851134, 'l1_ratio': 0.6875280744720871}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,896] Trial 65 finished with value: 0.014718193097215662 and parameters: {'alpha': 0.0001826337231503353, 'l1_ratio': 0.7605085194243737}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,905] Trial 66 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.010864299119891806, 'l1_ratio': 0.6716487635529141}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,914] Trial 67 finished with value: 0.014704800919816203 and parameters: {'alpha': 10.934044379235313, 'l1_ratio': 0.46898441546974}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,924] Trial 68 finished with value: 0.014691192966651894 and parameters: {'alpha': 0.0005680304270823967, 'l1_ratio': 0.5602640490223513}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,934] Trial 69 finished with value: 0.014692318079060499 and parameters: {'alpha': 0.0012668773960547123, 'l1_ratio': 0.9730064391279247}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,944] Trial 70 finished with value: 0.014745414827162894 and parameters: {'alpha': 3.574367981767069e-05, 'l1_ratio': 0.778586372856382}. Best is trial 62 with value: 0.014685459220571054.
[I 2026-10-08 19:49:32,954] Trial 71 finished with value: 0.01468535350738798 and parameters: {'alpha': 0.0007347055478539203, 'l1_ratio': 0.8640856784003581}. Best is trial 71 with value: 0.01468535350738798.
[I 2026-10-08 19:49:32,965] Trial 72 finished with value: 0.014703487092659086 and parameters: {'alpha': 0.0002477356929538738, 'l1_ratio': 0.8738688062670082}. Best is trial 71 with value: 0.01468535350738798.
[I 2026-10-08 19:49:32,974] Trial 73 finished with value: 0.014694527119853388 and parameters: {'alpha': 0.001772024141492229, 'l1_ratio': 0.8089815265080921}. Best is trial 71 with value: 0.01468535350738798.
[I 2026-10-08 19:49:32,982] Trial 74 finished with value: 0.014685304797969891 and parameters: {'alpha': 0.0006960611253085793, 'l1_ratio': 0.9008969682641493}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:32,991] Trial 75 finished with value: 0.014691004623098889 and parameters: {'alpha': 0.0003459914940320956, 'l1_ratio': 0.9509306864959994}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:32,999] Trial 76 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.004588035275807216, 'l1_ratio': 0.903347539331258}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:33,008] Trial 77 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.019613527801141305, 'l1_ratio': 0.838576182029795}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:33,019] Trial 78 finished with value: 0.014728510058841121 and parameters: {'alpha': 0.00010066322829770508, 'l1_ratio': 0.9310477860709176}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:33,027] Trial 79 finished with value: 0.014685370619849685 and parameters: {'alpha': 0.000737885026187603, 'l1_ratio': 0.8635128447546254}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:33,036] Trial 80 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.002640233380492345, 'l1_ratio': 0.9935199000135037}. Best is trial 74 with value: 0.014685304797969891.
[I 2026-10-08 19:49:33,046] Trial 81 finished with value: 0.014685248050756921 and parameters: {'alpha': 0.000720877153973871, 'l1_ratio': 0.8585388813061371}. Best is trial 81 with value: 0.014685248050756921.
[I 2026-10-08 19:49:33,055] Trial 82 finished with value: 0.014685065955771945 and parameters: {'alpha': 0.0006375771812539968, 'l1_ratio': 0.8775062990167025}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,067] Trial 83 finished with value: 0.014715015481250886 and parameters: {'alpha': 0.0001739640084068666, 'l1_ratio': 0.888823233080727}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,077] Trial 84 finished with value: 0.014688259833331186 and parameters: {'alpha': 0.0004944963069870495, 'l1_ratio': 0.8651992983186102}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,087] Trial 85 finished with value: 0.014685576803334292 and parameters: {'alpha': 0.0007828361735232048, 'l1_ratio': 0.84491258404399}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,096] Trial 86 finished with value: 0.01469497361136394 and parameters: {'alpha': 0.0018004976995875015, 'l1_ratio': 0.8515077879109423}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,107] Trial 87 finished with value: 0.014738287673505695 and parameters: {'alpha': 6.118262284994184e-05, 'l1_ratio': 0.890469307386302}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,117] Trial 88 finished with value: 0.014685299826029292 and parameters: {'alpha': 0.0006469108615289703, 'l1_ratio': 0.9661947507067676}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,126] Trial 89 finished with value: 0.014686305848784359 and parameters: {'alpha': 0.0007849713789037726, 'l1_ratio': 0.9166363535489735}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,137] Trial 90 finished with value: 0.014698268682343378 and parameters: {'alpha': 0.00029883507017880505, 'l1_ratio': 0.8336211686219571}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,149] Trial 91 finished with value: 0.014685244223762169 and parameters: {'alpha': 0.000640706509225994, 'l1_ratio': 0.961151763451198}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,158] Trial 92 finished with value: 0.014685895894064606 and parameters: {'alpha': 0.0007139632999290861, 'l1_ratio': 0.9651098908396013}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,168] Trial 93 finished with value: 0.014718814649369444 and parameters: {'alpha': 0.00014293993203282055, 'l1_ratio': 0.9559754463545427}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,177] Trial 94 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.006628094263873116, 'l1_ratio': 0.9320275273759986}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,185] Trial 95 finished with value: 0.014685684151495359 and parameters: {'alpha': 0.0006719320403490764, 'l1_ratio': 0.9973145666049591}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,192] Trial 96 finished with value: 0.014692621682695852 and parameters: {'alpha': 0.0013871054407587158, 'l1_ratio': 0.9078650666128822}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,200] Trial 97 finished with value: 0.014691178669403305 and parameters: {'alpha': 0.0003714000224625463, 'l1_ratio': 0.8673197923291402}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,208] Trial 98 finished with value: 0.01469955394801232 and parameters: {'alpha': 0.0025312259599015946, 'l1_ratio': 0.7912321177276433}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,218] Trial 99 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.0037918480397077987, 'l1_ratio': 0.753073122239345}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,228] Trial 100 finished with value: 0.014711773075440504 and parameters: {'alpha': 0.0002007022129477558, 'l1_ratio': 0.8508766543039553}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,238] Trial 101 finished with value: 0.014687062062957189 and parameters: {'alpha': 0.0007729082651541818, 'l1_ratio': 0.9877278509185924}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,247] Trial 102 finished with value: 0.01468658005249307 and parameters: {'alpha': 0.0005136650129283243, 'l1_ratio': 0.9386734573113714}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,257] Trial 103 finished with value: 0.014688360662378691 and parameters: {'alpha': 0.0011219842222346945, 'l1_ratio': 0.9016746055721052}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,267] Trial 104 finished with value: 0.014697632317342346 and parameters: {'alpha': 0.0002606561130432378, 'l1_ratio': 0.9737954330933887}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,277] Trial 105 finished with value: 0.014734172866715875 and parameters: {'alpha': 8.054953285368428e-05, 'l1_ratio': 0.8752185301664621}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,285] Trial 106 finished with value: 0.014695253112289438 and parameters: {'alpha': 0.0019197605896497329, 'l1_ratio': 0.8260134371959744}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,294] Trial 107 finished with value: 0.014685074593358466 and parameters: {'alpha': 0.0005869491902190762, 'l1_ratio': 0.9454085746187602}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,304] Trial 108 finished with value: 0.014729260630154846 and parameters: {'alpha': 0.00011614488452062287, 'l1_ratio': 0.7763796343238137}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,314] Trial 109 finished with value: 0.01474271612245638 and parameters: {'alpha': 3.998856524177776e-05, 'l1_ratio': 0.9473356902921533}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,323] Trial 110 finished with value: 0.014704800919816203 and parameters: {'alpha': 0.00848364129258419, 'l1_ratio': 0.9288264829495555}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,332] Trial 111 finished with value: 0.014685379802993748 and parameters: {'alpha': 0.000535778843091835, 'l1_ratio': 0.9859077763052422}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,341] Trial 112 finished with value: 0.014689515133584772 and parameters: {'alpha': 0.0011203633231555517, 'l1_ratio': 0.9719713356859021}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,352] Trial 113 finished with value: 0.014690603321164869 and parameters: {'alpha': 0.0003842659392399424, 'l1_ratio': 0.895193226161589}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,362] Trial 114 finished with value: 0.014685404763256428 and parameters: {'alpha': 0.000575329814046745, 'l1_ratio': 0.915655170036118}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,373] Trial 115 finished with value: 0.01470951687237458 and parameters: {'alpha': 0.0001995102456980654, 'l1_ratio': 0.916252617122103}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,383] Trial 116 finished with value: 0.014686720709182071 and parameters: {'alpha': 0.0004979349701519702, 'l1_ratio': 0.9586878285078452}. Best is trial 82 with value: 0.014685065955771945.
[I 2026-10-08 19:49:33,392] Trial 117 finished with value: 0.014692062806662439 and parameters: {'alpha': 0.0013837955578346905, 'l1_ratio': 0.872895165486419}. Best is trial 82 with value: 0.014685065955771945.

72

[I 2026-10-08 19:49:34,434] Trial 23 finished with value: 0.20549910435388688 and parameters: {'alpha': 0.002188630512404353, 'l1_ratio': 0.1043427144104692}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,443] Trial 24 finished with value: 0.20554306223842322 and parameters: {'alpha': 1.2569072099854885, 'l1_ratio': 0.29695438599029167}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,452] Trial 25 finished with value: 0.20551177378306987 and parameters: {'alpha': 0.009643578180876607, 'l1_ratio': 0.18440099553721584}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,459] Trial 26 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.06271687296001291, 'l1_ratio': 0.04567705360840742}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,468] Trial 27 finished with value: 0.2055879151587492 and parameters: {'alpha': 0.0009578298716025098, 'l1_ratio': 0.09320865777853499}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,479] Trial 28 finished with value: 0.20565477112297334 and parameters: {'alpha': 2.1962229147243956e-05, 'l1_ratio': 0.5038728713865513}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,489] Trial 29 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.29537217231390456, 'l1_ratio': 0.17073760293146875}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,498] Trial 30 finished with value: 0.20554306223842322 and parameters: {'alpha': 1.154815678049269, 'l1_ratio': 0.27720038307877537}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,508] Trial 31 finished with value: 0.20545120557965113 and parameters: {'alpha': 0.014518207246134665, 'l1_ratio': 0.018734152033738703}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,518] Trial 32 finished with value: 0.20551563449877105 and parameters: {'alpha': 0.02507429588929509, 'l1_ratio': 0.07073182005455915}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,529] Trial 33 finished with value: 0.2054936517100328 and parameters: {'alpha': 0.006809561063388873, 'l1_ratio': 0.02907140678667636}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,538] Trial 34 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.09625337061198476, 'l1_ratio': 0.15931083661096473}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,547] Trial 35 finished with value: 0.20551659187765867 and parameters: {'alpha': 0.002608833764801591, 'l1_ratio': 0.07281382530559298}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,556] Trial 36 finished with value: 0.20554306223842322 and parameters: {'alpha': 4.691274125185337, 'l1_ratio': 0.007371039463291734}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,567] Trial 37 finished with value: 0.20555791442977805 and parameters: {'alpha': 0.0004221014215089784, 'l1_ratio': 0.34327723665075116}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,578] Trial 38 finished with value: 0.2056633054724325 and parameters: {'alpha': 1.0921663232796382e-06, 'l1_ratio': 0.197110266858266}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,588] Trial 39 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.02736045792279241, 'l1_ratio': 0.09777444319094927}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,597] Trial 40 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.5237574357047998, 'l1_ratio': 0.2886195222078177}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,610] Trial 41 finished with value: 0.20549039520453535 and parameters: {'alpha': 0.011046028958721223, 'l1_ratio': 0.015350486836289961}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,621] Trial 42 finished with value: 0.20546704273125907 and parameters: {'alpha': 0.004510620563111464, 'l1_ratio': 0.06188003053966666}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,632] Trial 43 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.022250434221583373, 'l1_ratio': 0.128479780191678}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,642] Trial 44 finished with value: 0.20558323197416234 and parameters: {'alpha': 0.0013312997051993774, 'l1_ratio': 0.06799700887628887}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,650] Trial 45 finished with value: 0.20549075403394346 and parameters: {'alpha': 0.08604987331068668, 'l1_ratio': 0.013200129495260657}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,660] Trial 46 finished with value: 0.2055815284736946 and parameters: {'alpha': 0.00044781306612631214, 'l1_ratio': 0.24017477507386437}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,669] Trial 47 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.023271027961644597, 'l1_ratio': 0.1453159325586696}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,677] Trial 48 finished with value: 0.20554306223842322 and parameters: {'alpha': 2.334352586097401, 'l1_ratio': 0.6304062132164721}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,686] Trial 49 finished with value: 0.20554126825974667 and parameters: {'alpha': 0.011088689289990959, 'l1_ratio': 0.2042250500461693}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,696] Trial 50 finished with value: 0.2056593615441191 and parameters: {'alpha': 8.132993957191786e-05, 'l1_ratio': 0.04463526956748684}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,705] Trial 51 finished with value: 0.20549705898581352 and parameters: {'alpha': 0.0030764832076640436, 'l1_ratio': 0.5054770294553889}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,717] Trial 52 finished with value: 0.20557700082750435 and parameters: {'alpha': 0.00015144812391304762, 'l1_ratio': 0.7876552560340746}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,726] Trial 53 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.04641042121447962, 'l1_ratio': 0.4051186796205836}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,735] Trial 54 finished with value: 0.2054518036002928 and parameters: {'alpha': 0.14963336880981848, 'l1_ratio': 0.003000298406579366}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,744] Trial 55 finished with value: 0.20554306223842322 and parameters: {'alpha': 13.61738565636895, 'l1_ratio': 0.10811946634786405}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,751] Trial 56 finished with value: 0.20546763892474235 and parameters: {'alpha': 0.1354971362080875, 'l1_ratio': 0.005210638317877793}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,760] Trial 57 finished with value: 0.20547616160818674 and parameters: {'alpha': 0.014356678643789344, 'l1_ratio': 0.08002744810151712}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,770] Trial 58 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.4793653439340497, 'l1_ratio': 0.04441045633902921}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,779] Trial 59 finished with value: 0.20544808367112005 and parameters: {'alpha': 0.006493438710233178, 'l1_ratio': 0.1348619221578864}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,788] Trial 60 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.045656719928848864, 'l1_ratio': 0.15935918577386796}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,799] Trial 61 finished with value: 0.20544367698814384 and parameters: {'alpha': 0.007084943133445901, 'l1_ratio': 0.11415082430472161}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,808] Trial 62 finished with value: 0.20543871287445564 and parameters: {'alpha': 0.004092144378177771, 'l1_ratio': 0.11258394167095866}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,818] Trial 63 finished with value: 0.20543791864712083 and parameters: {'alpha': 0.004522698462413261, 'l1_ratio': 0.13025336534280316}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,827] Trial 64 finished with value: 0.20547983125147673 and parameters: {'alpha': 0.004901383207664639, 'l1_ratio': 0.2449241802283676}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,838] Trial 65 finished with value: 0.20550903430192416 and parameters: {'alpha': 0.0017777839459969852, 'l1_ratio': 0.11991815279625577}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,849] Trial 66 finished with value: 0.20548726429073913 and parameters: {'alpha': 0.0014398086837307542, 'l1_ratio': 0.17953418554894204}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,861] Trial 67 finished with value: 0.20559913275081484 and parameters: {'alpha': 0.0005662149822131977, 'l1_ratio': 0.13933625047309642}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,870] Trial 68 finished with value: 0.20549323401343425 and parameters: {'alpha': 0.00627110891205782, 'l1_ratio': 0.22554618602186705}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,880] Trial 69 finished with value: 0.20547049914036206 and parameters: {'alpha': 0.0042213133585804925, 'l1_ratio': 0.26433246768742225}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,890] Trial 70 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.04571303307526427, 'l1_ratio': 0.10794070024476657}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,899] Trial 71 finished with value: 0.20559445025426132 and parameters: {'alpha': 0.0008915732240092203, 'l1_ratio': 0.09008322800585888}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,910] Trial 72 finished with value: 0.2054598449103804 and parameters: {'alpha': 0.018396062322461056, 'l1_ratio': 0.05335529226413532}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,922] Trial 73 finished with value: 0.20546746599308163 and parameters: {'alpha': 0.0063977625092140255, 'l1_ratio': 0.1691353548848776}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,932] Trial 74 finished with value: 0.20550825291556638 and parameters: {'alpha': 0.008568544570096313, 'l1_ratio': 0.2008781810235743}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,943] Trial 75 finished with value: 0.2055640290936247 and parameters: {'alpha': 0.0027875405509707627, 'l1_ratio': 0.036066428935594835}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,953] Trial 76 finished with value: 0.20552097338781342 and parameters: {'alpha': 0.015480479466330912, 'l1_ratio': 0.12380045282344457}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,964] Trial 77 finished with value: 0.2056473566456704 and parameters: {'alpha': 0.000212827283975451, 'l1_ratio': 0.0795486172205904}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,974] Trial 78 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.03646718034997703, 'l1_ratio': 0.15347389039116888}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,985] Trial 79 finished with value: 0.20559262509480206 and parameters: {'alpha': 0.0008892162056432478, 'l1_ratio': 0.09351562510423228}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:34,995] Trial 80 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.2762752868624356, 'l1_ratio': 0.062246202424228084}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,003] Trial 81 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.10410168342484191, 'l1_ratio': 0.02849306096558004}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,011] Trial 82 finished with value: 0.20544576895812486 and parameters: {'alpha': 0.06477077103033926, 'l1_ratio': 0.001708176014728946}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,020] Trial 83 finished with value: 0.2055232870412076 and parameters: {'alpha': 0.058608436422692145, 'l1_ratio': 0.030947597850535847}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,029] Trial 84 finished with value: 0.20543860296638022 and parameters: {'alpha': 0.0042236356316168655, 'l1_ratio': 0.12653143375148262}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,038] Trial 85 finished with value: 0.20543960439797146 and parameters: {'alpha': 0.0033385765826981803, 'l1_ratio': 0.1376950454434384}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,047] Trial 86 finished with value: 0.2054714531319464 and parameters: {'alpha': 0.003502932583878544, 'l1_ratio': 0.3214835534121385}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,056] Trial 87 finished with value: 0.20544828232112952 and parameters: {'alpha': 0.0019238514775013758, 'l1_ratio': 0.2053637002675845}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,064] Trial 88 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.02500056077711367, 'l1_ratio': 0.18077552749612685}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,073] Trial 89 finished with value: 0.2054729678554469 and parameters: {'alpha': 0.009636995069303381, 'l1_ratio': 0.11715313914391692}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,083] Trial 90 finished with value: 0.20561873714342996 and parameters: {'alpha': 0.0006839471387523217, 'l1_ratio': 0.06987031241859643}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,094] Trial 91 finished with value: 0.20544696843646562 and parameters: {'alpha': 0.00651565990709442, 'l1_ratio': 0.13202455506553856}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,105] Trial 92 finished with value: 0.20555681818952104 and parameters: {'alpha': 0.0013867326062590138, 'l1_ratio': 0.0958142714819698}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,115] Trial 93 finished with value: 0.2054400670269826 and parameters: {'alpha': 0.003323184035461892, 'l1_ratio': 0.14686273853783874}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,123] Trial 94 finished with value: 0.20546303588822484 and parameters: {'alpha': 0.00034095202538360716, 'l1_ratio': 0.9904701161591015}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,134] Trial 95 finished with value: 0.20545804727257586 and parameters: {'alpha': 0.0022087118655526234, 'l1_ratio': 0.1544495407757921}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,145] Trial 96 finished with value: 0.20543479413585364 and parameters: {'alpha': 0.012896605724596595, 'l1_ratio': 0.04645045929686942}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,156] Trial 97 finished with value: 0.20546668173930902 and parameters: {'alpha': 0.01922428923314689, 'l1_ratio': 0.05434809652098475}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,167] Trial 98 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.03181077796636144, 'l1_ratio': 0.0791063518244176}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,179] Trial 99 finished with value: 0.20552135450255152 and parameters: {'alpha': 0.003621613415807265, 'l1_ratio': 0.04681015844285332}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,191] Trial 100 finished with value: 0.20546374289273783 and parameters: {'alpha': 0.010459017530699213, 'l1_ratio': 0.023739979708813214}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,207] Trial 101 finished with value: 0.2056634717037804 and parameters: {'alpha': 1.5490459181421272e-07, 'l1_ratio': 0.11359516106858798}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,219] Trial 102 finished with value: 0.2054410913907813 and parameters: {'alpha': 0.08225940586538194, 'l1_ratio': 0.0022652797070881747}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,232] Trial 103 finished with value: 0.20549045629441706 and parameters: {'alpha': 0.07484784764892405, 'l1_ratio': 0.015450214634774653}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,243] Trial 104 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.15925339796158985, 'l1_ratio': 0.06936167498101606}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,252] Trial 105 finished with value: 0.20543555397537835 and parameters: {'alpha': 0.01476945406961823, 'l1_ratio': 0.043050053098849836}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,263] Trial 106 finished with value: 0.20543779695886127 and parameters: {'alpha': 0.004683927997439285, 'l1_ratio': 0.0949819362833656}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,273] Trial 107 finished with value: 0.20550976249543332 and parameters: {'alpha': 0.004503374481853063, 'l1_ratio': 0.040825538943562445}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,283] Trial 108 finished with value: 0.20549122940328812 and parameters: {'alpha': 0.014879797117684179, 'l1_ratio': 0.08975187647687355}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,292] Trial 109 finished with value: 0.20553571350139463 and parameters: {'alpha': 0.0012231174953735034, 'l1_ratio': 0.1398841621528472}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,302] Trial 110 finished with value: 0.20545401442130182 and parameters: {'alpha': 0.0021307426877484083, 'l1_ratio': 0.17010700518934513}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,312] Trial 111 finished with value: 0.20543846868471716 and parameters: {'alpha': 0.0063403340397517076, 'l1_ratio': 0.10823883276689988}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,321] Trial 112 finished with value: 0.2054813499068788 and parameters: {'alpha': 0.0041685465177889545, 'l1_ratio': 0.05963745043725175}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,330] Trial 113 finished with value: 0.2055414531802793 and parameters: {'alpha': 0.011960534197846769, 'l1_ratio': 0.18955965679823988}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,340] Trial 114 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.033365277610455164, 'l1_ratio': 0.09797480716988158}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,349] Trial 115 finished with value: 0.20557101859036128 and parameters: {'alpha': 0.002912476981354821, 'l1_ratio': 0.029696484076598598}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,360] Trial 116 finished with value: 0.20554306223842322 and parameters: {'alpha': 0.020018321435220622, 'l1_ratio': 0.15575560358574997}. Best is trial 11 with value: 0.2054330562824627.
[I 2026-10-08 19:49:35,370] Trial 117 finished with value: 0.20543734194497024 and parameters: {'alpha': 0.0057380690541595746, 'l1_ratio': 0.08358146372499002}. Best is trial 11 with value: 0.2054330562824627.

In [102]:
results_df

            date  stock_id  R1M_Usd    y_pred  Lag1_R1M_Usd     Error
0     2012-11-30        24    0.048  0.014893         0.052 -0.033107
1     2012-11-30        34    0.114  0.014893         0.174 -0.099107
2     2012-11-30        41   -0.018  0.014893         0.001  0.032893
3     2012-11-30        45   -0.012  0.014893        -0.014  0.026893
4     2012-11-30        47    0.007  0.014893        -0.005  0.007893
...          ...       ...      ...       ...           ...       ...
11687 2018-12-31      1168    0.105  0.011827        -0.152 -0.093173
11688 2018-12-31      1186    0.080  0.024676        -0.172 -0.055324
11689 2018-12-31      1189   -0.103  0.008828        -0.394  0.111828
11690 2018-12-31      1195    0.157  0.005738        -0.180 -0.151262
11691 2018-12-31      1212    0.222  0.004330        -0.125 -0.217670

[11692 rows x 6 columns]

In [103]:
hyperparameters_df

         date     alpha  l1_ratio  validation_mse
0  2012-11-30  1.719901  0.407379        0.011728
1  2013-05-31  0.007971  0.266929        0.010583
2  2013-11-30  0.003271  0.682060        0.010761
3  2014-05-31  0.002824  0.572148        0.007903
4  2014-11-30  0.003044  0.487749        0.007980
5  2015-05-31  0.004254  0.337541        0.007613
6  2015-11-30  0.003787  0.503768        0.011038
7  2016-05-31  0.002045  0.922799        0.012344
8  2016-11-30  0.002459  0.248734        0.013512
9  2017-05-31  0.001180  0.436726        0.013497
10 2017-11-30  0.076676  0.002253        0.016580
11 2018-05-31  0.000638  0.877506        0.014685
12 2018-11-30  0.016030  0.028796        0.205430

In [101]:
# Include random walk benchmark
# Random walk benchmark
results_df = results_df.merge(data_ml_selected_lags[['date', 'stock_id', 'Lag1_R1M_Usd']], on=['date', 'stock_id'], how='left')
results_df['Error'] = results_df['y_pred'] - results_df['R1M_Usd']
results_df

            date  stock_id  R1M_Usd    y_pred  Lag1_R1M_Usd     Error
0     2012-11-30        24    0.048  0.014893         0.052 -0.033107
1     2012-11-30        34    0.114  0.014893         0.174 -0.099107
2     2012-11-30        41   -0.018  0.014893         0.001  0.032893
3     2012-11-30        45   -0.012  0.014893        -0.014  0.026893
4     2012-11-30        47    0.007  0.014893        -0.005  0.007893
...          ...       ...      ...       ...           ...       ...
11687 2018-12-31      1168    0.105  0.011827        -0.152 -0.093173
11688 2018-12-31      1186    0.080  0.024676        -0.172 -0.055324
11689 2018-12-31      1189   -0.103  0.008828        -0.394  0.111828
11690 2018-12-31      1195    0.157  0.005738        -0.180 -0.151262
11691 2018-12-31      1212    0.222  0.004330        -0.125 -0.217670

[11692 rows x 6 columns]

In [104]:
print(f'EN model:{mean_squared_error(results_df['y_pred'], results_df['R1M_Usd'])}')
print(f'RW model:{mean_squared_error(results_df['Lag1_R1M_Usd'], results_df['R1M_Usd'])}')

EN model:0.09098462189350821
RW model:0.1821770829627095