### My implementation of penalized regressions
In this notebook, I provide improvements and extensions to the original implementation of penalized regressions presented in the book. These include:
* Bayesian optimization of hyperparameters using optuna.
* Walk-forward optimization.
* Additional Feature Engineering: including lags of dependent variable.

For training time purposes, I reduce the number of features (use features_short) and use only 20% of the stock_ids_short list. Training is performed with ElasticNet only.

I do not provide code on sparse portfolio optimization in this notebook.

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
np.random.seed(123)
os.chdir('C:\\Users\\ferna\\OneDrive\\Downloads\\Code\\Python\\ML_Factor')

### 1) Data

In [25]:
from data.data_load import *

In [26]:
# Selection of 20% of stock_ids_short (Careful in real application, has survivorship bias. I use only for simplification).
stock_ids_selected = random.sample(stock_ids_short, k=int(0.2 * len(stock_ids_short)))
len(stock_ids_selected)

158

In [27]:
# Filtering for stock_ids_selected and features_short
data_ml_selected = data_ml.loc[data_ml['stock_id'].isin(stock_ids_selected), ['date', 'stock_id','R1M_Usd'] + features_short]
data_ml_selected = data_ml_selected.sort_values(by=['date', 'stock_id'], ascending=True)
data_ml_selected.index = range(data_ml_selected.shape[0])

print(data_ml_selected.shape[0], data_ml_selected.shape[1])
data_ml_selected.head()

36024 10

,date,stock_id,R1M_Usd,Div_Yld,Eps,Mkt_Cap_12M_Usd,Mom_11M_Usd,Ocf,Pb,Vol1Y_Usd
0,2000-01-31,3,0.077,0.67,0.36,0.11,0.54,0.21,0.19,0.22
1,2000-01-31,9,0.032,0.54,0.33,0.11,0.18,0.18,0.34,0.04
2,2000-01-31,24,0.222,0.12,0.32,0.29,0.50,0.20,0.66,0.68
3,2000-01-31,32,-0.142,0.07,0.23,0.40,0.33,0.05,0.32,0.25
4,2000-01-31,46,-0.008,0.46,0.30,0.72,0.75,0.74,0.37,0.53

In [28]:
# Adding lags of dependent variable - may introduce endogeneity if the errors are serially correlated.
# Add 4 lags
data_ml_selected_lags = data_ml_selected.copy()
nlags = 4
for ll in range(1,nlags+1):
    data_ml_selected_lags[f'Lag{ll}_R1M_Usd'] = data_ml_selected.groupby('stock_id')['R1M_Usd'].shift(ll)

In [29]:
# REMOVE NAN
data_ml_selected_lags = data_ml_selected_lags.dropna()

In [30]:
data_ml_selected_lags.iloc[[0,1,2,-2,-1],:]

,date,stock_id,R1M_Usd,Div_Yld,Eps,Mkt_Cap_12M_Usd,Mom_11M_Usd,Ocf,Pb,Vol1Y_Usd,Lag1_R1M_Usd,Lag2_R1M_Usd,Lag3_R1M_Usd,Lag4_R1M_Usd
632,2000-05-31,3,0.050,0.69,0.50,0.10,0.48,0.18,0.18,0.24,0.027,0.018,-0.024,0.077
633,2000-05-31,9,-0.121,0.56,0.36,0.10,0.36,0.06,0.28,0.09,-0.022,-0.025,0.076,0.032
634,2000-05-31,24,0.083,0.21,0.36,0.31,0.87,0.36,0.65,0.76,-0.070,0.098,-0.026,0.222
36022,2018-12-31,1203,0.061,0.34,0.45,0.57,0.88,0.41,0.72,0.11,-0.079,-0.005,-0.030,0.037
36023,2018-12-31,1212,0.222,0.13,0.99,0.72,0.09,0.87,0.73,0.88,-0.125,0.013,-0.266,0.044

### 2) Elastic Net training

In [31]:
import optuna
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import ElasticNet

In [32]:
# Functions for walk-forward optimization.

def prepare_data(data_ml_selected_lags, features, y_name , train_tuple, val_tuple, test_tuple):

    """
    Split panel data into training, validation, and test sets by date.
    Returns (X, y) pairs as arrays for each period.
    """
    
    idx_train = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= train_tuple[0]) & 
        (data_ml_selected_lags['date'] < train_tuple[1])
    ]

    idx_val  = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= val_tuple[0]) & 
        (data_ml_selected_lags['date'] < val_tuple[1])
    ]

    idx_test  = data_ml_selected_lags['date'].index[
        (data_ml_selected_lags['date'] >= test_tuple[0]) & 
        (data_ml_selected_lags['date'] <= test_tuple[1])
    ]

    X_train = data_ml_selected_lags.loc[idx_train,:][features].values
    X_val   = data_ml_selected_lags.loc[idx_val,:][features].values
    X_test  = data_ml_selected_lags.loc[idx_test,:][features].values

    y_train = data_ml_selected_lags.loc[idx_train,:][y_name].values
    y_val   = data_ml_selected_lags.loc[idx_val,:][y_name].values
    y_test  = data_ml_selected_lags.loc[idx_test,:][y_name].values

    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

def optimize_hyperparameters(X_train, y_train, X_val, y_val, n_trials=200):

    def objective(trial):

        alpha = trial.suggest_float("alpha", 1e-10, 1e2, log=True)
        l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)

        model = ElasticNet(
            alpha=alpha,
            l1_ratio=l1_ratio,
            max_iter=10000
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_val)

        return mean_squared_error(y_val, y_pred)

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials)

    return study

In [38]:
dates = data_ml_selected_lags['date'].sort_values().unique()

init_train = 120    # initial training window: 120 
init_val = 150      # end of the initial validation window
retrain_step = 6    # retrain every 6 obs

features = data_ml_selected_lags.columns.drop(['date', 'stock_id', 'R1M_Usd'])
y_name = 'R1M_Usd'

results = []
hyperparameters = []

for i in range(0, len(dates) - init_val, retrain_step):

    print(i)

    # Preparando dados
    
    train_tuple = (dates[i], dates[i + init_train])
    val_tuple   = (dates[i + init_train], dates[i + init_val])

    test_end   = min(i + init_val + retrain_step, len(dates))
    test_tuple = (dates[i + init_val], dates[test_end - 1])

    train, val, test = prepare_data(
        data_ml_selected_lags, features, y_name,
        train_tuple, val_tuple, test_tuple
    )

    
    # Hyperparameter optimization

    study = optimize_hyperparameters(train[0], train[1], val[0], val[1], n_trials=250)
    
    best_alpha    = study.best_params["alpha"]
    best_l1_ratio = study.best_params["l1_ratio"]

    # Model: fit on train+val, test on test.
    
    X_fit = np.concatenate([train[0], val[0]], axis=0)
    y_fit = np.concatenate([train[1], val[1]], axis=0)

    model = ElasticNet(**study.best_params, max_iter=10000)
    model.fit(X_fit, y_fit)
    print(model.coef_)

    # OOS
    y_pred = model.predict(test[0])
    
    test_dates = dates[i + init_val : i + init_val + retrain_step]

    test_df = data_ml_selected_lags.loc[
        data_ml_selected_lags['date'].isin(test_dates),
        ['date', 'stock_id', y_name]
    ].copy()

    test_df['y_pred'] = y_pred
    results.append(test_df)

    # Store hyperparameters
    hyperparameters.append({
        'date': test_dates[0],
        **study.best_params,
        'validation_mse': study.best_value
    })

# Combine results
results_df = pd.concat(results, ignore_index=True)
hyperparameters_df = pd.DataFrame(hyperparameters)

[I 2026-10-14 15:41:54,440] A new study created in memory with name: no-name-3dd46312-174e-4d3b-919c-a1786cc58b82
[I 2026-10-14 15:41:54,446] Trial 0 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.7255747754914083, 'l1_ratio': 0.35485898180605846}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,456] Trial 1 finished with value: 0.029827166889333703 and parameters: {'alpha': 6.158601454338207e-10, 'l1_ratio': 0.9604477027439345}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,467] Trial 2 finished with value: 0.029827154293959202 and parameters: {'alpha': 3.693769732619156e-08, 'l1_ratio': 0.46250187087614225}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,472] Trial 3 finished with value: 0.029045458883350354 and parameters: {'alpha': 8.453919909364403, 'l1_ratio': 0.05397890820877915}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,478] Trial 4 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.34016441843369355, 'l1_ratio': 0.3764741047146102}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,485] Trial 5 finished with value: 0.029526216924068746 and parameters: {'alpha': 0.0011061660010316542, 'l1_ratio': 0.4105816429965984}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,494] Trial 6 finished with value: 0.02982715607185489 and parameters: {'alpha': 1.7037565291195435e-08, 'l1_ratio': 0.9074847804480588}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,503] Trial 7 finished with value: 0.029827166872333097 and parameters: {'alpha': 4.022655133640706e-09, 'l1_ratio': 0.1127066057643924}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,510] Trial 8 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.08008519866827056, 'l1_ratio': 0.8779748566775563}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,519] Trial 9 finished with value: 0.029827166860381445 and parameters: {'alpha': 2.0799983763210605e-09, 'l1_ratio': 0.27089381110407074}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,529] Trial 10 finished with value: 0.0298212618197227 and parameters: {'alpha': 1.2463880629492103e-05, 'l1_ratio': 0.6402185481640009}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,538] Trial 11 finished with value: 0.029045458883350354 and parameters: {'alpha': 33.42695349499688, 'l1_ratio': 0.01135920503543885}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,545] Trial 12 finished with value: 0.029045458883350354 and parameters: {'alpha': 63.603540318868944, 'l1_ratio': 0.19724715165559098}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,554] Trial 13 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.22335296475357627, 'l1_ratio': 0.6147332027558021}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,562] Trial 14 finished with value: 0.02952748794636202 and parameters: {'alpha': 0.0069115218358979345, 'l1_ratio': 0.03625048408805681}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,569] Trial 15 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.402800800959164, 'l1_ratio': 0.2394530284261623}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,578] Trial 16 finished with value: 0.029738828150225726 and parameters: {'alpha': 0.00021212551446313436, 'l1_ratio': 0.586729197380053}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,585] Trial 17 finished with value: 0.029045458883350354 and parameters: {'alpha': 5.9799434144421735, 'l1_ratio': 0.769712320804609}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,596] Trial 18 finished with value: 0.029825921046961346 and parameters: {'alpha': 4.832180140449671e-06, 'l1_ratio': 0.3257307460353676}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,605] Trial 19 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.027810391236048254, 'l1_ratio': 0.11651670274487544}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,613] Trial 20 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.033713932821229, 'l1_ratio': 0.5050211222621116}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,622] Trial 21 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.33271361955107887, 'l1_ratio': 0.4146874237994234}. Best is trial 0 with value: 0.029045458883350354.

0

[I 2026-10-14 15:41:54,630] Trial 22 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.9766478728027171, 'l1_ratio': 0.3388923932405664}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,639] Trial 23 finished with value: 0.02912294842778903 and parameters: {'alpha': 0.009143807968610371, 'l1_ratio': 0.16519316254250713}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,648] Trial 24 finished with value: 0.029045458883350354 and parameters: {'alpha': 10.592937980200164, 'l1_ratio': 0.7152863460733012}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,656] Trial 25 finished with value: 0.029593866932470663 and parameters: {'alpha': 0.0010644494256964886, 'l1_ratio': 0.31006025853492847}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,664] Trial 26 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.13054895529792418, 'l1_ratio': 0.4775471940720012}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,672] Trial 27 finished with value: 0.029045458883350354 and parameters: {'alpha': 99.81747981221514, 'l1_ratio': 0.14023576702546775}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,680] Trial 28 finished with value: 0.029045458883350354 and parameters: {'alpha': 9.226478023103368, 'l1_ratio': 0.3836162053537208}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,687] Trial 29 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.48033421082557687, 'l1_ratio': 0.5381594105577888}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,696] Trial 30 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.01724968241054543, 'l1_ratio': 0.21858150617613445}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,703] Trial 31 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.24443050375125272, 'l1_ratio': 0.9999206840638422}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,711] Trial 32 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.05504857156800803, 'l1_ratio': 0.8773360563089849}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,718] Trial 33 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.0038189451652790073, 'l1_ratio': 0.7794281548890524}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,725] Trial 34 finished with value: 0.029764706360832668 and parameters: {'alpha': 0.00012771416559080142, 'l1_ratio': 0.6869209739944309}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,733] Trial 35 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.6934693150575797, 'l1_ratio': 0.0615818920244279}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,741] Trial 36 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.09347095882619999, 'l1_ratio': 0.9070408303406116}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,748] Trial 37 finished with value: 0.029045458883350354 and parameters: {'alpha': 16.619965138932702, 'l1_ratio': 0.8387626031740636}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,756] Trial 38 finished with value: 0.029448374214924893 and parameters: {'alpha': 0.0013634890948749732, 'l1_ratio': 0.44071499928788377}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,765] Trial 39 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.042708144947264624, 'l1_ratio': 0.5598855497317969}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,773] Trial 40 finished with value: 0.029045458883350354 and parameters: {'alpha': 5.596339155616884, 'l1_ratio': 0.26975504712094533}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,781] Trial 41 finished with value: 0.029045458883350354 and parameters: {'alpha': 22.19757983021356, 'l1_ratio': 0.007491728227353102}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,789] Trial 42 finished with value: 0.029045458883350354 and parameters: {'alpha': 85.62366432496994, 'l1_ratio': 0.059946024666427726}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,802] Trial 43 finished with value: 0.029827133624568878 and parameters: {'alpha': 4.1038592239050113e-07, 'l1_ratio': 0.07104916341943313}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,810] Trial 44 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.9152243464523709, 'l1_ratio': 0.00387314349254735}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,818] Trial 45 finished with value: 0.029045458883350354 and parameters: {'alpha': 30.394579960158914, 'l1_ratio': 0.15670365020890187}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,826] Trial 46 finished with value: 0.029045458883350354 and parameters: {'alpha': 4.086641818676507, 'l1_ratio': 0.08879361875821665}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,833] Trial 47 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.5601648241693974, 'l1_ratio': 0.18059527832896952}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,841] Trial 48 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.320179590719098, 'l1_ratio': 0.6550003113934941}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,849] Trial 49 finished with value: 0.029045458883350354 and parameters: {'alpha': 38.559374821572526, 'l1_ratio': 0.25281167882961864}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,856] Trial 50 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.1485466529326088, 'l1_ratio': 0.3682496541365393}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,865] Trial 51 finished with value: 0.029045458883350354 and parameters: {'alpha': 29.438098843946985, 'l1_ratio': 0.10277525423080877}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,872] Trial 52 finished with value: 0.029045458883350354 and parameters: {'alpha': 6.761795993538603, 'l1_ratio': 0.20264027277706823}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,879] Trial 53 finished with value: 0.029045458883350354 and parameters: {'alpha': 95.21343009395513, 'l1_ratio': 0.3017495052580258}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,887] Trial 54 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.744483513732998, 'l1_ratio': 0.13441455520879844}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,897] Trial 55 finished with value: 0.02982716726830452 and parameters: {'alpha': 8.91804573014844e-10, 'l1_ratio': 0.033543937445085624}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,905] Trial 56 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.228355480365379, 'l1_ratio': 0.22378169605476494}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,914] Trial 57 finished with value: 0.029045458883350354 and parameters: {'alpha': 13.115685405383065, 'l1_ratio': 0.5048717591482674}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,922] Trial 58 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.015416862365543967, 'l1_ratio': 0.29353221570816856}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,929] Trial 59 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.371296551442487, 'l1_ratio': 0.18403546728553508}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,936] Trial 60 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.06313640577086908, 'l1_ratio': 0.3549962907200023}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,944] Trial 61 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.18971177543690015, 'l1_ratio': 0.8142222566177715}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,953] Trial 62 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.003951249965908844, 'l1_ratio': 0.7222064052730887}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,964] Trial 63 finished with value: 0.02982716723105288 and parameters: {'alpha': 1.9750432940628493e-10, 'l1_ratio': 0.5923250569672933}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,972] Trial 64 finished with value: 0.029045458883350354 and parameters: {'alpha': 3.123775585753887, 'l1_ratio': 0.44135378381557466}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,980] Trial 65 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.208783724586994, 'l1_ratio': 0.9541178311913918}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,987] Trial 66 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.026025966965567374, 'l1_ratio': 0.4150445779810922}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:54,996] Trial 67 finished with value: 0.029045458883350354 and parameters: {'alpha': 52.68167422870124, 'l1_ratio': 0.6293154790655775}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,003] Trial 68 finished with value: 0.029045458883350354 and parameters: {'alpha': 10.734383778236312, 'l1_ratio': 0.04010600762009428}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,011] Trial 69 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.21628326704787323, 'l1_ratio': 0.1258235747040261}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,019] Trial 70 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.007418347379441279, 'l1_ratio': 0.38691201994716073}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,027] Trial 71 finished with value: 0.029045458883350354 and parameters: {'alpha': 3.321709877751073, 'l1_ratio': 0.24494762896548644}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,035] Trial 72 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.534752965997846, 'l1_ratio': 0.4765443442514999}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,043] Trial 73 finished with value: 0.029045458883350354 and parameters: {'alpha': 9.867476189863291, 'l1_ratio': 0.34019471277838514}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,051] Trial 74 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.08556703408073738, 'l1_ratio': 0.3155115050539735}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,059] Trial 75 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.9629755318913235, 'l1_ratio': 0.7348310605877014}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,067] Trial 76 finished with value: 0.029045458883350354 and parameters: {'alpha': 5.564411558415818, 'l1_ratio': 0.22044733293257326}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,076] Trial 77 finished with value: 0.029045458883350354 and parameters: {'alpha': 20.46203591217304, 'l1_ratio': 0.09297828776500469}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,083] Trial 78 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.4966468175511094, 'l1_ratio': 0.5232105969797392}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,091] Trial 79 finished with value: 0.029045458883350354 and parameters: {'alpha': 56.37108887446975, 'l1_ratio': 0.15651985894088405}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,099] Trial 80 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.33554134855289547, 'l1_ratio': 0.2863169321267087}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,107] Trial 81 finished with value: 0.029045458883350354 and parameters: {'alpha': 7.319927986580652, 'l1_ratio': 0.7727327631844452}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,115] Trial 82 finished with value: 0.029045458883350354 and parameters: {'alpha': 18.37915362680552, 'l1_ratio': 0.8561314074132491}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,127] Trial 83 finished with value: 0.02982715871740421 and parameters: {'alpha': 1.4760130068454577e-08, 'l1_ratio': 0.7955087736536615}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,136] Trial 84 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.04354209825523265, 'l1_ratio': 0.8978626679960962}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,145] Trial 85 finished with value: 0.029045458883350354 and parameters: {'alpha': 3.6700744507727237, 'l1_ratio': 0.9453203785560409}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,153] Trial 86 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.4620889054907014, 'l1_ratio': 0.6857700427151175}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,162] Trial 87 finished with value: 0.029045458883350354 and parameters: {'alpha': 36.27785680358344, 'l1_ratio': 0.9323915990885512}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,170] Trial 88 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.132161761730955, 'l1_ratio': 0.07003265168104703}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,180] Trial 89 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.5115993592324772, 'l1_ratio': 0.0051547603823659735}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,190] Trial 90 finished with value: 0.029823025182524623 and parameters: {'alpha': 1.950250125119053e-05, 'l1_ratio': 0.26036784232050064}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,200] Trial 91 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.02869355982190464, 'l1_ratio': 0.10664588586395307}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,209] Trial 92 finished with value: 0.02979243300355133 and parameters: {'alpha': 0.0005758033206794573, 'l1_ratio': 0.04219310385926364}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,216] Trial 93 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.015565720358701005, 'l1_ratio': 0.19604051377073697}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,224] Trial 94 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.10588253836500965, 'l1_ratio': 0.15050634714572503}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,232] Trial 95 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.2903936193625672, 'l1_ratio': 0.025945274829893332}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,241] Trial 96 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.057270773939982, 'l1_ratio': 0.12228998903931182}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,250] Trial 97 finished with value: 0.029045458883350354 and parameters: {'alpha': 14.99780251813836, 'l1_ratio': 0.0717002818610013}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,261] Trial 98 finished with value: 0.029649789027981755 and parameters: {'alpha': 0.0022619894017428623, 'l1_ratio': 0.08132071403035979}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,271] Trial 99 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.7143215662045325, 'l1_ratio': 0.17282833807317402}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,280] Trial 100 finished with value: 0.029045458883350354 and parameters: {'alpha': 65.05653534916289, 'l1_ratio': 0.8688227927884183}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,291] Trial 101 finished with value: 0.029045458883350354 and parameters: {'alpha': 6.573210111891464, 'l1_ratio': 0.6080767233481068}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,298] Trial 102 finished with value: 0.029045458883350354 and parameters: {'alpha': 3.9431416594676594, 'l1_ratio': 0.4333397623650037}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,307] Trial 103 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.05816582290033104, 'l1_ratio': 0.5623791943881153}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,316] Trial 104 finished with value: 0.029045458883350354 and parameters: {'alpha': 29.929473708013543, 'l1_ratio': 0.75378745928265}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,323] Trial 105 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.192604344195858, 'l1_ratio': 0.9951447623031106}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,331] Trial 106 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.0841254415346042, 'l1_ratio': 0.49218130479665145}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,338] Trial 107 finished with value: 0.029045458883350354 and parameters: {'alpha': 2.334237844418064, 'l1_ratio': 0.38844563708520835}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,347] Trial 108 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.024269187449600906, 'l1_ratio': 0.8217282363235525}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,355] Trial 109 finished with value: 0.029045458883350354 and parameters: {'alpha': 9.637963076606534, 'l1_ratio': 0.6742568500435119}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,362] Trial 110 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.01086060083114806, 'l1_ratio': 0.23362394122328056}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,370] Trial 111 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.3945573596359009, 'l1_ratio': 0.45523184190221094}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,378] Trial 112 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.08467149526970022, 'l1_ratio': 0.40405721640985354}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,386] Trial 113 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.2513392649732795, 'l1_ratio': 0.32232921421683774}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,394] Trial 114 finished with value: 0.029045458883350354 and parameters: {'alpha': 0.8640606355668562, 'l1_ratio': 0.3589144681295031}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,402] Trial 115 finished with value: 0.029045458883350354 and parameters: {'alpha': 4.616595835236285, 'l1_ratio': 0.27632237809099147}. Best is trial 0 with value: 0.029045458883350354.
[I 2026-10-14 15:41:55,411] Trial 116 finished with value: 0.029045458883350354 and parameters: {'alpha': 1.6518428158123073, 'l1_ratio': 0.46793779824820225}. Best is trial 0 with value: 0.029045458883350354.

[ 0. -0. -0. -0. -0. -0.  0.  0. -0.  0.  0.]
6

[I 2026-10-14 15:41:56,890] Trial 27 finished with value: 0.026335873383016847 and parameters: {'alpha': 9.189749503045634e-07, 'l1_ratio': 0.9166779015218286}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,897] Trial 28 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0093818166903751, 'l1_ratio': 0.5147244193400035}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,905] Trial 29 finished with value: 0.02622386281359182 and parameters: {'alpha': 0.00024199970691016749, 'l1_ratio': 0.8574325001494585}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,915] Trial 30 finished with value: 0.0263363758998619 and parameters: {'alpha': 1.3668260151129286e-10, 'l1_ratio': 0.6751205166222268}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,922] Trial 31 finished with value: 0.025800353936334983 and parameters: {'alpha': 6.3659246741015965, 'l1_ratio': 0.9950380077274992}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,930] Trial 32 finished with value: 0.025800353936334983 and parameters: {'alpha': 20.805468584845954, 'l1_ratio': 0.9274809598371787}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,941] Trial 33 finished with value: 0.025800353936334983 and parameters: {'alpha': 89.40304832715536, 'l1_ratio': 0.7782796899416466}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,949] Trial 34 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.08051306839942036, 'l1_ratio': 0.8345312816044761}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,958] Trial 35 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.6624973364375074, 'l1_ratio': 0.9361212240147408}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,966] Trial 36 finished with value: 0.025800353936334983 and parameters: {'alpha': 21.95949652471513, 'l1_ratio': 0.8840372387198389}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,977] Trial 37 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0038219790905150404, 'l1_ratio': 0.9693689807721576}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,986] Trial 38 finished with value: 0.02633635822818691 and parameters: {'alpha': 5.415508392971564e-08, 'l1_ratio': 0.5309350768386514}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:56,995] Trial 39 finished with value: 0.025800353936334983 and parameters: {'alpha': 1.4086939562002856, 'l1_ratio': 0.28414558998523953}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,004] Trial 40 finished with value: 0.02619132986426596 and parameters: {'alpha': 0.0003328745656910564, 'l1_ratio': 0.8207334454988551}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,012] Trial 41 finished with value: 0.025800353936334983 and parameters: {'alpha': 5.023554482016711, 'l1_ratio': 0.7487903342529515}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,020] Trial 42 finished with value: 0.025800353936334983 and parameters: {'alpha': 23.61164768710577, 'l1_ratio': 0.8583391430553188}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,029] Trial 43 finished with value: 0.025800353936334983 and parameters: {'alpha': 3.1016410971221147, 'l1_ratio': 0.6466528197302307}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,036] Trial 44 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.23076816874612927, 'l1_ratio': 0.8037329120490955}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,045] Trial 45 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0409616477849701, 'l1_ratio': 0.9460035746571114}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,053] Trial 46 finished with value: 0.025800353936334983 and parameters: {'alpha': 68.21384295551347, 'l1_ratio': 0.8876577490717416}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,062] Trial 47 finished with value: 0.026323137845010638 and parameters: {'alpha': 3.697763543555462e-05, 'l1_ratio': 0.5916544260557239}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,069] Trial 48 finished with value: 0.026041906619467835 and parameters: {'alpha': 0.0008307522893258364, 'l1_ratio': 0.7379590380933302}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,077] Trial 49 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.8231901681429876, 'l1_ratio': 0.6829393294642262}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,086] Trial 50 finished with value: 0.02633232316764294 and parameters: {'alpha': 7.101687104042781e-06, 'l1_ratio': 0.9613253651407232}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,096] Trial 51 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.2216542907995882, 'l1_ratio': 0.7670480224041036}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,104] Trial 52 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.036572785951336076, 'l1_ratio': 0.8186392641799995}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,112] Trial 53 finished with value: 0.025800353936334983 and parameters: {'alpha': 9.616250330951905, 'l1_ratio': 0.8534084246858811}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,123] Trial 54 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.014906681310795231, 'l1_ratio': 0.8792518138127505}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,131] Trial 55 finished with value: 0.025800353936334983 and parameters: {'alpha': 2.1126125708526473, 'l1_ratio': 0.6341093394447037}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,141] Trial 56 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.10883490165645146, 'l1_ratio': 0.7135723844878661}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,150] Trial 57 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.43041451947160786, 'l1_ratio': 0.26758938139968746}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,158] Trial 58 finished with value: 0.025799233556839066 and parameters: {'alpha': 0.0038089802337396344, 'l1_ratio': 0.5568981470994523}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,167] Trial 59 finished with value: 0.02580766049084993 and parameters: {'alpha': 0.005178888503380489, 'l1_ratio': 0.336951080353838}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,175] Trial 60 finished with value: 0.02598775702183 and parameters: {'alpha': 0.0013939678791029325, 'l1_ratio': 0.5418484608506079}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,184] Trial 61 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.015670048279836046, 'l1_ratio': 0.4454067614728214}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,193] Trial 62 finished with value: 0.026298176403764733 and parameters: {'alpha': 0.00013391091232302637, 'l1_ratio': 0.47389690926199374}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,202] Trial 63 finished with value: 0.025800353936334983 and parameters: {'alpha': 18.325142000820662, 'l1_ratio': 0.897073751508725}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,210] Trial 64 finished with value: 0.02582562775176674 and parameters: {'alpha': 0.0684491218538511, 'l1_ratio': 0.014651310636774328}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,218] Trial 65 finished with value: 0.02616187098741151 and parameters: {'alpha': 0.0005817952216011508, 'l1_ratio': 0.5672864465906563}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,226] Trial 66 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0034128071902351943, 'l1_ratio': 0.6752609116188916}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,233] Trial 67 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.18210800356628312, 'l1_ratio': 0.9981243262366676}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,241] Trial 68 finished with value: 0.025800353936334983 and parameters: {'alpha': 3.2963896268274366, 'l1_ratio': 0.7808009739859982}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,249] Trial 69 finished with value: 0.025800353936334983 and parameters: {'alpha': 36.11874635255593, 'l1_ratio': 0.9192492285906817}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,257] Trial 70 finished with value: 0.025800353936334983 and parameters: {'alpha': 11.594433899629626, 'l1_ratio': 0.8451822155553776}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,265] Trial 71 finished with value: 0.025800353936334983 and parameters: {'alpha': 1.2683969578684289, 'l1_ratio': 0.9532283264012639}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,275] Trial 72 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.031119245704153236, 'l1_ratio': 0.9803234847785838}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,283] Trial 73 finished with value: 0.026212447627864146 and parameters: {'alpha': 0.0012697106688732789, 'l1_ratio': 0.1508536238910898}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,291] Trial 74 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0054858695602717535, 'l1_ratio': 0.932518214703504}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,299] Trial 75 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.5136358614433526, 'l1_ratio': 0.900295414901743}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,307] Trial 76 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.009911319764977132, 'l1_ratio': 0.7530489564340579}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,316] Trial 77 finished with value: 0.025807438013889943 and parameters: {'alpha': 0.002165517231986793, 'l1_ratio': 0.8141154739965761}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,324] Trial 78 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.029520356074590866, 'l1_ratio': 0.9660575291039153}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,333] Trial 79 finished with value: 0.025800353936334983 and parameters: {'alpha': 5.665051658392512, 'l1_ratio': 0.8664868643692338}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,341] Trial 80 finished with value: 0.025800353936334983 and parameters: {'alpha': 40.14237147210057, 'l1_ratio': 0.7976326195413701}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,349] Trial 81 finished with value: 0.025800353936334983 and parameters: {'alpha': 44.36290587080094, 'l1_ratio': 0.7150468415424245}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,358] Trial 82 finished with value: 0.025800353936334983 and parameters: {'alpha': 14.472266237532336, 'l1_ratio': 0.6089404093107162}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,368] Trial 83 finished with value: 0.025800353936334983 and parameters: {'alpha': 2.0229888380444203, 'l1_ratio': 0.7303086538720687}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,377] Trial 84 finished with value: 0.025800353936334983 and parameters: {'alpha': 68.4789346100376, 'l1_ratio': 0.833710158211956}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,385] Trial 85 finished with value: 0.025800353936334983 and parameters: {'alpha': 4.748559344768908, 'l1_ratio': 0.6914498704634835}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,393] Trial 86 finished with value: 0.025800353936334983 and parameters: {'alpha': 99.25596616999091, 'l1_ratio': 0.661167889003583}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,405] Trial 87 finished with value: 0.026336375904836444 and parameters: {'alpha': 1.0762097803097848e-10, 'l1_ratio': 0.7880756743400652}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,413] Trial 88 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.06593848132841033, 'l1_ratio': 0.933395423776594}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,421] Trial 89 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.1510807947558979, 'l1_ratio': 0.9096686690002168}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,427] Trial 90 finished with value: 0.02603685814499567 and parameters: {'alpha': 0.0006326717109687706, 'l1_ratio': 0.9992872819804337}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,435] Trial 91 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.30881616260233985, 'l1_ratio': 0.7519481473269782}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,443] Trial 92 finished with value: 0.025800353936334983 and parameters: {'alpha': 1.019209424921239, 'l1_ratio': 0.8788400865870313}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,451] Trial 93 finished with value: 0.025800353936334983 and parameters: {'alpha': 7.180445559462251, 'l1_ratio': 0.6334371119434388}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,458] Trial 94 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.010803741717288226, 'l1_ratio': 0.7258056521429245}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,469] Trial 95 finished with value: 0.026336375548105934 and parameters: {'alpha': 9.605886412551296e-10, 'l1_ratio': 0.7013393181152086}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,477] Trial 96 finished with value: 0.025800353936334983 and parameters: {'alpha': 24.356387935602612, 'l1_ratio': 0.5823803823451288}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,484] Trial 97 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.023077612782862803, 'l1_ratio': 0.7702520042510541}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,492] Trial 98 finished with value: 0.025800353936334983 and parameters: {'alpha': 2.548382984317941, 'l1_ratio': 0.9741876649554884}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,500] Trial 99 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.7041306615187153, 'l1_ratio': 0.39617654667155094}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,509] Trial 100 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0051486391355354, 'l1_ratio': 0.9462343352233771}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,520] Trial 101 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0898921205287361, 'l1_ratio': 0.6542931265386448}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,528] Trial 102 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.007367632634584986, 'l1_ratio': 0.49808936098623174}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,540] Trial 103 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.059613091200435904, 'l1_ratio': 0.5579390633783933}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,549] Trial 104 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.019995311812075908, 'l1_ratio': 0.614847795699691}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,559] Trial 105 finished with value: 0.02629073895338487 and parameters: {'alpha': 0.00011661263952730813, 'l1_ratio': 0.6708129039241166}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,568] Trial 106 finished with value: 0.02582212474470269 and parameters: {'alpha': 0.002161223337042488, 'l1_ratio': 0.7477495948778209}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,577] Trial 107 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.1265630862592254, 'l1_ratio': 0.828616687200576}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,585] Trial 108 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.3488594665867009, 'l1_ratio': 0.6352623196862383}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,593] Trial 109 finished with value: 0.025800353936334983 and parameters: {'alpha': 13.595929027423002, 'l1_ratio': 0.8060589372630096}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,602] Trial 110 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.05119219201555237, 'l1_ratio': 0.6986381555141731}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,610] Trial 111 finished with value: 0.025800353936334983 and parameters: {'alpha': 4.535994954745639, 'l1_ratio': 0.8952567787896227}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,619] Trial 112 finished with value: 0.025800353936334983 and parameters: {'alpha': 1.5487332364985207, 'l1_ratio': 0.8709757989640501}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,628] Trial 113 finished with value: 0.025800353936334983 and parameters: {'alpha': 10.934773572933628, 'l1_ratio': 0.924956746327502}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,636] Trial 114 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.0029247352151492117, 'l1_ratio': 0.9555724271259317}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,645] Trial 115 finished with value: 0.025800353936334983 and parameters: {'alpha': 36.80988462398485, 'l1_ratio': 0.9754308296967195}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,654] Trial 116 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.629270606840409, 'l1_ratio': 0.8374468302808418}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,664] Trial 117 finished with value: 0.02621444380465954 and parameters: {'alpha': 0.00024899257248901655, 'l1_ratio': 0.9112522965211993}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,672] Trial 118 finished with value: 0.025800353936334983 and parameters: {'alpha': 3.220925406167097, 'l1_ratio': 0.8554810370499442}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,681] Trial 119 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.014475117579804082, 'l1_ratio': 0.7185819154139241}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,690] Trial 120 finished with value: 0.025800353936334983 and parameters: {'alpha': 23.686993999865912, 'l1_ratio': 0.7757448790962609}. Best is trial 17 with value: 0.02579851685820099.
[I 2026-10-14 15:41:57,698] Trial 121 finished with value: 0.025800353936334983 and parameters: {'alpha': 0.1639466346636477, 'l1_ratio': 0.7927127224051362}. Best is trial 17 with value: 0.02579851685820099.

[ 0. -0. -0. -0. -0. -0.  0.  0. -0.  0.  0.]
12

[I 2026-10-14 15:41:59,045] Trial 28 finished with value: 0.011941686544248717 and parameters: {'alpha': 12.668300953441735, 'l1_ratio': 0.9282224331392944}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,052] Trial 29 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.501550916478977, 'l1_ratio': 0.20144843233277718}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,059] Trial 30 finished with value: 0.011941686544248717 and parameters: {'alpha': 72.66827644504198, 'l1_ratio': 0.44937716133325917}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,067] Trial 31 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.19549041449749763, 'l1_ratio': 0.01758494247700703}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,074] Trial 32 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.020233905281635416, 'l1_ratio': 0.11089094049738123}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,082] Trial 33 finished with value: 0.012406758301634818 and parameters: {'alpha': 0.00023332951890687586, 'l1_ratio': 0.13933087290019414}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,091] Trial 34 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.08323777121064686, 'l1_ratio': 0.3359925835942584}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,098] Trial 35 finished with value: 0.011941686544248717 and parameters: {'alpha': 3.9203108006887075, 'l1_ratio': 0.06900219092929527}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,108] Trial 36 finished with value: 0.012429958046008048 and parameters: {'alpha': 1.7171162799416682e-07, 'l1_ratio': 0.21395042142283882}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,116] Trial 37 finished with value: 0.012011054675965683 and parameters: {'alpha': 0.006031636241114165, 'l1_ratio': 0.1727151478240849}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,124] Trial 38 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.06453254304391019, 'l1_ratio': 0.26675267993219}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,132] Trial 39 finished with value: 0.011941686544248717 and parameters: {'alpha': 23.51268407257772, 'l1_ratio': 0.05284890295990691}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,140] Trial 40 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.9246107292295201, 'l1_ratio': 0.9378643390067616}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,148] Trial 41 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.1295242621425239, 'l1_ratio': 0.2884141147921143}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,157] Trial 42 finished with value: 0.011941686544248717 and parameters: {'alpha': 3.748727296268377, 'l1_ratio': 0.0682213245815013}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,166] Trial 43 finished with value: 0.012380392064881266 and parameters: {'alpha': 0.00045227834183676703, 'l1_ratio': 0.16338497113055633}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,176] Trial 44 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.027477331781443206, 'l1_ratio': 0.3295433814383231}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,185] Trial 45 finished with value: 0.011941686544248717 and parameters: {'alpha': 2.540638639442323, 'l1_ratio': 0.007692628355077738}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,193] Trial 46 finished with value: 0.012119980077548161 and parameters: {'alpha': 0.0013799353897661296, 'l1_ratio': 0.4911813933051976}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,203] Trial 47 finished with value: 0.011941686544248717 and parameters: {'alpha': 25.735643232106074, 'l1_ratio': 0.8829771151667367}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,211] Trial 48 finished with value: 0.01242245922868759 and parameters: {'alpha': 3.2620931325032627e-05, 'l1_ratio': 0.37469417489984574}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,219] Trial 49 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.6580976944306568, 'l1_ratio': 0.23891567776402578}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,228] Trial 50 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.008042978903293006, 'l1_ratio': 0.7514756997276719}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,239] Trial 51 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.05982524849109338, 'l1_ratio': 0.908038968414393}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,247] Trial 52 finished with value: 0.011941686544248717 and parameters: {'alpha': 4.73506572707543, 'l1_ratio': 0.8241723241123295}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,256] Trial 53 finished with value: 0.011941686544248717 and parameters: {'alpha': 1.0624654869295773, 'l1_ratio': 0.9955626925238168}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,263] Trial 54 finished with value: 0.01197827357262126 and parameters: {'alpha': 0.0021050503120651127, 'l1_ratio': 0.6180486339533613}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,271] Trial 55 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.2344223115229101, 'l1_ratio': 0.9533552610618753}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,277] Trial 56 finished with value: 0.011941686544248717 and parameters: {'alpha': 27.805640845176864, 'l1_ratio': 0.7003044225607187}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,286] Trial 57 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.027062757668459694, 'l1_ratio': 0.10048228602727376}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,293] Trial 58 finished with value: 0.011941686544248717 and parameters: {'alpha': 1.6695784719192834, 'l1_ratio': 0.7957363716163489}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,301] Trial 59 finished with value: 0.011941686544248717 and parameters: {'alpha': 91.25374557759167, 'l1_ratio': 0.8917559427241237}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,308] Trial 60 finished with value: 0.011941686544248717 and parameters: {'alpha': 11.894577592258797, 'l1_ratio': 0.8616155410341438}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,316] Trial 61 finished with value: 0.011941686544248717 and parameters: {'alpha': 31.850371935186377, 'l1_ratio': 0.5401128680691154}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,323] Trial 62 finished with value: 0.011941686544248717 and parameters: {'alpha': 6.011922359246927, 'l1_ratio': 0.6553478192796345}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,331] Trial 63 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.4241015888848013, 'l1_ratio': 0.7390111834116943}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,339] Trial 64 finished with value: 0.011941686544248717 and parameters: {'alpha': 46.30254231788073, 'l1_ratio': 0.45574476073052017}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,347] Trial 65 finished with value: 0.011941686544248717 and parameters: {'alpha': 14.128001935061725, 'l1_ratio': 0.8127887939886052}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,356] Trial 66 finished with value: 0.011941686544248717 and parameters: {'alpha': 2.206918809004949, 'l1_ratio': 0.5533966897364739}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,366] Trial 67 finished with value: 0.012429964523895672 and parameters: {'alpha': 4.151260237130433e-07, 'l1_ratio': 0.034175876846646025}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,375] Trial 68 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.04504524833950046, 'l1_ratio': 0.9625540212652749}. Best is trial 1 with value: 0.011941686544248717.
[I 2026-10-14 15:41:59,383] Trial 69 finished with value: 0.011936736586444355 and parameters: {'alpha': 0.012906510041125044, 'l1_ratio': 0.13544331192314457}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,390] Trial 70 finished with value: 0.011937454259196541 and parameters: {'alpha': 0.013263776367268425, 'l1_ratio': 0.1456646261665666}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,398] Trial 71 finished with value: 0.01196417829555346 and parameters: {'alpha': 0.009709622266483513, 'l1_ratio': 0.1383465006702795}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,407] Trial 72 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.15693530728904811, 'l1_ratio': 0.09821571312627742}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,415] Trial 73 finished with value: 0.012050490211792353 and parameters: {'alpha': 0.004816638236568023, 'l1_ratio': 0.17940580444802806}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,423] Trial 74 finished with value: 0.01235281570024546 and parameters: {'alpha': 0.0007948709757993853, 'l1_ratio': 0.1452530824516307}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,432] Trial 75 finished with value: 0.012267009767105628 and parameters: {'alpha': 0.00362998238598881, 'l1_ratio': 0.055248422844518336}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,441] Trial 76 finished with value: 0.0124178488661482 and parameters: {'alpha': 8.171304596841394e-05, 'l1_ratio': 0.22660225420250613}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,450] Trial 77 finished with value: 0.011944276321991302 and parameters: {'alpha': 0.019474248576534355, 'l1_ratio': 0.07916281297341682}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,461] Trial 78 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.09042098115394731, 'l1_ratio': 0.26374925446019415}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,471] Trial 79 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.4169041505464587, 'l1_ratio': 0.20240081574986182}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,481] Trial 80 finished with value: 0.011966335428412543 and parameters: {'alpha': 0.0324935319117805, 'l1_ratio': 0.03503729591494073}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,493] Trial 81 finished with value: 0.012429982382202855 and parameters: {'alpha': 2.6572717843551133e-09, 'l1_ratio': 0.12231749082446997}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,503] Trial 82 finished with value: 0.012013072679133296 and parameters: {'alpha': 0.010896081485833722, 'l1_ratio': 0.08781510905213055}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,511] Trial 83 finished with value: 0.011941686544248717 and parameters: {'alpha': 8.541531603441909, 'l1_ratio': 0.3679602758183276}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,521] Trial 84 finished with value: 0.011941686544248717 and parameters: {'alpha': 43.50889913679354, 'l1_ratio': 0.18213953787907378}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,530] Trial 85 finished with value: 0.011941686544248717 and parameters: {'alpha': 17.753587063410254, 'l1_ratio': 0.9226676885301972}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,539] Trial 86 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.8352881505675901, 'l1_ratio': 0.615959342817854}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,548] Trial 87 finished with value: 0.011941686544248717 and parameters: {'alpha': 99.66138804087025, 'l1_ratio': 0.3034567697713821}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,557] Trial 88 finished with value: 0.01226755549500828 and parameters: {'alpha': 0.0020853738914448725, 'l1_ratio': 0.1216548352719473}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,567] Trial 89 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.12482036504206606, 'l1_ratio': 0.0308138997348108}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,576] Trial 90 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.26023774148140627, 'l1_ratio': 0.5023820420763351}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,584] Trial 91 finished with value: 0.011941686544248717 and parameters: {'alpha': 3.441053763477822, 'l1_ratio': 0.009640305772551427}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,591] Trial 92 finished with value: 0.011941686544248717 and parameters: {'alpha': 9.440737912175699, 'l1_ratio': 0.06647096349548318}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,598] Trial 93 finished with value: 0.011941686544248717 and parameters: {'alpha': 1.5917366653450709, 'l1_ratio': 0.15008383688054105}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,606] Trial 94 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.016001306358104213, 'l1_ratio': 0.9833153110164553}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,614] Trial 95 finished with value: 0.011941686544248717 and parameters: {'alpha': 6.264596176041878, 'l1_ratio': 0.4166174005009555}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,622] Trial 96 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.07420663877491462, 'l1_ratio': 0.050851436178215345}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,631] Trial 97 finished with value: 0.012060685767478572 and parameters: {'alpha': 0.04291698794394856, 'l1_ratio': 0.0032480138307939}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,640] Trial 98 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.6038949513931237, 'l1_ratio': 0.6523673232659591}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,649] Trial 99 finished with value: 0.011941686544248717 and parameters: {'alpha': 51.55997139635309, 'l1_ratio': 0.7106746210334332}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,657] Trial 100 finished with value: 0.011941686544248717 and parameters: {'alpha': 1.312381577156656, 'l1_ratio': 0.5849665615635723}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,665] Trial 101 finished with value: 0.011941686544248717 and parameters: {'alpha': 2.91740313939345, 'l1_ratio': 0.7716649009003659}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,673] Trial 102 finished with value: 0.011941686544248717 and parameters: {'alpha': 20.72507550386736, 'l1_ratio': 0.8487232552281869}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,681] Trial 103 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.22688333286274356, 'l1_ratio': 0.9488161537822579}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,688] Trial 104 finished with value: 0.011941686544248717 and parameters: {'alpha': 5.411232760676245, 'l1_ratio': 0.7276885501202647}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,696] Trial 105 finished with value: 0.011941686544248717 and parameters: {'alpha': 2.2360555602394845, 'l1_ratio': 0.9170361976368582}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,704] Trial 106 finished with value: 0.011941686544248717 and parameters: {'alpha': 26.124480944345585, 'l1_ratio': 0.9741386494368695}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,713] Trial 107 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.01270853802588414, 'l1_ratio': 0.876543346747035}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,722] Trial 108 finished with value: 0.012068772530709839 and parameters: {'alpha': 0.006586152924697526, 'l1_ratio': 0.1133997726679467}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,730] Trial 109 finished with value: 0.011941686544248717 and parameters: {'alpha': 14.828976436078792, 'l1_ratio': 0.0894682090319035}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,738] Trial 110 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.7784276552945459, 'l1_ratio': 0.6895533386486595}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,747] Trial 111 finished with value: 0.011941686544248717 and parameters: {'alpha': 53.59331610239437, 'l1_ratio': 0.7678366041568123}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,755] Trial 112 finished with value: 0.011941686544248717 and parameters: {'alpha': 34.17114631146066, 'l1_ratio': 0.6325806424053665}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,763] Trial 113 finished with value: 0.011941686544248717 and parameters: {'alpha': 66.88996882611636, 'l1_ratio': 0.6763594719776744}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,772] Trial 114 finished with value: 0.011941686544248717 and parameters: {'alpha': 6.717770372447977, 'l1_ratio': 0.8007820267728044}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,780] Trial 115 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.002936371515096542, 'l1_ratio': 0.8283989901238427}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,790] Trial 116 finished with value: 0.01212481703710404 and parameters: {'alpha': 0.0011363623429232197, 'l1_ratio': 0.5884219662209698}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,799] Trial 117 finished with value: 0.011941686544248717 and parameters: {'alpha': 13.621904457738621, 'l1_ratio': 0.9008408084786833}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,809] Trial 118 finished with value: 0.011943572446844236 and parameters: {'alpha': 0.04917787100656491, 'l1_ratio': 0.03039198298401362}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,818] Trial 119 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.11334512363307496, 'l1_ratio': 0.7428391001159904}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,827] Trial 120 finished with value: 0.011941686544248717 and parameters: {'alpha': 0.33210449372659334, 'l1_ratio': 0.16431887467388626}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,835] Trial 121 finished with value: 0.011941686544248717 and parameters: {'alpha': 1.01533190530289, 'l1_ratio': 0.05199521537942959}. Best is trial 69 with value: 0.011936736586444355.
[I 2026-10-14 15:41:59,843] Trial 122 finished with value: 0.011941686544248717 and parameters: {'alpha': 3.8951509905710986, 'l1_ratio': 0.12285390956049694}. Best is trial 69 with value: 0.011936736586444355.

[ 0.        -0.        -0.        -0.        -0.        -0.
  0.0021164  0.        -0.         0.         0.       ]
18

[I 2026-10-14 15:42:01,194] Trial 27 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.013497991540610094, 'l1_ratio': 0.20886508142635085}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,200] Trial 28 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.4827344325717242, 'l1_ratio': 0.29863793408011213}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,208] Trial 29 finished with value: 0.010454006888877565 and parameters: {'alpha': 0.0004232093064689508, 'l1_ratio': 0.4438195517750848}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,215] Trial 30 finished with value: 0.010284777982074745 and parameters: {'alpha': 8.238979334365865, 'l1_ratio': 0.08613716513564594}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,222] Trial 31 finished with value: 0.010284777982074745 and parameters: {'alpha': 19.070684434826447, 'l1_ratio': 0.5430657394893069}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,229] Trial 32 finished with value: 0.010284777982074745 and parameters: {'alpha': 84.78073936859813, 'l1_ratio': 0.7112338758155788}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,239] Trial 33 finished with value: 0.010506468604133493 and parameters: {'alpha': 1.6709725664588337e-08, 'l1_ratio': 0.45116229902438787}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,247] Trial 34 finished with value: 0.010284777982074745 and parameters: {'alpha': 1.3171402745527856, 'l1_ratio': 0.505865282115385}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,254] Trial 35 finished with value: 0.010284777982074745 and parameters: {'alpha': 9.420414440783459, 'l1_ratio': 0.6102359272395115}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,262] Trial 36 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.4815199183407506, 'l1_ratio': 0.8468650853069167}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,272] Trial 37 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.006723196694079145, 'l1_ratio': 0.4101812544475349}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,280] Trial 38 finished with value: 0.010284777982074745 and parameters: {'alpha': 6.196780412959423, 'l1_ratio': 0.7105994843954293}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,288] Trial 39 finished with value: 0.010284777982074745 and parameters: {'alpha': 24.109546983327114, 'l1_ratio': 0.039125690430584656}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,299] Trial 40 finished with value: 0.01050646923612832 and parameters: {'alpha': 3.704432435684454e-08, 'l1_ratio': 0.12383465549287384}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,308] Trial 41 finished with value: 0.010456835585353645 and parameters: {'alpha': 0.0002217501285035627, 'l1_ratio': 0.8240161659432217}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,317] Trial 42 finished with value: 0.010486373316396342 and parameters: {'alpha': 7.368541929344153e-05, 'l1_ratio': 0.9682331533406454}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,326] Trial 43 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.0425233797592285, 'l1_ratio': 0.906972294647967}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,334] Trial 44 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.25531331296979565, 'l1_ratio': 0.793814247220083}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,342] Trial 45 finished with value: 0.010284777982074745 and parameters: {'alpha': 1.7814656806252944, 'l1_ratio': 0.65121339435896}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,350] Trial 46 finished with value: 0.010374262381672104 and parameters: {'alpha': 0.002297847464478276, 'l1_ratio': 0.2305747994974841}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,362] Trial 47 finished with value: 0.010506470916474053 and parameters: {'alpha': 1.0414438513461979e-10, 'l1_ratio': 0.043656347396101844}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,369] Trial 48 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.020878809076696613, 'l1_ratio': 0.3952835124427547}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,378] Trial 49 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.8591035124462383, 'l1_ratio': 0.7673438601282934}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,386] Trial 50 finished with value: 0.010284777982074745 and parameters: {'alpha': 36.01874100109122, 'l1_ratio': 0.5639144571961251}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,394] Trial 51 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.04692585466095076, 'l1_ratio': 0.3164825038977634}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,402] Trial 52 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.1165733827206729, 'l1_ratio': 0.5078987430535986}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,410] Trial 53 finished with value: 0.010284777982074745 and parameters: {'alpha': 3.5835105589844707, 'l1_ratio': 0.1948743041626549}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,417] Trial 54 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.006305895594332731, 'l1_ratio': 0.3359317796979492}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,426] Trial 55 finished with value: 0.010284777982074745 and parameters: {'alpha': 18.707867812081602, 'l1_ratio': 0.2748388753050757}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,433] Trial 56 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.2757408111820897, 'l1_ratio': 0.13403922979218608}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,442] Trial 57 finished with value: 0.010361990863167457 and parameters: {'alpha': 0.0015672583833691244, 'l1_ratio': 0.4007807066382303}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,453] Trial 58 finished with value: 0.010506319021557313 and parameters: {'alpha': 1.469455998298369e-05, 'l1_ratio': 0.0004931955402369681}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,461] Trial 59 finished with value: 0.010284777982074745 and parameters: {'alpha': 3.36106017602195, 'l1_ratio': 0.9077645871327633}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,472] Trial 60 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.07970777789065636, 'l1_ratio': 0.0664564943711968}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,481] Trial 61 finished with value: 0.010380398249202862 and parameters: {'alpha': 0.00786942357471862, 'l1_ratio': 0.04520874801884456}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,489] Trial 62 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.870265496423882, 'l1_ratio': 0.17993969759538275}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,496] Trial 63 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.2312883878569377, 'l1_ratio': 0.10355705354282463}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,504] Trial 64 finished with value: 0.010284777982074745 and parameters: {'alpha': 90.94367795847647, 'l1_ratio': 0.37491755096362955}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,512] Trial 65 finished with value: 0.010284777982074745 and parameters: {'alpha': 37.329946599254114, 'l1_ratio': 0.4725334486395556}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,523] Trial 66 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.7787992879962785, 'l1_ratio': 0.2651860289160392}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,532] Trial 67 finished with value: 0.010284777982074745 and parameters: {'alpha': 12.973995325797958, 'l1_ratio': 0.6185475161559237}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,540] Trial 68 finished with value: 0.010284777982074745 and parameters: {'alpha': 4.046494247104165, 'l1_ratio': 0.6832013436175794}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,549] Trial 69 finished with value: 0.010354025046672176 and parameters: {'alpha': 0.013546186651995612, 'l1_ratio': 0.030922257687194463}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,558] Trial 70 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.054841049743373387, 'l1_ratio': 0.1562302256671754}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,569] Trial 71 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.39488630690541615, 'l1_ratio': 0.5277798318885956}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,579] Trial 72 finished with value: 0.010284777982074745 and parameters: {'alpha': 1.9256070448332747, 'l1_ratio': 0.41820532664762655}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,588] Trial 73 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.1566130003089304, 'l1_ratio': 0.5932266648180797}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,598] Trial 74 finished with value: 0.010426948665226268 and parameters: {'alpha': 0.0006239089835167688, 'l1_ratio': 0.48168271651530087}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,608] Trial 75 finished with value: 0.010284777982074745 and parameters: {'alpha': 8.059812235533663, 'l1_ratio': 0.07370194522698326}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,617] Trial 76 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.02811002948702112, 'l1_ratio': 0.5433655504922252}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,626] Trial 77 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.9725674156752585, 'l1_ratio': 0.6368364704490127}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,635] Trial 78 finished with value: 0.010284777982074745 and parameters: {'alpha': 39.45938863166562, 'l1_ratio': 0.6743268883743971}. Best is trial 0 with value: 0.010284777982074745.
[I 2026-10-14 15:42:01,644] Trial 79 finished with value: 0.010279258733342098 and parameters: {'alpha': 0.0036397976143348596, 'l1_ratio': 0.4390411589536065}. Best is trial 79 with value: 0.010279258733342098.
[I 2026-10-14 15:42:01,652] Trial 80 finished with value: 0.010277614904236546 and parameters: {'alpha': 0.0038920391562428064, 'l1_ratio': 0.4315784778632649}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,661] Trial 81 finished with value: 0.010283163160949725 and parameters: {'alpha': 0.003358975920517334, 'l1_ratio': 0.43648206035547404}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,670] Trial 82 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.005757023792462673, 'l1_ratio': 0.432636157945376}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,680] Trial 83 finished with value: 0.010307347611786966 and parameters: {'alpha': 0.0010921615874216802, 'l1_ratio': 0.9982979023201618}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,690] Trial 84 finished with value: 0.010279018834446861 and parameters: {'alpha': 0.0035172163174373603, 'l1_ratio': 0.457363312883024}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,701] Trial 85 finished with value: 0.010490789839647992 and parameters: {'alpha': 0.00011495096650209768, 'l1_ratio': 0.46097568632527053}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,710] Trial 86 finished with value: 0.010292715402181546 and parameters: {'alpha': 0.002592646815298438, 'l1_ratio': 0.4914739031743721}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,718] Trial 87 finished with value: 0.010475791430080934 and parameters: {'alpha': 0.0002974099917150533, 'l1_ratio': 0.351284213926521}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,727] Trial 88 finished with value: 0.010277693330144678 and parameters: {'alpha': 0.004040754660093701, 'l1_ratio': 0.4371533260303722}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,736] Trial 89 finished with value: 0.010505310669764033 and parameters: {'alpha': 8.542456490059124e-06, 'l1_ratio': 0.4428588458839352}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,747] Trial 90 finished with value: 0.01029122296484965 and parameters: {'alpha': 0.0034277370646213826, 'l1_ratio': 0.37658416416030427}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,755] Trial 91 finished with value: 0.01041993067956656 and parameters: {'alpha': 0.00077112376881947, 'l1_ratio': 0.4269524724089376}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,764] Trial 92 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.01937167252359174, 'l1_ratio': 0.5277019676745978}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,773] Trial 93 finished with value: 0.01049918085004879 and parameters: {'alpha': 6.155730599479478e-05, 'l1_ratio': 0.38728038744141285}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,782] Trial 94 finished with value: 0.010296313415543084 and parameters: {'alpha': 0.0039651223935995164, 'l1_ratio': 0.3017783192826361}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,792] Trial 95 finished with value: 0.01036991940929623 and parameters: {'alpha': 0.0017229665740741687, 'l1_ratio': 0.33085988273845657}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,800] Trial 96 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.010858700782139902, 'l1_ratio': 0.45853865830503643}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,809] Trial 97 finished with value: 0.010459169156487915 and parameters: {'alpha': 0.0003401222067629289, 'l1_ratio': 0.49755731307077655}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,818] Trial 98 finished with value: 0.010378681546032402 and parameters: {'alpha': 0.0009539298166825488, 'l1_ratio': 0.5643938501430156}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,827] Trial 99 finished with value: 0.010284777982074745 and parameters: {'alpha': 52.58928111647255, 'l1_ratio': 0.41213588866170636}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,837] Trial 100 finished with value: 0.010483982371042325 and parameters: {'alpha': 0.0001489084648476787, 'l1_ratio': 0.5233965654736823}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,845] Trial 101 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.01564805887818115, 'l1_ratio': 0.36979835209078377}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,855] Trial 102 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.06928309809989942, 'l1_ratio': 0.4471456126930508}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,864] Trial 103 finished with value: 0.010278187955085807 and parameters: {'alpha': 0.007586516933753401, 'l1_ratio': 0.2173302150617895}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,874] Trial 104 finished with value: 0.010472378291023987 and parameters: {'alpha': 0.0004998297767616594, 'l1_ratio': 0.22193235083926968}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,884] Trial 105 finished with value: 0.010284777982074745 and parameters: {'alpha': 17.13881543453143, 'l1_ratio': 0.24379069923395577}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,893] Trial 106 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.0075302067772733475, 'l1_ratio': 0.8724139162027679}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,902] Trial 107 finished with value: 0.01037906559839096 and parameters: {'alpha': 0.003611204876383668, 'l1_ratio': 0.12984582063598282}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,911] Trial 108 finished with value: 0.010320110930334078 and parameters: {'alpha': 0.002012828502120415, 'l1_ratio': 0.47511143880807516}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,920] Trial 109 finished with value: 0.010277969565928326 and parameters: {'alpha': 0.005107296536778246, 'l1_ratio': 0.3503230068991636}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,928] Trial 110 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.03301723619444232, 'l1_ratio': 0.39173386656671666}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,935] Trial 111 finished with value: 0.010431190712871888 and parameters: {'alpha': 0.0013432916915909236, 'l1_ratio': 0.19255215065536013}. Best is trial 80 with value: 0.010277614904236546.
[I 2026-10-14 15:42:01,944] Trial 112 finished with value: 0.010277576858696357 and parameters: {'alpha': 0.004928585446864702, 'l1_ratio': 0.35378907300707835}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,951] Trial 113 finished with value: 0.010278379926753567 and parameters: {'alpha': 0.005833787475908235, 'l1_ratio': 0.3129388597476723}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,960] Trial 114 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.011098330901415859, 'l1_ratio': 0.34100377276066474}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,969] Trial 115 finished with value: 0.010280835611724513 and parameters: {'alpha': 0.004858422482171525, 'l1_ratio': 0.31518139172393855}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,978] Trial 116 finished with value: 0.01029381816324234 and parameters: {'alpha': 0.00437789354643888, 'l1_ratio': 0.2816591184786572}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,986] Trial 117 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.025901382816097836, 'l1_ratio': 0.30440951431156377}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:01,995] Trial 118 finished with value: 0.010344549864620136 and parameters: {'alpha': 0.0022592722621916765, 'l1_ratio': 0.32765264889947476}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:02,003] Trial 119 finished with value: 0.010284777982074745 and parameters: {'alpha': 0.008344442349430489, 'l1_ratio': 0.35744529134294867}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:02,013] Trial 120 finished with value: 0.01043637803071295 and parameters: {'alpha': 0.000611871430134948, 'l1_ratio': 0.4214565847753111}. Best is trial 112 with value: 0.010277576858696357.
[I 2026-10-14 15:42:02,021] Trial 121 finished with value: 0.010297145635467141 and parameters: {'alpha': 0.004364288208674133, 'l1_ratio': 0.269871071447602}. Best is trial 112 with value: 0.010277576858696357.

[ 0.         -0.         -0.         -0.         -0.         -0.
  0.00252049  0.         -0.          0.          0.        ]
24

[I 2026-10-14 15:42:03,444] Trial 23 finished with value: 0.010065419044590877 and parameters: {'alpha': 5.805104899742456, 'l1_ratio': 0.8422659785819167}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,452] Trial 24 finished with value: 0.010065419044590877 and parameters: {'alpha': 53.223973803448885, 'l1_ratio': 0.72190883417752}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,460] Trial 25 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.35953548249109263, 'l1_ratio': 0.008401284773736417}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,468] Trial 26 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.0410200649863386, 'l1_ratio': 0.793592656032957}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,475] Trial 27 finished with value: 0.010065419044590877 and parameters: {'alpha': 1.0312992841266693, 'l1_ratio': 0.1052860083827723}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,482] Trial 28 finished with value: 0.010065419044590877 and parameters: {'alpha': 11.189808315857361, 'l1_ratio': 0.3532723961647253}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,490] Trial 29 finished with value: 0.010147848496454002 and parameters: {'alpha': 0.0011480599342807236, 'l1_ratio': 0.5928799360717332}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,500] Trial 30 finished with value: 0.010317588673809204 and parameters: {'alpha': 1.5189112451855685e-05, 'l1_ratio': 0.22260118897220105}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,507] Trial 31 finished with value: 0.010065419044590877 and parameters: {'alpha': 95.69638690529861, 'l1_ratio': 0.4314499125324598}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,515] Trial 32 finished with value: 0.010065419044590877 and parameters: {'alpha': 23.532414102930257, 'l1_ratio': 0.36345402775157565}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,523] Trial 33 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.9726808375578582, 'l1_ratio': 0.13505018021003695}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,531] Trial 34 finished with value: 0.010065419044590877 and parameters: {'alpha': 12.668180529857306, 'l1_ratio': 0.33488915995620677}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,540] Trial 35 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.07880067313778745, 'l1_ratio': 0.24091744150711342}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,548] Trial 36 finished with value: 0.010065419044590877 and parameters: {'alpha': 98.25576552871503, 'l1_ratio': 0.4746566092582295}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,556] Trial 37 finished with value: 0.010065419044590877 and parameters: {'alpha': 1.4538553995235697, 'l1_ratio': 0.5805984689687864}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,568] Trial 38 finished with value: 0.010318830052098975 and parameters: {'alpha': 1.739654508670771e-08, 'l1_ratio': 0.7538919957609708}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,575] Trial 39 finished with value: 0.010065419044590877 and parameters: {'alpha': 14.267832553062176, 'l1_ratio': 0.895275567463965}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,585] Trial 40 finished with value: 0.010160887847608989 and parameters: {'alpha': 0.008476758937893387, 'l1_ratio': 0.052813341030400335}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,593] Trial 41 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.22251139617688168, 'l1_ratio': 0.4257490521364621}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,600] Trial 42 finished with value: 0.010065419044590877 and parameters: {'alpha': 2.0538449683533084, 'l1_ratio': 0.3865433195139758}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,607] Trial 43 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.15149362122994056, 'l1_ratio': 0.4576527118023726}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,614] Trial 44 finished with value: 0.010065419044590877 and parameters: {'alpha': 20.20001050220855, 'l1_ratio': 0.18071170129463304}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,621] Trial 45 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.6386944270927378, 'l1_ratio': 0.3102976696616647}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,628] Trial 46 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.009004705551454092, 'l1_ratio': 0.25021591345599653}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,635] Trial 47 finished with value: 0.010065419044590877 and parameters: {'alpha': 3.0975384849558787, 'l1_ratio': 0.38527970972477743}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,643] Trial 48 finished with value: 0.010065419044590877 and parameters: {'alpha': 38.6321099590693, 'l1_ratio': 0.6350123998230192}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,649] Trial 49 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.024229880812543583, 'l1_ratio': 0.5621017104647182}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,658] Trial 50 finished with value: 0.010065419044590877 and parameters: {'alpha': 5.285517031037268, 'l1_ratio': 0.47863718280748313}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,666] Trial 51 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.16316231723997288, 'l1_ratio': 0.3131474946610781}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,675] Trial 52 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.07605897947130502, 'l1_ratio': 0.2781803449779001}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,687] Trial 53 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.5162251008209181, 'l1_ratio': 0.19689503271325803}. Best is trial 5 with value: 0.010065419044590877.
[I 2026-10-14 15:42:03,696] Trial 54 finished with value: 0.010065248100962834 and parameters: {'alpha': 0.002994410757414879, 'l1_ratio': 0.6818584153841746}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,706] Trial 55 finished with value: 0.010202361133569506 and parameters: {'alpha': 0.0005688570257286228, 'l1_ratio': 0.7137602177959099}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,716] Trial 56 finished with value: 0.010317682492902852 and parameters: {'alpha': 5.023859175874136e-06, 'l1_ratio': 0.6801647391029215}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,726] Trial 57 finished with value: 0.010065419044590877 and parameters: {'alpha': 34.73706840836051, 'l1_ratio': 0.9835606015628708}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,734] Trial 58 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.0029541763119859932, 'l1_ratio': 0.7725964747549603}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,743] Trial 59 finished with value: 0.010293237473039955 and parameters: {'alpha': 9.808741109242438e-05, 'l1_ratio': 0.8078310144418757}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,752] Trial 60 finished with value: 0.010065419044590877 and parameters: {'alpha': 2.4465941809984546, 'l1_ratio': 0.9172436888846546}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,760] Trial 61 finished with value: 0.010132908477633687 and parameters: {'alpha': 0.0027817944572165344, 'l1_ratio': 0.26882391783818366}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,768] Trial 62 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.015967073013764543, 'l1_ratio': 0.5129413020198256}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,776] Trial 63 finished with value: 0.010065419044590877 and parameters: {'alpha': 6.580746115725357, 'l1_ratio': 0.34447759943561007}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,784] Trial 64 finished with value: 0.010065419044590877 and parameters: {'alpha': 94.54851324142066, 'l1_ratio': 0.40911853445471597}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,792] Trial 65 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.05573210778961187, 'l1_ratio': 0.8689691727677067}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,802] Trial 66 finished with value: 0.010314883856837412 and parameters: {'alpha': 5.0913245431503305e-05, 'l1_ratio': 0.2098159881614079}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,810] Trial 67 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.4036396051602683, 'l1_ratio': 0.16274297033795887}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,819] Trial 68 finished with value: 0.010065419044590877 and parameters: {'alpha': 1.1471268850381324, 'l1_ratio': 0.11385527228086623}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,826] Trial 69 finished with value: 0.010065419044590877 and parameters: {'alpha': 10.902962770644463, 'l1_ratio': 0.5475744853920624}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,835] Trial 70 finished with value: 0.010173342714552586 and parameters: {'alpha': 0.0008918309538017851, 'l1_ratio': 0.6004048391677426}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,842] Trial 71 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.005929664528970045, 'l1_ratio': 0.5116361514310517}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,849] Trial 72 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.039674507048756066, 'l1_ratio': 0.37300474883284374}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,858] Trial 73 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.13452907281067022, 'l1_ratio': 0.31545797082692095}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,866] Trial 74 finished with value: 0.01026101201081599 and parameters: {'alpha': 0.0004067109173038312, 'l1_ratio': 0.44730146027348544}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,875] Trial 75 finished with value: 0.010139279329927128 and parameters: {'alpha': 0.0014621386988778432, 'l1_ratio': 0.4987784632481746}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,884] Trial 76 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.021930020347285483, 'l1_ratio': 0.6899265598467967}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,891] Trial 77 finished with value: 0.010065419044590877 and parameters: {'alpha': 28.940278369529032, 'l1_ratio': 0.40866278553016266}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,901] Trial 78 finished with value: 0.010065419044590877 and parameters: {'alpha': 3.8937893696047827, 'l1_ratio': 0.2409004133792274}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,909] Trial 79 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.004682743283497145, 'l1_ratio': 0.9516549300445316}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,916] Trial 80 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.013886816645270653, 'l1_ratio': 0.34845041109558045}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,924] Trial 81 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.28928383589620554, 'l1_ratio': 0.4860286771275038}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,931] Trial 82 finished with value: 0.010065419044590877 and parameters: {'alpha': 59.45571856804711, 'l1_ratio': 0.540912527422209}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,938] Trial 83 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.8230211480825105, 'l1_ratio': 0.4239759247613944}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,945] Trial 84 finished with value: 0.010065419044590877 and parameters: {'alpha': 15.540983679935803, 'l1_ratio': 0.4484241727787107}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,952] Trial 85 finished with value: 0.010065419044590877 and parameters: {'alpha': 8.368149006048917, 'l1_ratio': 0.38472401655791727}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,960] Trial 86 finished with value: 0.010065419044590877 and parameters: {'alpha': 1.8988618391501604, 'l1_ratio': 0.6183809154120629}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,967] Trial 87 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.12575814626330872, 'l1_ratio': 0.29059709163257286}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,975] Trial 88 finished with value: 0.010065419044590877 and parameters: {'alpha': 21.30364778974892, 'l1_ratio': 0.25725827507311094}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,986] Trial 89 finished with value: 0.010318833991871303 and parameters: {'alpha': 2.5568609769852774e-09, 'l1_ratio': 0.5361493816533695}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:03,994] Trial 90 finished with value: 0.010065419044590877 and parameters: {'alpha': 5.774704389859588, 'l1_ratio': 0.5740028014125006}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,002] Trial 91 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.49421217263486694, 'l1_ratio': 0.6514179368457914}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,012] Trial 92 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.0392696132518208, 'l1_ratio': 0.46268425124292506}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,021] Trial 93 finished with value: 0.010065419044590877 and parameters: {'alpha': 50.65346449021217, 'l1_ratio': 0.8070529142698681}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,032] Trial 94 finished with value: 0.010318810901691318 and parameters: {'alpha': 9.331381253508845e-08, 'l1_ratio': 0.7510000022437328}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,042] Trial 95 finished with value: 0.010065419044590877 and parameters: {'alpha': 1.4958524520170564, 'l1_ratio': 0.330750370107993}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,053] Trial 96 finished with value: 0.010065419044590877 and parameters: {'alpha': 3.449856369617283, 'l1_ratio': 0.4360896174897792}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,065] Trial 97 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.09901072416594044, 'l1_ratio': 0.6815758292301489}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,077] Trial 98 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.3169998265924936, 'l1_ratio': 0.3892975455465182}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,089] Trial 99 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.19159665743311088, 'l1_ratio': 0.3617931792395381}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,101] Trial 100 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.8203124917774706, 'l1_ratio': 0.8393724416692521}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,112] Trial 101 finished with value: 0.010065419044590877 and parameters: {'alpha': 64.52051203601997, 'l1_ratio': 0.1787241153104164}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,124] Trial 102 finished with value: 0.010065419044590877 and parameters: {'alpha': 19.761460580179268, 'l1_ratio': 0.23008969570417695}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,136] Trial 103 finished with value: 0.010065419044590877 and parameters: {'alpha': 9.440631722637614, 'l1_ratio': 0.30195936536496365}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,148] Trial 104 finished with value: 0.010065419044590877 and parameters: {'alpha': 40.85380452289435, 'l1_ratio': 0.14246263827209596}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,158] Trial 105 finished with value: 0.010065419044590877 and parameters: {'alpha': 4.282594246699442, 'l1_ratio': 0.0730927224094367}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,169] Trial 106 finished with value: 0.010286229059317297 and parameters: {'alpha': 0.0002073329213195728, 'l1_ratio': 0.47999385666389954}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,179] Trial 107 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.0551582258376632, 'l1_ratio': 0.20770457428288788}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,188] Trial 108 finished with value: 0.010065419044590877 and parameters: {'alpha': 78.2034048649737, 'l1_ratio': 0.5986029990983353}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,196] Trial 109 finished with value: 0.010065419044590877 and parameters: {'alpha': 34.9651164908574, 'l1_ratio': 0.11184407136435123}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,204] Trial 110 finished with value: 0.010065419044590877 and parameters: {'alpha': 2.224158752178372, 'l1_ratio': 0.5221919392263715}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,212] Trial 111 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.013560178237231385, 'l1_ratio': 0.5658569824092561}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,221] Trial 112 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.028690728500093923, 'l1_ratio': 0.504994263032546}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,229] Trial 113 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.007688524595940879, 'l1_ratio': 0.41172781299698824}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,237] Trial 114 finished with value: 0.010110344273408855 and parameters: {'alpha': 0.002005237457064511, 'l1_ratio': 0.4623877161398798}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,246] Trial 115 finished with value: 0.010065419044590877 and parameters: {'alpha': 0.06846852584416128, 'l1_ratio': 0.6552749816862975}. Best is trial 54 with value: 0.010065248100962834.
[I 2026-10-14 15:42:04,255] Trial 116 finished with value: 0.010064992095961477 and parameters: {'alpha': 0.004026912421751181, 'l1_ratio': 0.4887810912837162}. Best is trial 116 with value: 0.010064992095961477.
[I 2026-10-14 15:42:04,263] Trial 117 finished with value: 0.010082385630171284 and parameters: {'alpha': 0.0042457812647827215, 'l1_ratio': 0.27572689493840263}. Best is trial 116 with value: 0.010064992095961477.

[-0.         -0.         -0.         -0.         -0.         -0.
  0.00012495  0.         -0.          0.          0.        ]
30

[I 2026-10-14 15:42:05,671] Trial 28 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.012512079810648486, 'l1_ratio': 0.6227293620503137}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,681] Trial 29 finished with value: 0.006606445422697391 and parameters: {'alpha': 1.249492457159205e-07, 'l1_ratio': 0.41678652728652643}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,689] Trial 30 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.06574000126004799, 'l1_ratio': 0.07584999015735006}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,697] Trial 31 finished with value: 0.00644514643148634 and parameters: {'alpha': 11.770198472490664, 'l1_ratio': 0.07048829303354494}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,705] Trial 32 finished with value: 0.00644514643148634 and parameters: {'alpha': 1.88128351003044, 'l1_ratio': 0.24195744975947422}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,712] Trial 33 finished with value: 0.00644514643148634 and parameters: {'alpha': 20.176834699664113, 'l1_ratio': 0.05311243385202921}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,721] Trial 34 finished with value: 0.006469364654152094 and parameters: {'alpha': 0.004617887588937693, 'l1_ratio': 0.15802842987896415}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,728] Trial 35 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.25406773205822675, 'l1_ratio': 0.33117807375229746}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,737] Trial 36 finished with value: 0.0066064023739890974 and parameters: {'alpha': 8.660751147885523e-07, 'l1_ratio': 0.23947684748860745}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,746] Trial 37 finished with value: 0.00644514643148634 and parameters: {'alpha': 3.109217993782552, 'l1_ratio': 0.11295606545038042}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,756] Trial 38 finished with value: 0.006483313507909373 and parameters: {'alpha': 0.0015258666342060378, 'l1_ratio': 0.43169477813614243}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,767] Trial 39 finished with value: 0.006606458872260951 and parameters: {'alpha': 1.0866921623259124e-10, 'l1_ratio': 0.30525887282215247}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,778] Trial 40 finished with value: 0.0065813513006756814 and parameters: {'alpha': 0.00015516975760290912, 'l1_ratio': 0.6715761661145068}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,788] Trial 41 finished with value: 0.00644514643148634 and parameters: {'alpha': 19.144625499916984, 'l1_ratio': 0.2888492613306236}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,796] Trial 42 finished with value: 0.00644514643148634 and parameters: {'alpha': 5.033003807154426, 'l1_ratio': 0.5467871155661242}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,804] Trial 43 finished with value: 0.006431841532972135 and parameters: {'alpha': 0.030413205878552563, 'l1_ratio': 0.03954907558452981}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,812] Trial 44 finished with value: 0.006449495517684916 and parameters: {'alpha': 0.020914833490721117, 'l1_ratio': 0.03715641958986908}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,821] Trial 45 finished with value: 0.006605830549406806 and parameters: {'alpha': 2.0804179164211034e-05, 'l1_ratio': 0.09335013818029181}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,829] Trial 46 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.04219696159377409, 'l1_ratio': 0.16388684372346368}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,837] Trial 47 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.24679978009099152, 'l1_ratio': 0.9069197459736229}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,846] Trial 48 finished with value: 0.0065943975998689775 and parameters: {'alpha': 0.0011673524853241329, 'l1_ratio': 0.012273330950339476}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,854] Trial 49 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.7187798254828823, 'l1_ratio': 0.13140623632429813}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,863] Trial 50 finished with value: 0.006529810240498688 and parameters: {'alpha': 0.004071508929077764, 'l1_ratio': 0.0654489939912378}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,871] Trial 51 finished with value: 0.00644514643148634 and parameters: {'alpha': 49.28500620958451, 'l1_ratio': 0.21387035254520992}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,878] Trial 52 finished with value: 0.00644514643148634 and parameters: {'alpha': 31.164008064526687, 'l1_ratio': 0.19426274941665989}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,885] Trial 53 finished with value: 0.00644514643148634 and parameters: {'alpha': 4.872710158521481, 'l1_ratio': 0.2710418415454385}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,892] Trial 54 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.13234387459558114, 'l1_ratio': 0.35346878240444474}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,902] Trial 55 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.9564211667042155, 'l1_ratio': 0.027107918484086564}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,910] Trial 56 finished with value: 0.00644514643148634 and parameters: {'alpha': 7.42600506060281, 'l1_ratio': 0.758561845777889}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,917] Trial 57 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.042161617117897156, 'l1_ratio': 0.13439098128801705}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,924] Trial 58 finished with value: 0.00644514643148634 and parameters: {'alpha': 2.051802352888259, 'l1_ratio': 0.45687867880370503}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,932] Trial 59 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.4268062985955482, 'l1_ratio': 0.1003054254888599}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,940] Trial 60 finished with value: 0.00644514643148634 and parameters: {'alpha': 99.29191178113167, 'l1_ratio': 0.5834322193601907}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,947] Trial 61 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.10803822244890712, 'l1_ratio': 0.5693989129753946}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,957] Trial 62 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.004909335933274216, 'l1_ratio': 0.48724846382177517}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,966] Trial 63 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.021978312671022467, 'l1_ratio': 0.6394836598264987}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,974] Trial 64 finished with value: 0.006586628684309341 and parameters: {'alpha': 0.00034208557283238954, 'l1_ratio': 0.21756112633438524}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,981] Trial 65 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.01063136002833168, 'l1_ratio': 0.5252795074363167}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,989] Trial 66 finished with value: 0.00644514643148634 and parameters: {'alpha': 11.299918839706999, 'l1_ratio': 0.15018767459269458}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:05,997] Trial 67 finished with value: 0.006458184154046854 and parameters: {'alpha': 0.07661901978025441, 'l1_ratio': 0.0004981732304808681}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,006] Trial 68 finished with value: 0.006593784494106822 and parameters: {'alpha': 0.0006552140328616596, 'l1_ratio': 0.05031065038227167}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,014] Trial 69 finished with value: 0.00644514643148634 and parameters: {'alpha': 1.54889890347135, 'l1_ratio': 0.7009134771030892}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,022] Trial 70 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.31039043175548015, 'l1_ratio': 0.18283949289969612}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,031] Trial 71 finished with value: 0.006537341990448688 and parameters: {'alpha': 0.0028085069399214086, 'l1_ratio': 0.09027339122003439}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,040] Trial 72 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.026046667893959603, 'l1_ratio': 0.24822059961048287}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,049] Trial 73 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.006845801973429882, 'l1_ratio': 0.38692960736873416}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,058] Trial 74 finished with value: 0.00644514643148634 and parameters: {'alpha': 33.78152855277355, 'l1_ratio': 0.20816810798620677}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,070] Trial 75 finished with value: 0.006606458345133532 and parameters: {'alpha': 7.220360330523113e-09, 'l1_ratio': 0.27693120241178143}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,077] Trial 76 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.14739666430232162, 'l1_ratio': 0.322715145075404}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,086] Trial 77 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.04010834966389469, 'l1_ratio': 0.4437011348756146}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,093] Trial 78 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.718063097276323, 'l1_ratio': 0.47262217597312467}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,103] Trial 79 finished with value: 0.00644514643148634 and parameters: {'alpha': 3.984956020406535, 'l1_ratio': 0.07291738690541605}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,111] Trial 80 finished with value: 0.0064530138847325455 and parameters: {'alpha': 0.0015522021382814637, 'l1_ratio': 0.6114251418915507}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,120] Trial 81 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.19984352543722617, 'l1_ratio': 0.8285973114357633}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,129] Trial 82 finished with value: 0.00644514643148634 and parameters: {'alpha': 18.91770127439267, 'l1_ratio': 0.12971734506456806}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,139] Trial 83 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.012640938587407934, 'l1_ratio': 0.7613305818636915}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,148] Trial 84 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.051898953265766865, 'l1_ratio': 0.04356625089635316}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,155] Trial 85 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.4038417731789966, 'l1_ratio': 0.9979225347872416}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,164] Trial 86 finished with value: 0.00644514643148634 and parameters: {'alpha': 2.9944497347529704, 'l1_ratio': 0.899060231946691}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,172] Trial 87 finished with value: 0.00644514643148634 and parameters: {'alpha': 1.450145223891633, 'l1_ratio': 0.1785183689803684}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,181] Trial 88 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.0888972637152033, 'l1_ratio': 0.8655300097302348}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,190] Trial 89 finished with value: 0.0064362740202549345 and parameters: {'alpha': 0.0074284140893927835, 'l1_ratio': 0.15068097632578556}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,200] Trial 90 finished with value: 0.006601756238704975 and parameters: {'alpha': 0.00010554849589835584, 'l1_ratio': 0.15443483311508374}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,208] Trial 91 finished with value: 0.0065248324016508215 and parameters: {'alpha': 0.002977676739676875, 'l1_ratio': 0.1084849818224259}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,217] Trial 92 finished with value: 0.006558139444899327 and parameters: {'alpha': 0.0008609697563405244, 'l1_ratio': 0.2258847133610109}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,225] Trial 93 finished with value: 0.006470963415544407 and parameters: {'alpha': 0.008945993319421149, 'l1_ratio': 0.07164809447047274}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,233] Trial 94 finished with value: 0.006462800611657841 and parameters: {'alpha': 0.022945656710842078, 'l1_ratio': 0.02334166331310722}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,242] Trial 95 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.006123105076144749, 'l1_ratio': 0.40643070439624984}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,250] Trial 96 finished with value: 0.00644514643148634 and parameters: {'alpha': 38.851832788708734, 'l1_ratio': 0.3554668065733545}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,257] Trial 97 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.03257271003446295, 'l1_ratio': 0.1380021693813404}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,265] Trial 98 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.08539145461252454, 'l1_ratio': 0.20083255085161011}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,273] Trial 99 finished with value: 0.00644514643148634 and parameters: {'alpha': 9.674613315325283, 'l1_ratio': 0.9535336864793419}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,281] Trial 100 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.018400399616157668, 'l1_ratio': 0.7873578757361586}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,288] Trial 101 finished with value: 0.00644514643148634 and parameters: {'alpha': 6.527062572966322, 'l1_ratio': 0.5257484431264678}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,296] Trial 102 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.8000106528205834, 'l1_ratio': 0.6799133568954447}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,304] Trial 103 finished with value: 0.00644514643148634 and parameters: {'alpha': 16.917463474326127, 'l1_ratio': 0.5174745299265792}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,313] Trial 104 finished with value: 0.00644514643148634 and parameters: {'alpha': 55.36341419482209, 'l1_ratio': 0.3009638092367271}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,320] Trial 105 finished with value: 0.00644514643148634 and parameters: {'alpha': 2.034924609008955, 'l1_ratio': 0.17285663481514973}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,328] Trial 106 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.2113368993165353, 'l1_ratio': 0.10208665179583219}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,336] Trial 107 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.64534624431534, 'l1_ratio': 0.5475714618876499}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,344] Trial 108 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.0509955363554787, 'l1_ratio': 0.49733803834594414}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,351] Trial 109 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.17264261791027977, 'l1_ratio': 0.08788650294231731}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,360] Trial 110 finished with value: 0.0065720672465140045 and parameters: {'alpha': 0.0019675031914619698, 'l1_ratio': 0.04765405291150554}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,370] Trial 111 finished with value: 0.00644514643148634 and parameters: {'alpha': 62.66101745447645, 'l1_ratio': 0.27155472943990755}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,378] Trial 112 finished with value: 0.00644514643148634 and parameters: {'alpha': 27.403098855173027, 'l1_ratio': 0.23124475752157192}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,386] Trial 113 finished with value: 0.00644514643148634 and parameters: {'alpha': 3.245375176404143, 'l1_ratio': 0.5926355396474973}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,395] Trial 114 finished with value: 0.00644514643148634 and parameters: {'alpha': 10.749191897187107, 'l1_ratio': 0.2542539075820508}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,403] Trial 115 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.013807786980605141, 'l1_ratio': 0.19211323233845667}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,413] Trial 116 finished with value: 0.00644514643148634 and parameters: {'alpha': 76.1807805346006, 'l1_ratio': 0.14495569398615393}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,422] Trial 117 finished with value: 0.00644514643148634 and parameters: {'alpha': 1.214090003545942, 'l1_ratio': 0.11921984832901286}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,432] Trial 118 finished with value: 0.00644514643148634 and parameters: {'alpha': 19.81392888792292, 'l1_ratio': 0.16369328092289248}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,441] Trial 119 finished with value: 0.00644514643148634 and parameters: {'alpha': 6.771187865060003, 'l1_ratio': 0.4275910597317432}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,451] Trial 120 finished with value: 0.006548464286472434 and parameters: {'alpha': 0.005721945012651364, 'l1_ratio': 0.02034843875210083}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,461] Trial 121 finished with value: 0.00644514643148634 and parameters: {'alpha': 0.013986284993713146, 'l1_ratio': 0.403304234341699}. Best is trial 23 with value: 0.006428875640008897.
[I 2026-10-14 15:42:06,470] Trial 122 finished with value: 0.0064385236154497726 and parameters: {'alpha': 0.004294880709919049, 'l1_ratio': 0.4705315633066457}. Best is trial 23 with value: 0.006428875640008897.

[ 0.         -0.         -0.         -0.00061705 -0.         -0.
  0.00685625  0.         -0.          0.          0.        ]
36

[I 2026-10-14 15:42:07,896] Trial 25 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.0745016699580072, 'l1_ratio': 0.7635456457783985}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,905] Trial 26 finished with value: 0.007783240394526452 and parameters: {'alpha': 16.374160784635066, 'l1_ratio': 0.5536442102022929}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,914] Trial 27 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.937548418239027, 'l1_ratio': 0.2619746827922179}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,923] Trial 28 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.002678308793332769, 'l1_ratio': 0.9029497535779158}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,931] Trial 29 finished with value: 0.007783240394526452 and parameters: {'alpha': 25.00536423330711, 'l1_ratio': 0.05330576175766377}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,939] Trial 30 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.13938089958123315, 'l1_ratio': 0.01623416158176305}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,948] Trial 31 finished with value: 0.007783240394526452 and parameters: {'alpha': 92.39987618824318, 'l1_ratio': 0.21111440575537213}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,955] Trial 32 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.3548671768862328, 'l1_ratio': 0.14546773125988088}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,963] Trial 33 finished with value: 0.007783240394526452 and parameters: {'alpha': 34.70611620129978, 'l1_ratio': 0.31276380102825607}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,975] Trial 34 finished with value: 0.008020258353357332 and parameters: {'alpha': 6.892408771619602e-09, 'l1_ratio': 0.4060908295664021}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:07,987] Trial 35 finished with value: 0.007783240394526452 and parameters: {'alpha': 12.095070513363575, 'l1_ratio': 0.21717839235718936}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,000] Trial 36 finished with value: 0.008020259092542515 and parameters: {'alpha': 1.2210552595130377e-10, 'l1_ratio': 0.28052603813235116}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,008] Trial 37 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.7716160042212907, 'l1_ratio': 0.5840045046325762}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,016] Trial 38 finished with value: 0.007982788336051856 and parameters: {'alpha': 0.00016860541464286407, 'l1_ratio': 0.8238386426943373}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,025] Trial 39 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.33536846551358, 'l1_ratio': 0.4625875081385201}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,033] Trial 40 finished with value: 0.007783240394526452 and parameters: {'alpha': 33.04571567574681, 'l1_ratio': 0.7113841458515663}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,041] Trial 41 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.4305401093767658, 'l1_ratio': 0.40024327395482895}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,048] Trial 42 finished with value: 0.007783240394526452 and parameters: {'alpha': 2.656937795442252, 'l1_ratio': 0.34078103885425814}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,056] Trial 43 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.11638851512497565, 'l1_ratio': 0.1441949226364884}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,063] Trial 44 finished with value: 0.007783240394526452 and parameters: {'alpha': 7.762075343606897, 'l1_ratio': 0.96004725104375}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,071] Trial 45 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.028022383740852176, 'l1_ratio': 0.25413711859563154}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,078] Trial 46 finished with value: 0.007783240394526452 and parameters: {'alpha': 95.58527717148172, 'l1_ratio': 0.16094803197677784}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,085] Trial 47 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.40873146090760837, 'l1_ratio': 0.08160803025017355}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,092] Trial 48 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.006472813674479025, 'l1_ratio': 0.36582541919594}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,099] Trial 49 finished with value: 0.007783240394526452 and parameters: {'alpha': 23.56198948180758, 'l1_ratio': 0.49148429200893257}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,108] Trial 50 finished with value: 0.008007268329138813 and parameters: {'alpha': 7.926695633786755e-05, 'l1_ratio': 0.6181497714404995}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,117] Trial 51 finished with value: 0.007783240394526452 and parameters: {'alpha': 3.0519077739715925, 'l1_ratio': 0.9779126391631141}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,125] Trial 52 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.7954166571765735, 'l1_ratio': 0.9376069532215497}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,134] Trial 53 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.1508849928196105, 'l1_ratio': 0.9965880013929864}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,143] Trial 54 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.00843031621293098, 'l1_ratio': 0.806090257768828}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,150] Trial 55 finished with value: 0.007783240394526452 and parameters: {'alpha': 4.496256221978184, 'l1_ratio': 0.8971392821012397}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,158] Trial 56 finished with value: 0.007783240394526452 and parameters: {'alpha': 13.997572453714923, 'l1_ratio': 0.8656953363681862}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,166] Trial 57 finished with value: 0.007783240394526452 and parameters: {'alpha': 29.004418907374838, 'l1_ratio': 0.9427764501772654}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,174] Trial 58 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.06492969025490324, 'l1_ratio': 0.7569053829176193}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,181] Trial 59 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.955346156968616, 'l1_ratio': 0.1847633413222116}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,192] Trial 60 finished with value: 0.008020199809966952 and parameters: {'alpha': 2.5171480734988505e-07, 'l1_ratio': 0.9170137418149311}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,199] Trial 61 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.48772027201272244, 'l1_ratio': 0.2962320061771312}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,206] Trial 62 finished with value: 0.007783240394526452 and parameters: {'alpha': 3.236039808064418, 'l1_ratio': 0.24000908560460682}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,214] Trial 63 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.20520470019968115, 'l1_ratio': 0.12073862036180677}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,222] Trial 64 finished with value: 0.007783240394526452 and parameters: {'alpha': 7.814206073530424, 'l1_ratio': 0.33673305094486805}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,231] Trial 65 finished with value: 0.007783240394526452 and parameters: {'alpha': 60.32697717053395, 'l1_ratio': 0.42132231036788326}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,238] Trial 66 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.016028285055718825, 'l1_ratio': 0.6696489725005712}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,246] Trial 67 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.05013701502231808, 'l1_ratio': 0.9982032928644446}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,254] Trial 68 finished with value: 0.007799731925422671 and parameters: {'alpha': 0.0017707072898572674, 'l1_ratio': 0.8617203853348216}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,263] Trial 69 finished with value: 0.007783240394526452 and parameters: {'alpha': 47.14473458199731, 'l1_ratio': 0.5417445823240372}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,272] Trial 70 finished with value: 0.007783240394526452 and parameters: {'alpha': 12.923307742375659, 'l1_ratio': 0.37205507943058336}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,280] Trial 71 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.1940240172167171, 'l1_ratio': 0.20038586237705883}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,287] Trial 72 finished with value: 0.007783240394526452 and parameters: {'alpha': 4.641243448658095, 'l1_ratio': 0.2872904971200959}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,296] Trial 73 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.5508210035277605, 'l1_ratio': 0.23839426552440035}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,304] Trial 74 finished with value: 0.007783240394526452 and parameters: {'alpha': 20.470326527615416, 'l1_ratio': 0.1694613873390481}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,314] Trial 75 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.2623850124411982, 'l1_ratio': 0.05978793523146131}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,322] Trial 76 finished with value: 0.007783240394526452 and parameters: {'alpha': 6.028214616822259, 'l1_ratio': 0.3177498805460542}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,329] Trial 77 finished with value: 0.007783240394526452 and parameters: {'alpha': 47.21791250568504, 'l1_ratio': 0.2213727562897027}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,337] Trial 78 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.6222487376023671, 'l1_ratio': 0.2688014632981108}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,345] Trial 79 finished with value: 0.007783240394526452 and parameters: {'alpha': 2.7186423660016543, 'l1_ratio': 0.9668394502115871}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,352] Trial 80 finished with value: 0.007783240394526452 and parameters: {'alpha': 11.350898121908752, 'l1_ratio': 0.12196896312520816}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,364] Trial 81 finished with value: 0.007985825804927602 and parameters: {'alpha': 0.00027284805678310015, 'l1_ratio': 0.45615108062134524}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,372] Trial 82 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.014079706319983586, 'l1_ratio': 0.3649151664083071}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,382] Trial 83 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.0906371137265098, 'l1_ratio': 0.9259543625719194}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,390] Trial 84 finished with value: 0.007783240394526452 and parameters: {'alpha': 90.58138035430419, 'l1_ratio': 0.49684153171483664}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,398] Trial 85 finished with value: 0.007812018340560163 and parameters: {'alpha': 0.004232950063190273, 'l1_ratio': 0.30669681950255523}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,406] Trial 86 finished with value: 0.00789666283375286 and parameters: {'alpha': 0.0007318090523814778, 'l1_ratio': 0.7958504348032496}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,414] Trial 87 finished with value: 0.007783240394526452 and parameters: {'alpha': 25.06712706009444, 'l1_ratio': 0.4017934709499761}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,423] Trial 88 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.9939006114688336, 'l1_ratio': 0.6245297911264399}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,431] Trial 89 finished with value: 0.007783240394526452 and parameters: {'alpha': 7.435550085770111, 'l1_ratio': 0.7124598308260555}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,439] Trial 90 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.042720483878250864, 'l1_ratio': 0.18897778367624968}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,448] Trial 91 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.021561725027340037, 'l1_ratio': 0.9605016670368655}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,459] Trial 92 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.1814691395691561, 'l1_ratio': 0.8780149291509066}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,468] Trial 93 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.008368318550322275, 'l1_ratio': 0.8478521932652454}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,476] Trial 94 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.5262295884347271, 'l1_ratio': 0.34293620996023216}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,485] Trial 95 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.10837588782345166, 'l1_ratio': 0.9160063530423903}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,497] Trial 96 finished with value: 0.008019484365502443 and parameters: {'alpha': 1.088644134886364e-05, 'l1_ratio': 0.25600795985026037}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,505] Trial 97 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.0976902703772535, 'l1_ratio': 0.8941510747983594}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,513] Trial 98 finished with value: 0.007783240394526452 and parameters: {'alpha': 38.744758119818925, 'l1_ratio': 0.42767078735521863}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,523] Trial 99 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.28374907744988226, 'l1_ratio': 0.974216227491074}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,531] Trial 100 finished with value: 0.00787804028155355 and parameters: {'alpha': 0.0008613182889942411, 'l1_ratio': 0.8179976280241321}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,539] Trial 101 finished with value: 0.007783240394526452 and parameters: {'alpha': 14.116585789367948, 'l1_ratio': 0.7767239319854496}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,550] Trial 102 finished with value: 0.007783240394526452 and parameters: {'alpha': 58.20249867133784, 'l1_ratio': 0.9424808492203248}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,558] Trial 103 finished with value: 0.007783240394526452 and parameters: {'alpha': 99.27009701808888, 'l1_ratio': 0.8819671917872136}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,566] Trial 104 finished with value: 0.007783240394526452 and parameters: {'alpha': 5.2104843511276915, 'l1_ratio': 0.846479298826514}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,575] Trial 105 finished with value: 0.007783240394526452 and parameters: {'alpha': 28.293385519234405, 'l1_ratio': 0.1534309229378663}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,585] Trial 106 finished with value: 0.007783240394526452 and parameters: {'alpha': 2.901238157374991, 'l1_ratio': 0.22552802355662904}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,593] Trial 107 finished with value: 0.007783240394526452 and parameters: {'alpha': 11.71364612608124, 'l1_ratio': 0.3787179647850732}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,601] Trial 108 finished with value: 0.007783240394526452 and parameters: {'alpha': 16.343696760557034, 'l1_ratio': 0.997500298895282}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,610] Trial 109 finished with value: 0.007866119804600735 and parameters: {'alpha': 0.002711758662537617, 'l1_ratio': 0.2806251306769565}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,621] Trial 110 finished with value: 0.00802025866117816 and parameters: {'alpha': 4.954762567005774e-09, 'l1_ratio': 0.3269907783604455}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,628] Trial 111 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.6513599192698836, 'l1_ratio': 0.5098263909283727}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,637] Trial 112 finished with value: 0.007783240394526452 and parameters: {'alpha': 1.5977265363597006, 'l1_ratio': 0.5381835283232111}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,644] Trial 113 finished with value: 0.007783240394526452 and parameters: {'alpha': 4.180205919665076, 'l1_ratio': 0.44932686605832606}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,653] Trial 114 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.0583790894271726, 'l1_ratio': 0.43772214389556346}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,661] Trial 115 finished with value: 0.007783240394526452 and parameters: {'alpha': 55.61813806874437, 'l1_ratio': 0.3524136202368445}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,669] Trial 116 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.02612534172531072, 'l1_ratio': 0.9073545243935454}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,677] Trial 117 finished with value: 0.007783240394526452 and parameters: {'alpha': 21.638324721934165, 'l1_ratio': 0.38705534461964775}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,685] Trial 118 finished with value: 0.007783240394526452 and parameters: {'alpha': 0.886826313742597, 'l1_ratio': 0.17526061005894134}. Best is trial 4 with value: 0.007783240394526452.
[I 2026-10-14 15:42:08,692] Trial 119 finished with value: 0.007783240394526452 and parameters: {'alpha': 7.3255366345253226, 'l1_ratio': 0.4755832320533247}. Best is trial 4 with value: 0.007783240394526452.

[-0. -0. -0. -0. -0. -0.  0.  0. -0.  0.  0.]
42

[I 2026-10-14 15:42:10,085] Trial 23 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.05987109804802056, 'l1_ratio': 0.6931731807368985}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,095] Trial 24 finished with value: 0.013992765423100934 and parameters: {'alpha': 6.702506828710783, 'l1_ratio': 0.4902608319161779}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,103] Trial 25 finished with value: 0.014066458333332496 and parameters: {'alpha': 0.00022243226839110624, 'l1_ratio': 0.8629003362586096}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,112] Trial 26 finished with value: 0.014106793013972645 and parameters: {'alpha': 2.746800524200387e-06, 'l1_ratio': 0.26949359141045387}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,119] Trial 27 finished with value: 0.01399408613102936 and parameters: {'alpha': 0.018027533590861285, 'l1_ratio': 0.0708891967693106}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,128] Trial 28 finished with value: 0.013992765423100934 and parameters: {'alpha': 79.61859705690108, 'l1_ratio': 0.6756743433108543}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,136] Trial 29 finished with value: 0.013992765423100934 and parameters: {'alpha': 1.266688376329341, 'l1_ratio': 0.41207643103461594}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,143] Trial 30 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.14268076840802182, 'l1_ratio': 0.7594536129743235}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,151] Trial 31 finished with value: 0.013992765423100934 and parameters: {'alpha': 20.664578367454872, 'l1_ratio': 0.5705684458150172}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,158] Trial 32 finished with value: 0.013992765423100934 and parameters: {'alpha': 20.740309874623666, 'l1_ratio': 0.6071628704473127}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,164] Trial 33 finished with value: 0.013992765423100934 and parameters: {'alpha': 2.2294801443463044, 'l1_ratio': 0.8950241887987987}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,173] Trial 34 finished with value: 0.013998158124300747 and parameters: {'alpha': 0.001467376154556499, 'l1_ratio': 0.7759811319527027}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,182] Trial 35 finished with value: 0.014097479180633848 and parameters: {'alpha': 0.00017332916891893175, 'l1_ratio': 0.20513596139528975}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,190] Trial 36 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.02461221399195389, 'l1_ratio': 0.3127424816036927}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,198] Trial 37 finished with value: 0.013992765423100934 and parameters: {'alpha': 13.896345752456236, 'l1_ratio': 0.396187643725319}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,206] Trial 38 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.21042261971949142, 'l1_ratio': 0.9058015571507632}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,214] Trial 39 finished with value: 0.013992765423100934 and parameters: {'alpha': 70.18150072935357, 'l1_ratio': 0.6346426317918612}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,226] Trial 40 finished with value: 0.014106989830691113 and parameters: {'alpha': 4.408761991217815e-09, 'l1_ratio': 0.5523777446368726}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,234] Trial 41 finished with value: 0.013992765423100934 and parameters: {'alpha': 49.33454750035332, 'l1_ratio': 0.11239053192869741}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,243] Trial 42 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.970638890975195, 'l1_ratio': 0.17528948365704936}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,254] Trial 43 finished with value: 0.013992765423100934 and parameters: {'alpha': 10.790211840519378, 'l1_ratio': 0.24006583420001626}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,263] Trial 44 finished with value: 0.014029667658016694 and parameters: {'alpha': 0.005673099008503105, 'l1_ratio': 0.060270231867014024}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,271] Trial 45 finished with value: 0.013992765423100934 and parameters: {'alpha': 92.62617746117367, 'l1_ratio': 0.32076562337900627}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,278] Trial 46 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.5285050773167123, 'l1_ratio': 0.12398349659118732}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,289] Trial 47 finished with value: 0.014106901080646122 and parameters: {'alpha': 7.889967072035175e-07, 'l1_ratio': 0.44104156072727907}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,297] Trial 48 finished with value: 0.013992765423100934 and parameters: {'alpha': 3.502759538985284, 'l1_ratio': 0.013045057303231244}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,305] Trial 49 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.03126981320692356, 'l1_ratio': 0.2116873938624418}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,314] Trial 50 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.4056812151214543, 'l1_ratio': 0.9895715593623825}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,322] Trial 51 finished with value: 0.013992765423100934 and parameters: {'alpha': 24.885419623864696, 'l1_ratio': 0.16701670227264176}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,330] Trial 52 finished with value: 0.013992765423100934 and parameters: {'alpha': 2.095383696294439, 'l1_ratio': 0.3558382128384877}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,339] Trial 53 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.24114533791093368, 'l1_ratio': 0.25655860499886396}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,347] Trial 54 finished with value: 0.013997649497519629 and parameters: {'alpha': 0.005244061853171331, 'l1_ratio': 0.20965165732441168}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,355] Trial 55 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.06585178738129735, 'l1_ratio': 0.08468599572261232}. Best is trial 1 with value: 0.013992765423100934.
[I 2026-10-14 15:42:10,364] Trial 56 finished with value: 0.013992743735405606 and parameters: {'alpha': 0.01320615907138665, 'l1_ratio': 0.15176532203434345}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,373] Trial 57 finished with value: 0.014082767028803223 and parameters: {'alpha': 0.0006597497241396683, 'l1_ratio': 0.13575864144340627}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,383] Trial 58 finished with value: 0.014082505750739487 and parameters: {'alpha': 0.00019961689023986767, 'l1_ratio': 0.5168123029978564}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,393] Trial 59 finished with value: 0.014106619516332493 and parameters: {'alpha': 1.9503707945799513e-05, 'l1_ratio': 0.05028405745473699}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,401] Trial 60 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.012143129502334144, 'l1_ratio': 0.2968165966126818}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,410] Trial 61 finished with value: 0.013992765423100934 and parameters: {'alpha': 5.946162098575836, 'l1_ratio': 0.16261647767236953}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,417] Trial 62 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.06830378715635456, 'l1_ratio': 0.23508062746348635}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,425] Trial 63 finished with value: 0.014052190549073057 and parameters: {'alpha': 0.002375514809509174, 'l1_ratio': 0.09602624684996111}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,433] Trial 64 finished with value: 0.013992765423100934 and parameters: {'alpha': 32.00513964631715, 'l1_ratio': 0.2822500035797177}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,441] Trial 65 finished with value: 0.013992765423100934 and parameters: {'alpha': 8.40723387549823, 'l1_ratio': 0.7604826181329152}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,449] Trial 66 finished with value: 0.013992765423100934 and parameters: {'alpha': 1.2024044194872114, 'l1_ratio': 0.18659987726825455}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,456] Trial 67 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.040612123331436316, 'l1_ratio': 0.35138523156302426}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,464] Trial 68 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.012603214057291876, 'l1_ratio': 0.7960356826316066}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,475] Trial 69 finished with value: 0.014106990430348954 and parameters: {'alpha': 1.0209058401608039e-10, 'l1_ratio': 0.7110606478200836}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,484] Trial 70 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.30605916649973763, 'l1_ratio': 0.1418675908012902}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,491] Trial 71 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.1320547162221615, 'l1_ratio': 0.6445398693627424}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,499] Trial 72 finished with value: 0.013992765423100934 and parameters: {'alpha': 2.274147438173525, 'l1_ratio': 0.4566202860777106}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,507] Trial 73 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.5957903629443181, 'l1_ratio': 0.5286056220817779}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,517] Trial 74 finished with value: 0.013992765423100934 and parameters: {'alpha': 10.201071286506522, 'l1_ratio': 0.2331930134889123}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,525] Trial 75 finished with value: 0.013992765423100934 and parameters: {'alpha': 32.4976672335581, 'l1_ratio': 0.3270223574334822}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,533] Trial 76 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.009744780094277025, 'l1_ratio': 0.9235401158369767}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,541] Trial 77 finished with value: 0.0140050160576763 and parameters: {'alpha': 0.002134095901297873, 'l1_ratio': 0.4108981413169602}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,550] Trial 78 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.1326583097093428, 'l1_ratio': 0.8444943824200626}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,557] Trial 79 finished with value: 0.013992765423100934 and parameters: {'alpha': 4.520347997267671, 'l1_ratio': 0.3798710473867252}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,566] Trial 80 finished with value: 0.013992765423100934 and parameters: {'alpha': 49.176316928827326, 'l1_ratio': 0.2743483779476381}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,574] Trial 81 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.873807103652671, 'l1_ratio': 0.10622812892957076}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,582] Trial 82 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.03737812338897513, 'l1_ratio': 0.18341864371338662}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,590] Trial 83 finished with value: 0.013992765423100934 and parameters: {'alpha': 15.999762571795106, 'l1_ratio': 0.04764050448615781}. Best is trial 56 with value: 0.013992743735405606.
[I 2026-10-14 15:42:10,600] Trial 84 finished with value: 0.013990999275512485 and parameters: {'alpha': 0.2400839522178205, 'l1_ratio': 0.005037550973176985}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,611] Trial 85 finished with value: 0.013992765423100934 and parameters: {'alpha': 2.1241380462930897, 'l1_ratio': 0.20051947211527596}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,621] Trial 86 finished with value: 0.014063133255498295 and parameters: {'alpha': 0.00421064889619913, 'l1_ratio': 0.024886629717043092}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,633] Trial 87 finished with value: 0.013992765423100934 and parameters: {'alpha': 96.57156861580275, 'l1_ratio': 0.13509404165260636}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,642] Trial 88 finished with value: 0.013993470990432702 and parameters: {'alpha': 0.02138789501360217, 'l1_ratio': 0.07462198323168351}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,653] Trial 89 finished with value: 0.014106277074290657 and parameters: {'alpha': 7.494632218502234e-05, 'l1_ratio': 0.010939421635835663}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,663] Trial 90 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.0819721317741622, 'l1_ratio': 0.5908025653889631}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,672] Trial 91 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.20715628654894538, 'l1_ratio': 0.11403750280480138}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,681] Trial 92 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.6297324950045489, 'l1_ratio': 0.15862562830812466}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,690] Trial 93 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.24269050695814773, 'l1_ratio': 0.23119878698695137}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,699] Trial 94 finished with value: 0.013992765423100934 and parameters: {'alpha': 3.4070697285524165, 'l1_ratio': 0.2594946147128734}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,708] Trial 95 finished with value: 0.013992765423100934 and parameters: {'alpha': 1.4759063512460227, 'l1_ratio': 0.09377489482241283}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,719] Trial 96 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.5116076031167237, 'l1_ratio': 0.21873184932126283}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,728] Trial 97 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.045858093267168526, 'l1_ratio': 0.30062039988230216}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,737] Trial 98 finished with value: 0.013993915359588464 and parameters: {'alpha': 0.018372256909532588, 'l1_ratio': 0.07252189737264814}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,746] Trial 99 finished with value: 0.013992765423100934 and parameters: {'alpha': 51.56026781291277, 'l1_ratio': 0.03575421859372338}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,756] Trial 100 finished with value: 0.013992765423100934 and parameters: {'alpha': 7.349985460173245, 'l1_ratio': 0.14635870407932786}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,767] Trial 101 finished with value: 0.014022628502697067 and parameters: {'alpha': 0.0012459357572284745, 'l1_ratio': 0.4433246038668716}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,776] Trial 102 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.005509905803789691, 'l1_ratio': 0.48712606475563286}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,784] Trial 103 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.007785394591030305, 'l1_ratio': 0.5509076550914541}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,792] Trial 104 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.11713391127213243, 'l1_ratio': 0.48814485698834853}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,801] Trial 105 finished with value: 0.014055639172200901 and parameters: {'alpha': 0.00038418931251052565, 'l1_ratio': 0.670733890756801}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,810] Trial 106 finished with value: 0.013992765423100934 and parameters: {'alpha': 17.124137714203773, 'l1_ratio': 0.1987259594983115}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,820] Trial 107 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.029802253989341908, 'l1_ratio': 0.7281318076383941}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,828] Trial 108 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.06624110246763203, 'l1_ratio': 0.46513643194597337}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,840] Trial 109 finished with value: 0.014106988486395845 and parameters: {'alpha': 2.2468223103660807e-08, 'l1_ratio': 0.3334075355813664}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,849] Trial 110 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.3425560690925233, 'l1_ratio': 0.617478626692517}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,858] Trial 111 finished with value: 0.013992765423100934 and parameters: {'alpha': 25.645328858327442, 'l1_ratio': 0.2494548779846737}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,867] Trial 112 finished with value: 0.013992765423100934 and parameters: {'alpha': 4.000871255614794, 'l1_ratio': 0.367287040385198}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,875] Trial 113 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.8146200708365319, 'l1_ratio': 0.17713024893353813}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,883] Trial 114 finished with value: 0.013992765423100934 and parameters: {'alpha': 1.5053205880284724, 'l1_ratio': 0.27543124527588275}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,892] Trial 115 finished with value: 0.013992765423100934 and parameters: {'alpha': 44.87140831980691, 'l1_ratio': 0.31342874279779165}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,901] Trial 116 finished with value: 0.013992765423100934 and parameters: {'alpha': 9.584745628563187, 'l1_ratio': 0.41749944352132307}. Best is trial 84 with value: 0.013990999275512485.
[I 2026-10-14 15:42:10,910] Trial 117 finished with value: 0.013992765423100934 and parameters: {'alpha': 0.19213302148435166, 'l1_ratio': 0.12417532504569995}. Best is trial 84 with value: 0.013990999275512485.

[ 0.00000000e+00 -1.06334659e-04 -0.00000000e+00 -9.45896070e-04
 -0.00000000e+00 -0.00000000e+00  1.54491238e-03  6.33979810e-05
 -0.00000000e+00  0.00000000e+00  1.69685683e-04]
48

[I 2026-10-14 15:42:12,507] Trial 25 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.05007563601451126, 'l1_ratio': 0.3275268564080348}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,517] Trial 26 finished with value: 0.015011508535921654 and parameters: {'alpha': 4.994506014958038e-05, 'l1_ratio': 0.1913738944515531}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,525] Trial 27 finished with value: 0.014986394270507864 and parameters: {'alpha': 3.8811098287768493, 'l1_ratio': 0.07779471520117137}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,537] Trial 28 finished with value: 0.015013293211683595 and parameters: {'alpha': 8.678626482346501e-07, 'l1_ratio': 0.0012644570049296644}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,546] Trial 29 finished with value: 0.014957074477598085 and parameters: {'alpha': 0.001898764429188513, 'l1_ratio': 0.2262103910163795}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,559] Trial 30 finished with value: 0.015013297829301485 and parameters: {'alpha': 2.713487179698152e-10, 'l1_ratio': 0.0910571959785271}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,567] Trial 31 finished with value: 0.014961981104351667 and parameters: {'alpha': 0.00523477482233868, 'l1_ratio': 0.21063715909109634}. Best is trial 4 with value: 0.01495305014834125.
[I 2026-10-14 15:42:12,576] Trial 32 finished with value: 0.014952549668311086 and parameters: {'alpha': 0.002135880364515513, 'l1_ratio': 0.3418609738874799}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,583] Trial 33 finished with value: 0.015001411290564535 and parameters: {'alpha': 0.00016370097455650382, 'l1_ratio': 0.3418482200986954}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,592] Trial 34 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.1026331214943529, 'l1_ratio': 0.4652704723961757}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,600] Trial 35 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.744789099994365, 'l1_ratio': 0.45807404446717215}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,609] Trial 36 finished with value: 0.014955473172557457 and parameters: {'alpha': 0.002924498990010732, 'l1_ratio': 0.30552667857177224}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,619] Trial 37 finished with value: 0.01501180245738919 and parameters: {'alpha': 2.6760303827626965e-05, 'l1_ratio': 0.315168745478401}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,627] Trial 38 finished with value: 0.014986394270507864 and parameters: {'alpha': 5.857791328531934, 'l1_ratio': 0.4483360584553917}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,636] Trial 39 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.030719626859803607, 'l1_ratio': 0.6039259502517704}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,645] Trial 40 finished with value: 0.014961278666963623 and parameters: {'alpha': 0.003815556850790053, 'l1_ratio': 0.28667639705344905}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,655] Trial 41 finished with value: 0.014991844245494235 and parameters: {'alpha': 0.00041535622654145706, 'l1_ratio': 0.24143955601584083}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,665] Trial 42 finished with value: 0.014996005992141586 and parameters: {'alpha': 0.0002349796702564625, 'l1_ratio': 0.348851278260195}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,674] Trial 43 finished with value: 0.014986394270507864 and parameters: {'alpha': 68.5898466733113, 'l1_ratio': 0.5065386561187034}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,683] Trial 44 finished with value: 0.01497328589683479 and parameters: {'alpha': 0.002418039041939253, 'l1_ratio': 0.07966518016281508}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,691] Trial 45 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.02074999789304003, 'l1_ratio': 0.8196963478411724}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,698] Trial 46 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.2578768019719491, 'l1_ratio': 0.2822235747216054}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,706] Trial 47 finished with value: 0.014975200114916003 and parameters: {'alpha': 0.0008655109904289157, 'l1_ratio': 0.24260112500447623}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,714] Trial 48 finished with value: 0.015007941331945177 and parameters: {'alpha': 7.087421930736754e-05, 'l1_ratio': 0.3711692764570145}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,722] Trial 49 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.07671909684711953, 'l1_ratio': 0.1622544476025674}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,731] Trial 50 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.013294759360546877, 'l1_ratio': 0.4233916458934997}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,739] Trial 51 finished with value: 0.01495310567411039 and parameters: {'alpha': 0.00247154235288684, 'l1_ratio': 0.22491281939896957}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,748] Trial 52 finished with value: 0.01495284487462298 and parameters: {'alpha': 0.003017890521136559, 'l1_ratio': 0.25241333232686086}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,757] Trial 53 finished with value: 0.014987750180775944 and parameters: {'alpha': 0.0004053256087993997, 'l1_ratio': 0.3039213452500255}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,764] Trial 54 finished with value: 0.014969107291593857 and parameters: {'alpha': 0.007823921252975107, 'l1_ratio': 0.16424673969091755}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,774] Trial 55 finished with value: 0.015012676339783983 and parameters: {'alpha': 1.3260211221570775e-05, 'l1_ratio': 0.25679829816859073}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,782] Trial 56 finished with value: 0.015010812948509505 and parameters: {'alpha': 0.00011850750499547066, 'l1_ratio': 0.09863727352186391}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,792] Trial 57 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.02890295212576697, 'l1_ratio': 0.18140192087507623}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,800] Trial 58 finished with value: 0.014963454532739152 and parameters: {'alpha': 0.0008974317604955877, 'l1_ratio': 0.36800191792040743}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,808] Trial 59 finished with value: 0.01495688022567263 and parameters: {'alpha': 0.003538289582157569, 'l1_ratio': 0.11054400007125409}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,815] Trial 60 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.27601726995205056, 'l1_ratio': 0.2741876256528024}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,822] Trial 61 finished with value: 0.014953965040424745 and parameters: {'alpha': 0.0034198093745539775, 'l1_ratio': 0.14241674346933172}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,830] Trial 62 finished with value: 0.01500414360699437 and parameters: {'alpha': 0.0006015974088480229, 'l1_ratio': 0.05417049779999503}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,838] Trial 63 finished with value: 0.01495908098879137 and parameters: {'alpha': 0.0044291584666647345, 'l1_ratio': 0.22791438497561892}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,845] Trial 64 finished with value: 0.014983780401603053 and parameters: {'alpha': 0.014969116462897742, 'l1_ratio': 0.1299899601315505}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,853] Trial 65 finished with value: 0.0149585570209146 and parameters: {'alpha': 0.001993551084202643, 'l1_ratio': 0.19488442740225803}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,861] Trial 66 finished with value: 0.015002630066037153 and parameters: {'alpha': 0.00015898757048457866, 'l1_ratio': 0.3145749877428526}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,871] Trial 67 finished with value: 0.014983768972043024 and parameters: {'alpha': 0.05049923526557427, 'l1_ratio': 0.036505267285693754}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,879] Trial 68 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.008347567502342373, 'l1_ratio': 0.4002762077051104}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,886] Trial 69 finished with value: 0.014981880974965478 and parameters: {'alpha': 0.0016072304137089404, 'l1_ratio': 0.9788794678823172}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,898] Trial 70 finished with value: 0.015013297726691266 and parameters: {'alpha': 3.4566456605498606e-09, 'l1_ratio': 0.1596889255780224}. Best is trial 32 with value: 0.014952549668311086.
[I 2026-10-14 15:42:12,907] Trial 71 finished with value: 0.014952491833060244 and parameters: {'alpha': 0.004569999385278889, 'l1_ratio': 0.11551621191300651}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,915] Trial 72 finished with value: 0.015007771086660621 and parameters: {'alpha': 0.0003537944075892981, 'l1_ratio': 0.05818876259255723}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,925] Trial 73 finished with value: 0.014960177331886728 and parameters: {'alpha': 0.00500211744286014, 'l1_ratio': 0.20733177968136257}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,935] Trial 74 finished with value: 0.01497863149830884 and parameters: {'alpha': 0.1090112944911854, 'l1_ratio': 0.012379390528851814}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,944] Trial 75 finished with value: 0.014966457105341629 and parameters: {'alpha': 0.0011024507432850041, 'l1_ratio': 0.2644060296153535}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,953] Trial 76 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.024156262501934107, 'l1_ratio': 0.11510448655031227}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,963] Trial 77 finished with value: 0.014955272734832846 and parameters: {'alpha': 0.0029153235970571017, 'l1_ratio': 0.30267480829307164}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,973] Trial 78 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.00964589408846462, 'l1_ratio': 0.3352292952962034}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,983] Trial 79 finished with value: 0.015010428595888626 and parameters: {'alpha': 8.224486526496099e-05, 'l1_ratio': 0.17426518564830246}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:12,992] Trial 80 finished with value: 0.015012637743073117 and parameters: {'alpha': 2.3878165674976095e-05, 'l1_ratio': 0.1386431455365035}. Best is trial 71 with value: 0.014952491833060244.
[I 2026-10-14 15:42:13,002] Trial 81 finished with value: 0.01495205935983817 and parameters: {'alpha': 0.0028600199540572586, 'l1_ratio': 0.2318415191731328}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,012] Trial 82 finished with value: 0.014960279657902096 and parameters: {'alpha': 0.0016770186724000729, 'l1_ratio': 0.21193001837707454}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,020] Trial 83 finished with value: 0.014979553573768947 and parameters: {'alpha': 0.0006071328354069908, 'l1_ratio': 0.2938193852625096}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,030] Trial 84 finished with value: 0.015009454347829286 and parameters: {'alpha': 0.00021169432358433292, 'l1_ratio': 0.07500413977206363}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,040] Trial 85 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.04849656226967403, 'l1_ratio': 0.24076831845120766}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,049] Trial 86 finished with value: 0.014957072899197463 and parameters: {'alpha': 0.002628193010251044, 'l1_ratio': 0.36678495396752997}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,058] Trial 87 finished with value: 0.014982564363327898 and parameters: {'alpha': 0.006468022628544718, 'l1_ratio': 0.2679321024296478}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,065] Trial 88 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.01550180243900475, 'l1_ratio': 0.1935811054754668}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,073] Trial 89 finished with value: 0.014998668924358234 and parameters: {'alpha': 0.00029685632783239607, 'l1_ratio': 0.22522742225319606}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,082] Trial 90 finished with value: 0.014963501308171612 and parameters: {'alpha': 0.0009481754998286202, 'l1_ratio': 0.34661651963615375}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,092] Trial 91 finished with value: 0.01495761990269282 and parameters: {'alpha': 0.0032336454188693626, 'l1_ratio': 0.30193337302171785}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,100] Trial 92 finished with value: 0.014956496017870418 and parameters: {'alpha': 0.0028625907692159886, 'l1_ratio': 0.14644161391964308}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,109] Trial 93 finished with value: 0.014979155610127151 and parameters: {'alpha': 0.005804905210859067, 'l1_ratio': 0.2608367034825274}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,119] Trial 94 finished with value: 0.014998792552284108 and parameters: {'alpha': 0.0005693827741280844, 'l1_ratio': 0.10582801148143031}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,127] Trial 95 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.016358169914718047, 'l1_ratio': 0.28827315527851044}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,135] Trial 96 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.03787087186543323, 'l1_ratio': 0.4333361006567401}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,142] Trial 97 finished with value: 0.014954208705158976 and parameters: {'alpha': 0.001615113016410652, 'l1_ratio': 0.3274165496442494}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,150] Trial 98 finished with value: 0.014964185688097941 and parameters: {'alpha': 0.001336155746008645, 'l1_ratio': 0.23391344223716762}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,158] Trial 99 finished with value: 0.014983877088958287 and parameters: {'alpha': 0.010992173220849461, 'l1_ratio': 0.17918385069688303}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,165] Trial 100 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.00531268247401869, 'l1_ratio': 0.4909326572623003}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,174] Trial 101 finished with value: 0.01495281644616026 and parameters: {'alpha': 0.001854021572583995, 'l1_ratio': 0.3223157571079823}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,184] Trial 102 finished with value: 0.01495579972738882 and parameters: {'alpha': 0.001505146921180433, 'l1_ratio': 0.31626551101878886}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,193] Trial 103 finished with value: 0.014977535103834405 and parameters: {'alpha': 0.0005559839678107723, 'l1_ratio': 0.35383645879738157}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,203] Trial 104 finished with value: 0.014954171398167116 and parameters: {'alpha': 0.002517070947812531, 'l1_ratio': 0.32768871106429964}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,214] Trial 105 finished with value: 0.014959991696547782 and parameters: {'alpha': 0.0009719941369077311, 'l1_ratio': 0.39477036133410975}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,223] Trial 106 finished with value: 0.01499849080031236 and parameters: {'alpha': 0.00020908240593147856, 'l1_ratio': 0.33337374756711685}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,231] Trial 107 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.02082451685374012, 'l1_ratio': 0.25441409770257584}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,239] Trial 108 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.007665435914970039, 'l1_ratio': 0.38377731721917613}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,248] Trial 109 finished with value: 0.015010280068217132 and parameters: {'alpha': 0.00011254384722953086, 'l1_ratio': 0.12720538740502446}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,256] Trial 110 finished with value: 0.014954409817324597 and parameters: {'alpha': 0.0019850482581117283, 'l1_ratio': 0.41994989943131933}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,265] Trial 111 finished with value: 0.01495487489382956 and parameters: {'alpha': 0.0020843863233012956, 'l1_ratio': 0.4166913236728692}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,273] Trial 112 finished with value: 0.014972602109166533 and parameters: {'alpha': 0.0042933387759209385, 'l1_ratio': 0.32346611272587167}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,281] Trial 113 finished with value: 0.014993289510978017 and parameters: {'alpha': 0.0003367945337763397, 'l1_ratio': 0.2795440873987561}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,291] Trial 114 finished with value: 0.014959293681470432 and parameters: {'alpha': 0.0008411100003677128, 'l1_ratio': 0.4835017636972023}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,299] Trial 115 finished with value: 0.014952529041352088 and parameters: {'alpha': 0.001669132702541222, 'l1_ratio': 0.3816665074876295}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,306] Trial 116 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.0751831591486093, 'l1_ratio': 0.08005914800502628}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,313] Trial 117 finished with value: 0.014986394270507864 and parameters: {'alpha': 0.011350701584235729, 'l1_ratio': 0.363208383375087}. Best is trial 81 with value: 0.01495205935983817.
[I 2026-10-14 15:42:13,322] Trial 118 finished with value: 0.014953797776913086 and parameters: {'alpha': 0.003890618212232094, 'l1_ratio': 0.20829538891819427}. Best is trial 81 with value: 0.01495205935983817.

[ 0.         -0.00426849 -0.         -0.0086621  -0.         -0.0053292
  0.01106145  0.01615722 -0.00889524  0.          0.02192357]
54

[I 2026-10-14 15:42:14,726] Trial 25 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.07487013989364534, 'l1_ratio': 0.9975089394322556}. Best is trial 20 with value: 0.01481548525304769.
[I 2026-10-14 15:42:14,735] Trial 26 finished with value: 0.014815293338920087 and parameters: {'alpha': 0.0006902541818899728, 'l1_ratio': 0.8157787133009231}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,743] Trial 27 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0281390934037709, 'l1_ratio': 0.7656707939766833}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,750] Trial 28 finished with value: 0.014851884147489024 and parameters: {'alpha': 9.316685535653626e-05, 'l1_ratio': 0.8205492712464286}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,760] Trial 29 finished with value: 0.014863140836602269 and parameters: {'alpha': 4.365849852203874e-08, 'l1_ratio': 0.6078623053632487}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,767] Trial 30 finished with value: 0.014854955410415996 and parameters: {'alpha': 2.0111155456006777, 'l1_ratio': 0.9274938210407351}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,775] Trial 31 finished with value: 0.014821495134184959 and parameters: {'alpha': 0.0009764423827986438, 'l1_ratio': 0.9153851864317263}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,783] Trial 32 finished with value: 0.014822164961239765 and parameters: {'alpha': 0.0003967218862709516, 'l1_ratio': 0.7930015762494179}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,792] Trial 33 finished with value: 0.014861684164769878 and parameters: {'alpha': 1.2622107077534733e-05, 'l1_ratio': 0.7050058360637834}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,803] Trial 34 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.005623460845904013, 'l1_ratio': 0.8983336355753492}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,811] Trial 35 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.014036510988875617, 'l1_ratio': 0.814992228458979}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,823] Trial 36 finished with value: 0.014863108121659132 and parameters: {'alpha': 3.036454636827258e-07, 'l1_ratio': 0.7343642188971441}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,832] Trial 37 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0028871702461417182, 'l1_ratio': 0.8314177681640064}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,843] Trial 38 finished with value: 0.014863143116672577 and parameters: {'alpha': 1.3871698276037001e-08, 'l1_ratio': 0.9442666910774523}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,856] Trial 39 finished with value: 0.014861614305769037 and parameters: {'alpha': 1.3251854839753533e-05, 'l1_ratio': 0.704222738794632}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,864] Trial 40 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.18128612422096685, 'l1_ratio': 0.8851068926946289}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,872] Trial 41 finished with value: 0.01482065071801776 and parameters: {'alpha': 0.0009656048881091682, 'l1_ratio': 0.901766871085187}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,880] Trial 42 finished with value: 0.014840662134011567 and parameters: {'alpha': 0.00018293879413043898, 'l1_ratio': 0.7755549142966852}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,889] Trial 43 finished with value: 0.014827055853691127 and parameters: {'alpha': 0.0011797813539030472, 'l1_ratio': 0.8743087422674236}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,897] Trial 44 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.015052890056230171, 'l1_ratio': 0.9447483219725905}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,906] Trial 45 finished with value: 0.014817206182551135 and parameters: {'alpha': 0.00076856233962819, 'l1_ratio': 0.9984835999307639}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,914] Trial 46 finished with value: 0.014856532502047251 and parameters: {'alpha': 4.4157778269390385e-05, 'l1_ratio': 0.9841864156902561}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,922] Trial 47 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.005821938384157507, 'l1_ratio': 0.8307841513139017}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,930] Trial 48 finished with value: 0.014854955410415996 and parameters: {'alpha': 9.761260915250947, 'l1_ratio': 0.9969890636580063}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,938] Trial 49 finished with value: 0.014846361248748606 and parameters: {'alpha': 0.00016342525240965698, 'l1_ratio': 0.6557776774819477}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,946] Trial 50 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.05301950637589591, 'l1_ratio': 0.780983091338638}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,954] Trial 51 finished with value: 0.01481568366808531 and parameters: {'alpha': 0.0007545771796990459, 'l1_ratio': 0.9215268692947238}. Best is trial 26 with value: 0.014815293338920087.
[I 2026-10-14 15:42:14,963] Trial 52 finished with value: 0.014815088279997201 and parameters: {'alpha': 0.0007045106722838535, 'l1_ratio': 0.8502980146620185}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:14,971] Trial 53 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0030747236370557976, 'l1_ratio': 0.8519759735803049}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:14,978] Trial 54 finished with value: 0.014825238104419172 and parameters: {'alpha': 0.0002883217031043351, 'l1_ratio': 0.9447849216150588}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:14,987] Trial 55 finished with value: 0.01485735582063981 and parameters: {'alpha': 4.681267555995223e-05, 'l1_ratio': 0.799431765598298}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:14,995] Trial 56 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.006518069367323639, 'l1_ratio': 0.7378148135743836}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,002] Trial 57 finished with value: 0.014818808557069995 and parameters: {'alpha': 0.00042678677480228506, 'l1_ratio': 0.9582500249850079}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,012] Trial 58 finished with value: 0.014859552141078484 and parameters: {'alpha': 2.626895522793237e-05, 'l1_ratio': 0.85979387837924}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,021] Trial 59 finished with value: 0.014862400749344772 and parameters: {'alpha': 4.974743891132988e-06, 'l1_ratio': 0.9101325995812488}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,030] Trial 60 finished with value: 0.014845453822598711 and parameters: {'alpha': 0.00013451804935143229, 'l1_ratio': 0.8398300659534607}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,039] Trial 61 finished with value: 0.014819623061508774 and parameters: {'alpha': 0.0009140298739080776, 'l1_ratio': 0.9184094834316568}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,048] Trial 62 finished with value: 0.014855877113925955 and parameters: {'alpha': 0.0017906704200101073, 'l1_ratio': 0.9707702045347255}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,055] Trial 63 finished with value: 0.014815734883096024 and parameters: {'alpha': 0.0006066660327986397, 'l1_ratio': 0.866821698875801}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,064] Trial 64 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.010755496908733963, 'l1_ratio': 0.749373146439085}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,072] Trial 65 finished with value: 0.014819118536597817 and parameters: {'alpha': 0.0004644731117729598, 'l1_ratio': 0.8622132519624306}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,083] Trial 66 finished with value: 0.014852638928155677 and parameters: {'alpha': 8.998972748999066e-05, 'l1_ratio': 0.803482878494779}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,091] Trial 67 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.03618587444787157, 'l1_ratio': 0.9216199902072049}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,098] Trial 68 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.24026562394587636, 'l1_ratio': 0.8865051308255695}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,108] Trial 69 finished with value: 0.014855304116188949 and parameters: {'alpha': 0.0026740158585883233, 'l1_ratio': 0.6859028861964449}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,117] Trial 70 finished with value: 0.014824514823306097 and parameters: {'alpha': 0.00044655825182850835, 'l1_ratio': 0.6277496702533575}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,124] Trial 71 finished with value: 0.014815101813275078 and parameters: {'alpha': 0.000715289165919738, 'l1_ratio': 0.8329016436096836}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,134] Trial 72 finished with value: 0.014849694866363125 and parameters: {'alpha': 0.0017242360894106864, 'l1_ratio': 0.8255586997864677}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,142] Trial 73 finished with value: 0.014816140510197917 and parameters: {'alpha': 0.0006609464294134778, 'l1_ratio': 0.7616360947909686}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,153] Trial 74 finished with value: 0.014835657552776596 and parameters: {'alpha': 0.0002286748059560446, 'l1_ratio': 0.762231084991104}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,164] Trial 75 finished with value: 0.014860810230973343 and parameters: {'alpha': 2.6924386022056837e-05, 'l1_ratio': 0.5288409445852793}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,172] Trial 76 finished with value: 0.014858113497401904 and parameters: {'alpha': 9.120646619900264e-05, 'l1_ratio': 0.34113577485320135}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,181] Trial 77 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.007276648198471297, 'l1_ratio': 0.7167713589922302}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,191] Trial 78 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.01992404586126833, 'l1_ratio': 0.7920671663790679}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,200] Trial 79 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0033628004605330913, 'l1_ratio': 0.8435918883721203}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,207] Trial 80 finished with value: 0.014816695407383335 and parameters: {'alpha': 0.0005108097483255129, 'l1_ratio': 0.9350887085403172}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,216] Trial 81 finished with value: 0.014815858203155834 and parameters: {'alpha': 0.0005346882617423577, 'l1_ratio': 0.968204558783174}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,225] Trial 82 finished with value: 0.014816623395817387 and parameters: {'alpha': 0.000515664209354039, 'l1_ratio': 0.9320607462320905}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,234] Trial 83 finished with value: 0.01483590592995507 and parameters: {'alpha': 0.0001936397732316705, 'l1_ratio': 0.8934923472648897}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,243] Trial 84 finished with value: 0.01485630009066463 and parameters: {'alpha': 0.001728426750167289, 'l1_ratio': 0.9745255852479587}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,253] Trial 85 finished with value: 0.014862494469393653 and parameters: {'alpha': 4.8642957727298575e-06, 'l1_ratio': 0.8103604782009083}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,262] Trial 86 finished with value: 0.014854192125288808 and parameters: {'alpha': 6.396017112076014e-05, 'l1_ratio': 0.9531237785493759}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,272] Trial 87 finished with value: 0.014862738863951687 and parameters: {'alpha': 2.828612988207718e-05, 'l1_ratio': 0.06809571324110009}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,282] Trial 88 finished with value: 0.014815994600944347 and parameters: {'alpha': 0.0005809821032751268, 'l1_ratio': 0.8786727543153356}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,291] Trial 89 finished with value: 0.014830540102730787 and parameters: {'alpha': 0.0012697390678315854, 'l1_ratio': 0.8804105083434798}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,300] Trial 90 finished with value: 0.01484733836371067 and parameters: {'alpha': 0.00013320284845796094, 'l1_ratio': 0.7645099128087345}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,309] Trial 91 finished with value: 0.014823055998491121 and parameters: {'alpha': 0.0003318695998805955, 'l1_ratio': 0.9099058145227717}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,318] Trial 92 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.003665910790772917, 'l1_ratio': 0.8500686072898382}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,327] Trial 93 finished with value: 0.014815634433000316 and parameters: {'alpha': 0.000646136860989595, 'l1_ratio': 0.8249695019985471}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,335] Trial 94 finished with value: 0.014815089475929818 and parameters: {'alpha': 0.0007569064333780246, 'l1_ratio': 0.811293866855692}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,343] Trial 95 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.008850386423872536, 'l1_ratio': 0.819722458711994}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,352] Trial 96 finished with value: 0.014856323012733522 and parameters: {'alpha': 0.0021354367703994774, 'l1_ratio': 0.786615270591378}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,360] Trial 97 finished with value: 0.014829246899178486 and parameters: {'alpha': 0.0002572466433333465, 'l1_ratio': 0.8709361279708504}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,368] Trial 98 finished with value: 0.014818422623759337 and parameters: {'alpha': 0.0009555327333459848, 'l1_ratio': 0.840512374271458}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,376] Trial 99 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0050912380686432565, 'l1_ratio': 0.7282839002892216}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,386] Trial 100 finished with value: 0.014854955410415996 and parameters: {'alpha': 97.11868995130489, 'l1_ratio': 0.2023277512397938}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,394] Trial 101 finished with value: 0.014815088846467563 and parameters: {'alpha': 0.0007461758986953828, 'l1_ratio': 0.8135621519338604}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,402] Trial 102 finished with value: 0.014843388919216244 and parameters: {'alpha': 0.00013996336393920196, 'l1_ratio': 0.89600907120159}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,410] Trial 103 finished with value: 0.014824139559238492 and parameters: {'alpha': 0.0011838132668388446, 'l1_ratio': 0.8037368035925256}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,420] Trial 104 finished with value: 0.014831847967511148 and parameters: {'alpha': 0.00023102590416924416, 'l1_ratio': 0.8706055012231959}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,430] Trial 105 finished with value: 0.014856188132435525 and parameters: {'alpha': 5.578923847718395e-05, 'l1_ratio': 0.8203001798444662}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,440] Trial 106 finished with value: 0.014816713694245845 and parameters: {'alpha': 0.000560602958170993, 'l1_ratio': 0.8508448707185533}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,454] Trial 107 finished with value: 0.014863145254474294 and parameters: {'alpha': 2.203937730892961e-10, 'l1_ratio': 0.9087185331369009}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,462] Trial 108 finished with value: 0.01485229484163076 and parameters: {'alpha': 0.0018840660726260434, 'l1_ratio': 0.7823141882276115}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,469] Trial 109 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.0040370407382491254, 'l1_ratio': 0.964206522754986}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,480] Trial 110 finished with value: 0.014815901932529138 and parameters: {'alpha': 0.0006961355832185074, 'l1_ratio': 0.7422160007719695}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,488] Trial 111 finished with value: 0.014815091495916831 and parameters: {'alpha': 0.0007358720774290283, 'l1_ratio': 0.8191145006992984}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,499] Trial 112 finished with value: 0.01482647069012289 and parameters: {'alpha': 0.0003438727066605029, 'l1_ratio': 0.7444350582793317}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,507] Trial 113 finished with value: 0.014819862062946141 and parameters: {'alpha': 0.0012198594463440238, 'l1_ratio': 0.688398806100046}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,515] Trial 114 finished with value: 0.014844927798335218 and parameters: {'alpha': 0.00013818213142777655, 'l1_ratio': 0.8400501914405129}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,522] Trial 115 finished with value: 0.014854908329897332 and parameters: {'alpha': 0.002519882171900797, 'l1_ratio': 0.8006192432773818}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,533] Trial 116 finished with value: 0.014863144847434548 and parameters: {'alpha': 3.424268164826496e-09, 'l1_ratio': 0.772044951023353}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,540] Trial 117 finished with value: 0.014815290350483082 and parameters: {'alpha': 0.0007946207085017923, 'l1_ratio': 0.8291319873012968}. Best is trial 52 with value: 0.014815088279997201.
[I 2026-10-14 15:42:15,548] Trial 118 finished with value: 0.014854955410415996 and parameters: {'alpha': 0.021130475785972262, 'l1_ratio': 0.8293004739430031}. Best is trial 52 with value: 0.014815088279997201.

[ 0.         -0.00231573 -0.         -0.00938639 -0.         -0.00240485
  0.00962601  0.02346094 -0.00895482  0.          0.03260664]
60

[I 2026-10-14 15:42:16,992] Trial 27 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.47874776186223744, 'l1_ratio': 0.41213457141244314}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:16,999] Trial 28 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.021709381785459173, 'l1_ratio': 0.20788873449934697}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,006] Trial 29 finished with value: 0.014819610652639802 and parameters: {'alpha': 3.3224355485051453, 'l1_ratio': 0.9559551107081007}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,014] Trial 30 finished with value: 0.014864811165937743 and parameters: {'alpha': 0.00014691840811165355, 'l1_ratio': 0.693908652068323}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,021] Trial 31 finished with value: 0.014819610652639802 and parameters: {'alpha': 38.98207031187781, 'l1_ratio': 0.305259569405167}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,030] Trial 32 finished with value: 0.014819610652639802 and parameters: {'alpha': 11.467520201959584, 'l1_ratio': 0.4628398699042639}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,038] Trial 33 finished with value: 0.014819610652639802 and parameters: {'alpha': 68.64486877364769, 'l1_ratio': 0.053487605148281554}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,051] Trial 34 finished with value: 0.014886305542813038 and parameters: {'alpha': 5.379463088203325e-08, 'l1_ratio': 0.3784430850624893}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,058] Trial 35 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.3865610437398828, 'l1_ratio': 0.2787735523686507}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,067] Trial 36 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.07199080115586813, 'l1_ratio': 0.14772590083120035}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,081] Trial 37 finished with value: 0.014886310584048568 and parameters: {'alpha': 1.0329140577665836e-10, 'l1_ratio': 0.07281351158415708}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,089] Trial 38 finished with value: 0.014819610652639802 and parameters: {'alpha': 96.98190819936983, 'l1_ratio': 0.19864251514404474}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,097] Trial 39 finished with value: 0.014819610652639802 and parameters: {'alpha': 16.280928234128876, 'l1_ratio': 0.6204768958095741}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,106] Trial 40 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.007615511724127359, 'l1_ratio': 0.5277083663035559}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,114] Trial 41 finished with value: 0.014819610652639802 and parameters: {'alpha': 2.9741926217100065, 'l1_ratio': 0.3063214641957062}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,123] Trial 42 finished with value: 0.014819610652639802 and parameters: {'alpha': 16.24955227488349, 'l1_ratio': 0.3447468576467318}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,131] Trial 43 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.6191047488066107, 'l1_ratio': 0.18764560224868726}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,139] Trial 44 finished with value: 0.014819610652639802 and parameters: {'alpha': 5.73111885682497, 'l1_ratio': 0.24174016742393717}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,147] Trial 45 finished with value: 0.014819610652639802 and parameters: {'alpha': 35.14712818069691, 'l1_ratio': 0.4570067826424977}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,155] Trial 46 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.04904789715921248, 'l1_ratio': 0.049394467871245365}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,164] Trial 47 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.2449080759785191, 'l1_ratio': 0.40423102646851045}. Best is trial 12 with value: 0.014811937577066676.
[I 2026-10-14 15:42:17,175] Trial 48 finished with value: 0.01480926531303972 and parameters: {'alpha': 0.0014691894546537796, 'l1_ratio': 0.5712145717582894}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,183] Trial 49 finished with value: 0.0148099523744961 and parameters: {'alpha': 0.0013258291783854461, 'l1_ratio': 0.5862969642375023}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,192] Trial 50 finished with value: 0.014809295182313562 and parameters: {'alpha': 0.0014479305409979082, 'l1_ratio': 0.5763275825671674}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,200] Trial 51 finished with value: 0.01482733993157641 and parameters: {'alpha': 0.0006404688119393929, 'l1_ratio': 0.5829557417479242}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,207] Trial 52 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.004847077398088689, 'l1_ratio': 0.7741457152519056}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,216] Trial 53 finished with value: 0.014872340086660416 and parameters: {'alpha': 0.00010074428616479584, 'l1_ratio': 0.6307864422825453}. Best is trial 48 with value: 0.01480926531303972.
[I 2026-10-14 15:42:17,223] Trial 54 finished with value: 0.014809164396813375 and parameters: {'alpha': 0.0015071869900786044, 'l1_ratio': 0.577463996264438}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,231] Trial 55 finished with value: 0.014809810178664208 and parameters: {'alpha': 0.0017202910774133861, 'l1_ratio': 0.6733529327237208}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,239] Trial 56 finished with value: 0.014822563435545144 and parameters: {'alpha': 0.0020771713714070653, 'l1_ratio': 0.8172745096033396}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,249] Trial 57 finished with value: 0.014884963265893414 and parameters: {'alpha': 8.294317789980112e-06, 'l1_ratio': 0.6787289902342349}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,257] Trial 58 finished with value: 0.014856590849378274 and parameters: {'alpha': 0.00024436132330212055, 'l1_ratio': 0.572507559504343}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,265] Trial 59 finished with value: 0.014881720854536491 and parameters: {'alpha': 3.9306026804833336e-05, 'l1_ratio': 0.49149796745098595}. Best is trial 54 with value: 0.014809164396813375.
[I 2026-10-14 15:42:17,273] Trial 60 finished with value: 0.014808667177675665 and parameters: {'alpha': 0.0014236240461662855, 'l1_ratio': 0.7396027674921084}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,280] Trial 61 finished with value: 0.01482462704174031 and parameters: {'alpha': 0.0005531032751987917, 'l1_ratio': 0.7447147489156847}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,287] Trial 62 finished with value: 0.014821364483840149 and parameters: {'alpha': 0.001831805483898145, 'l1_ratio': 0.85079291848253}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,297] Trial 63 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.007760120261978698, 'l1_ratio': 0.6683780256263074}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,307] Trial 64 finished with value: 0.014808781424614156 and parameters: {'alpha': 0.0018767198242278125, 'l1_ratio': 0.5621817841832392}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,319] Trial 65 finished with value: 0.014881135748921822 and parameters: {'alpha': 3.9172223576379446e-05, 'l1_ratio': 0.5614686708683593}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,326] Trial 66 finished with value: 0.014849580955104106 and parameters: {'alpha': 0.0002925973415022184, 'l1_ratio': 0.5987241257291569}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,335] Trial 67 finished with value: 0.014810496675229573 and parameters: {'alpha': 0.0014550520376704645, 'l1_ratio': 0.5078096702526247}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,343] Trial 68 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.013376656986421641, 'l1_ratio': 0.6523965021152686}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,355] Trial 69 finished with value: 0.014873377501466594 and parameters: {'alpha': 8.246016746081532e-05, 'l1_ratio': 0.7104663974009167}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,364] Trial 70 finished with value: 0.014886190810205245 and parameters: {'alpha': 8.159527929733544e-07, 'l1_ratio': 0.6062061508484814}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,372] Trial 71 finished with value: 0.014809371769550541 and parameters: {'alpha': 0.0015288799644278712, 'l1_ratio': 0.5388187193680791}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,379] Trial 72 finished with value: 0.014821497546066641 and parameters: {'alpha': 0.0032681341430757446, 'l1_ratio': 0.5474530726902751}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,387] Trial 73 finished with value: 0.014849808986037273 and parameters: {'alpha': 0.00032305203782488943, 'l1_ratio': 0.5369007138855308}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,396] Trial 74 finished with value: 0.014813938530129711 and parameters: {'alpha': 0.0012227063393633222, 'l1_ratio': 0.489763997724685}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,405] Trial 75 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.0167137793204241, 'l1_ratio': 0.6462783167676763}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,413] Trial 76 finished with value: 0.014819679793769514 and parameters: {'alpha': 0.0028017978002954874, 'l1_ratio': 0.7452852320389661}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,423] Trial 77 finished with value: 0.014884026215099861 and parameters: {'alpha': 1.5800063950929978e-05, 'l1_ratio': 0.6050528571992928}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,435] Trial 78 finished with value: 0.014817947096158681 and parameters: {'alpha': 0.0006540410213108995, 'l1_ratio': 0.7928800964342035}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,444] Trial 79 finished with value: 0.014856664204406844 and parameters: {'alpha': 0.0001991546478281529, 'l1_ratio': 0.704728866629508}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,453] Trial 80 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.03757203664142621, 'l1_ratio': 0.5103881977111403}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,461] Trial 81 finished with value: 0.014818209034137303 and parameters: {'alpha': 0.0010600958280781942, 'l1_ratio': 0.4770236738903987}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,470] Trial 82 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.0075270213964491964, 'l1_ratio': 0.5234319124673527}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,478] Trial 83 finished with value: 0.014813258672279195 and parameters: {'alpha': 0.001410187531187666, 'l1_ratio': 0.4361683443730922}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,487] Trial 84 finished with value: 0.014821162450951542 and parameters: {'alpha': 0.0032840312737186773, 'l1_ratio': 0.5557651559664161}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,495] Trial 85 finished with value: 0.01483765014710001 and parameters: {'alpha': 0.00040022116588038384, 'l1_ratio': 0.6624423951407442}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,505] Trial 86 finished with value: 0.01487353723945733 and parameters: {'alpha': 9.936129793426207e-05, 'l1_ratio': 0.5773856098222396}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,513] Trial 87 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.01104716723232015, 'l1_ratio': 0.6253570523922617}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,522] Trial 88 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.005269750757241399, 'l1_ratio': 0.5195648338717425}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,530] Trial 89 finished with value: 0.014809785104562153 and parameters: {'alpha': 0.0011501219595204208, 'l1_ratio': 0.6865990300897111}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,538] Trial 90 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.003380525016175273, 'l1_ratio': 0.6813963299995841}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,547] Trial 91 finished with value: 0.01481347998295585 and parameters: {'alpha': 0.0010453685235341994, 'l1_ratio': 0.5885659770478968}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,556] Trial 92 finished with value: 0.014828575045547937 and parameters: {'alpha': 0.000493606794150137, 'l1_ratio': 0.7303085764384711}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,565] Trial 93 finished with value: 0.01480882186844249 and parameters: {'alpha': 0.0017221472091878123, 'l1_ratio': 0.621273512217283}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,574] Trial 94 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.028572670038057083, 'l1_ratio': 0.6328059783942072}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,585] Trial 95 finished with value: 0.014876903995262298 and parameters: {'alpha': 6.679814017130933e-05, 'l1_ratio': 0.6186065094584213}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,593] Trial 96 finished with value: 0.01486362793929984 and parameters: {'alpha': 0.00015405324047441333, 'l1_ratio': 0.6970229802926103}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,601] Trial 97 finished with value: 0.014816054563448275 and parameters: {'alpha': 0.002488410142712402, 'l1_ratio': 0.5526171372744872}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,608] Trial 98 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.11075425235524816, 'l1_ratio': 0.6476125232941781}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,615] Trial 99 finished with value: 0.01481238388811225 and parameters: {'alpha': 0.000859407918913262, 'l1_ratio': 0.7616585803805541}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,624] Trial 100 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.011145855087824435, 'l1_ratio': 0.5963173636706438}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,631] Trial 101 finished with value: 0.0148097323225948 and parameters: {'alpha': 0.0019920855416437674, 'l1_ratio': 0.5764414659815534}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,638] Trial 102 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.005649429459293771, 'l1_ratio': 0.5712819168804977}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,646] Trial 103 finished with value: 0.01481010660994284 and parameters: {'alpha': 0.001759247557740318, 'l1_ratio': 0.668151564171573}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,653] Trial 104 finished with value: 0.014843559683041442 and parameters: {'alpha': 0.00040130894176574824, 'l1_ratio': 0.5381398112717297}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,660] Trial 105 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.004749203581634002, 'l1_ratio': 0.6051106252187746}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,668] Trial 106 finished with value: 0.014822036920528456 and parameters: {'alpha': 0.0006554274458500625, 'l1_ratio': 0.6837334327851912}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,675] Trial 107 finished with value: 0.014854571158961405 and parameters: {'alpha': 0.00020823409507800925, 'l1_ratio': 0.7238335551940238}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,682] Trial 108 finished with value: 0.01480879491863304 and parameters: {'alpha': 0.002107312835473451, 'l1_ratio': 0.4708424249591252}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,690] Trial 109 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.02037891466263335, 'l1_ratio': 0.4925540423400592}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,698] Trial 110 finished with value: 0.014809219246146138 and parameters: {'alpha': 0.002094734652926158, 'l1_ratio': 0.4442795355335981}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,707] Trial 111 finished with value: 0.014809125570439828 and parameters: {'alpha': 0.002012419544186201, 'l1_ratio': 0.46655515952005894}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,715] Trial 112 finished with value: 0.014809352705797025 and parameters: {'alpha': 0.0026294602447160405, 'l1_ratio': 0.4206033784999199}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,723] Trial 113 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.01018665592174917, 'l1_ratio': 0.4026768193933388}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,731] Trial 114 finished with value: 0.01480950083354075 and parameters: {'alpha': 0.0026570860554511575, 'l1_ratio': 0.42079857964862444}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,739] Trial 115 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.005040255961195993, 'l1_ratio': 0.4458166177700043}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,746] Trial 116 finished with value: 0.014812026312239764 and parameters: {'alpha': 0.0033980756280502676, 'l1_ratio': 0.3663877612825346}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,755] Trial 117 finished with value: 0.014830425133700456 and parameters: {'alpha': 0.0007629449968993556, 'l1_ratio': 0.43377716930063237}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,764] Trial 118 finished with value: 0.014847549195685381 and parameters: {'alpha': 0.0004017547656518405, 'l1_ratio': 0.46107209659205173}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,772] Trial 119 finished with value: 0.014819610652639802 and parameters: {'alpha': 0.01920605307706115, 'l1_ratio': 0.41678672343882195}. Best is trial 60 with value: 0.014808667177675665.
[I 2026-10-14 15:42:17,780] Trial 120 finished with value: 0.014809028299096376 and parameters: {'alpha': 0.00225852474654672, 'l1_ratio': 0.4786083029179337}. Best is trial 60 with value: 0.014808667177675665.

[ 0.         -0.         -0.         -0.00421114 -0.         -0.
  0.00714672  0.00833256 -0.          0.          0.01712515]
66

[I 2026-10-14 15:42:19,179] Trial 24 finished with value: 0.014055230072499082 and parameters: {'alpha': 1.743154436562395e-05, 'l1_ratio': 0.4800846309624622}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,185] Trial 25 finished with value: 0.014071864000304884 and parameters: {'alpha': 2.6725710785501993, 'l1_ratio': 0.6039352371363313}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,192] Trial 26 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.017022511209970788, 'l1_ratio': 0.31277970002673994}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,200] Trial 27 finished with value: 0.014039149202718882 and parameters: {'alpha': 0.00043599313290505054, 'l1_ratio': 0.17471365088649127}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,210] Trial 28 finished with value: 0.014057305662873804 and parameters: {'alpha': 2.3032563749903772e-07, 'l1_ratio': 0.4668678692722555}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,219] Trial 29 finished with value: 0.01405153136135721 and parameters: {'alpha': 2.933053856811572e-05, 'l1_ratio': 0.818419319808155}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,227] Trial 30 finished with value: 0.014020526181608504 and parameters: {'alpha': 0.0009535972641803636, 'l1_ratio': 0.9694265442074581}. Best is trial 13 with value: 0.014007662898807486.
[I 2026-10-14 15:42:19,234] Trial 31 finished with value: 0.014006796803492861 and parameters: {'alpha': 0.0005679906308087619, 'l1_ratio': 0.8597292712857039}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,241] Trial 32 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.018995378681209877, 'l1_ratio': 0.9131806689371419}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,254] Trial 33 finished with value: 0.014052933119797056 and parameters: {'alpha': 2.1334398472030914e-05, 'l1_ratio': 0.8466593917322575}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,264] Trial 34 finished with value: 0.014071864000304884 and parameters: {'alpha': 3.814023620727612, 'l1_ratio': 0.79228200343136}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,273] Trial 35 finished with value: 0.014016380068340672 and parameters: {'alpha': 0.0003731526565205774, 'l1_ratio': 0.7266776950580205}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,280] Trial 36 finished with value: 0.014021289653467574 and parameters: {'alpha': 0.0002952138825577697, 'l1_ratio': 0.7452183787716564}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,286] Trial 37 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.044681954828431174, 'l1_ratio': 0.6125843617145387}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,296] Trial 38 finished with value: 0.014046960430081544 and parameters: {'alpha': 0.001423832398283181, 'l1_ratio': 0.9266980178835489}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,304] Trial 39 finished with value: 0.014049130048083459 and parameters: {'alpha': 4.847364866966557e-05, 'l1_ratio': 0.7089362425355524}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,317] Trial 40 finished with value: 0.01405733302720868 and parameters: {'alpha': 1.0447817024829289e-10, 'l1_ratio': 0.5598932444014437}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,324] Trial 41 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.005027944884727684, 'l1_ratio': 0.852585687616232}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,332] Trial 42 finished with value: 0.014024819350909731 and parameters: {'alpha': 0.0002798410737376875, 'l1_ratio': 0.6659273157749817}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,341] Trial 43 finished with value: 0.014056813241385734 and parameters: {'alpha': 5.931571124935067e-06, 'l1_ratio': 0.3398090882296198}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,348] Trial 44 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.9202296423360816, 'l1_ratio': 0.7260482214337073}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,357] Trial 45 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.008678531239669737, 'l1_ratio': 0.46855965929553445}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,364] Trial 46 finished with value: 0.014006952641534374 and parameters: {'alpha': 0.001559071134737561, 'l1_ratio': 0.27123091134829885}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,371] Trial 47 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.1087200055447002, 'l1_ratio': 0.2007448357338742}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,380] Trial 48 finished with value: 0.014055380643876387 and parameters: {'alpha': 0.00010488413917795884, 'l1_ratio': 0.056735245231143705}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,389] Trial 49 finished with value: 0.014047487355951124 and parameters: {'alpha': 0.001571205780182459, 'l1_ratio': 0.008348046662478015}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,398] Trial 50 finished with value: 0.014057180050430029 and parameters: {'alpha': 4.4521154126004275e-06, 'l1_ratio': 0.12032207616204543}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,406] Trial 51 finished with value: 0.01402987350785273 and parameters: {'alpha': 0.0004367357334667468, 'l1_ratio': 0.3154402595567867}. Best is trial 31 with value: 0.014006796803492861.
[I 2026-10-14 15:42:19,414] Trial 52 finished with value: 0.014006658516452997 and parameters: {'alpha': 0.0016381614273909952, 'l1_ratio': 0.280368336969227}. Best is trial 52 with value: 0.014006658516452997.
[I 2026-10-14 15:42:19,422] Trial 53 finished with value: 0.014006529751446698 and parameters: {'alpha': 0.0018773035490866608, 'l1_ratio': 0.25520025706648014}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,430] Trial 54 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.07521522326571824, 'l1_ratio': 0.25588441926504546}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,438] Trial 55 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.00945844549809803, 'l1_ratio': 0.2674302217358893}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,446] Trial 56 finished with value: 0.014008954140886598 and parameters: {'alpha': 0.0025025739481104466, 'l1_ratio': 0.1375294726381616}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,453] Trial 57 finished with value: 0.014013880178944005 and parameters: {'alpha': 0.0021563042028174624, 'l1_ratio': 0.12681305812495153}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,461] Trial 58 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.2578736243886594, 'l1_ratio': 0.20808532572115884}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,470] Trial 59 finished with value: 0.014054631172633699 and parameters: {'alpha': 8.946476890955942e-05, 'l1_ratio': 0.10536786762942618}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,478] Trial 60 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.010166198715368417, 'l1_ratio': 0.2987612669068727}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,485] Trial 61 finished with value: 0.014025495140250852 and parameters: {'alpha': 0.0007274619584706299, 'l1_ratio': 0.23495081393423423}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,493] Trial 62 finished with value: 0.014041057465166618 and parameters: {'alpha': 0.0029534195916612665, 'l1_ratio': 0.42015952754872254}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,501] Trial 63 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.03690417607191641, 'l1_ratio': 0.1498256437750606}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,511] Trial 64 finished with value: 0.01404639086012577 and parameters: {'alpha': 0.00020083863988461017, 'l1_ratio': 0.21971477966656594}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,518] Trial 65 finished with value: 0.014007415686646365 and parameters: {'alpha': 0.0010664412255195783, 'l1_ratio': 0.37660604758862926}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,525] Trial 66 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.004948820524044167, 'l1_ratio': 0.3750947366166849}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,535] Trial 67 finished with value: 0.014053891416821002 and parameters: {'alpha': 4.6686989502853515e-05, 'l1_ratio': 0.28788732944457746}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,543] Trial 68 finished with value: 0.01401667688053028 and parameters: {'alpha': 0.0007874248714504503, 'l1_ratio': 0.33083652137996006}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,554] Trial 69 finished with value: 0.01402750535417427 and parameters: {'alpha': 0.0020755517956870316, 'l1_ratio': 0.5078013390166001}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,566] Trial 70 finished with value: 0.014057042060744153 and parameters: {'alpha': 1.2361210922775828e-05, 'l1_ratio': 0.07597365981937887}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,573] Trial 71 finished with value: 0.014016709270636463 and parameters: {'alpha': 0.000669978855323396, 'l1_ratio': 0.39131552912848455}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,584] Trial 72 finished with value: 0.014039750194508017 and parameters: {'alpha': 0.00017418068025818945, 'l1_ratio': 0.4460802375403463}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,594] Trial 73 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.01713180694689375, 'l1_ratio': 0.1787039229885929}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,603] Trial 74 finished with value: 0.014011989831467063 and parameters: {'alpha': 0.0012020285448393851, 'l1_ratio': 0.26074352291948427}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,611] Trial 75 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.0078069327320515955, 'l1_ratio': 0.35092782269577993}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,623] Trial 76 finished with value: 0.014049399593350238 and parameters: {'alpha': 5.634115133294841e-05, 'l1_ratio': 0.5855255459268607}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,631] Trial 77 finished with value: 0.014013023205881901 and parameters: {'alpha': 0.0031197368921936763, 'l1_ratio': 0.24335851846638987}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,639] Trial 78 finished with value: 0.014032534471085895 and parameters: {'alpha': 0.00039861498930687464, 'l1_ratio': 0.2917176066023733}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,647] Trial 79 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.02272708842749012, 'l1_ratio': 0.5031157442520311}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,658] Trial 80 finished with value: 0.014042660095095904 and parameters: {'alpha': 0.00014715813740090263, 'l1_ratio': 0.4300056844914196}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,666] Trial 81 finished with value: 0.014008419973319681 and parameters: {'alpha': 0.0013405020154788347, 'l1_ratio': 0.2737973173310271}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,674] Trial 82 finished with value: 0.014018034724994572 and parameters: {'alpha': 0.0012692374797668763, 'l1_ratio': 0.1864480947768588}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,682] Trial 83 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.004924447254174953, 'l1_ratio': 0.36480966635225837}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,691] Trial 84 finished with value: 0.01400731180576796 and parameters: {'alpha': 0.00044815442778940105, 'l1_ratio': 0.9779128044519436}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,699] Trial 85 finished with value: 0.014006736828725738 and parameters: {'alpha': 0.0005226350162595038, 'l1_ratio': 0.9883234392065862}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,708] Trial 86 finished with value: 0.014006738536230825 and parameters: {'alpha': 0.0005316545933227291, 'l1_ratio': 0.9609682026459383}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,716] Trial 87 finished with value: 0.014006781574899726 and parameters: {'alpha': 0.000496779910650403, 'l1_ratio': 0.9995580150453556}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,725] Trial 88 finished with value: 0.014015238935385654 and parameters: {'alpha': 0.0002909757056054227, 'l1_ratio': 0.9827918671412286}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,735] Trial 89 finished with value: 0.01405091763701679 and parameters: {'alpha': 2.851522268846044e-05, 'l1_ratio': 0.9374929268999838}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,743] Trial 90 finished with value: 0.01400673384415444 and parameters: {'alpha': 0.0005375954554263243, 'l1_ratio': 0.9622961479682077}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,750] Trial 91 finished with value: 0.014006858767916115 and parameters: {'alpha': 0.0005024317177745255, 'l1_ratio': 0.9571981147172633}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,757] Trial 92 finished with value: 0.014007232924818308 and parameters: {'alpha': 0.00046595744486226153, 'l1_ratio': 0.952215412664773}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,764] Trial 93 finished with value: 0.014037029558025034 and parameters: {'alpha': 9.812759780527996e-05, 'l1_ratio': 0.9550305481120767}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,771] Trial 94 finished with value: 0.0140255904569657 and parameters: {'alpha': 0.00020184269793603718, 'l1_ratio': 0.8962363923724393}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,779] Trial 95 finished with value: 0.014045932093594489 and parameters: {'alpha': 5.707771691882599e-05, 'l1_ratio': 0.8590574584559747}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,786] Trial 96 finished with value: 0.014007371157792563 and parameters: {'alpha': 0.0006352026411571714, 'l1_ratio': 0.9483227826977627}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,795] Trial 97 finished with value: 0.014054734343689692 and parameters: {'alpha': 1.1517531107807896e-05, 'l1_ratio': 0.9181865538221696}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,807] Trial 98 finished with value: 0.01405732957967634 and parameters: {'alpha': 1.3963634500518422e-08, 'l1_ratio': 0.9959679732811978}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,815] Trial 99 finished with value: 0.014017482292853526 and parameters: {'alpha': 0.0002901935839499103, 'l1_ratio': 0.8965829092465893}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,822] Trial 100 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.0024127888232811654, 'l1_ratio': 0.9992241834994018}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,830] Trial 101 finished with value: 0.014007153961134573 and parameters: {'alpha': 0.00046475013885726184, 'l1_ratio': 0.968485179089924}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,838] Trial 102 finished with value: 0.014033213504563137 and parameters: {'alpha': 0.00012209572737689284, 'l1_ratio': 0.9596295118551357}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,846] Trial 103 finished with value: 0.014006823911780356 and parameters: {'alpha': 0.000629630366695679, 'l1_ratio': 0.8746304277152132}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,853] Trial 104 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.008458731492791452, 'l1_ratio': 0.8730072391125816}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,861] Trial 105 finished with value: 0.014067493069423146 and parameters: {'alpha': 0.001794633376704678, 'l1_ratio': 0.9140566369018363}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,868] Trial 106 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.004268381024637651, 'l1_ratio': 0.8247603617512814}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,876] Trial 107 finished with value: 0.014009527542147744 and parameters: {'alpha': 0.0007119005752865451, 'l1_ratio': 0.97559742836695}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,883] Trial 108 finished with value: 0.014023174553733342 and parameters: {'alpha': 0.00021803027469752067, 'l1_ratio': 0.9314343784443361}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,895] Trial 109 finished with value: 0.01404241801373115 and parameters: {'alpha': 7.484234565744073e-05, 'l1_ratio': 0.8795744476861215}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,907] Trial 110 finished with value: 0.014049297784115677 and parameters: {'alpha': 4.025367316319293e-05, 'l1_ratio': 0.8387788716830612}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,916] Trial 111 finished with value: 0.014006942567333274 and parameters: {'alpha': 0.0004993166513266904, 'l1_ratio': 0.9406552043248215}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,926] Trial 112 finished with value: 0.014020422599147365 and parameters: {'alpha': 0.0010184225504413925, 'l1_ratio': 0.9040889973744921}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,935] Trial 113 finished with value: 0.014006805064912623 and parameters: {'alpha': 0.0005236768266189906, 'l1_ratio': 0.9343516730886022}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,945] Trial 114 finished with value: 0.014034158304332084 and parameters: {'alpha': 0.0001399913417756939, 'l1_ratio': 0.7812045849224919}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,953] Trial 115 finished with value: 0.014071864000304884 and parameters: {'alpha': 0.0030666210260181467, 'l1_ratio': 0.9418146581655115}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,961] Trial 116 finished with value: 0.014069649643681861 and parameters: {'alpha': 0.0018365132819072119, 'l1_ratio': 0.9226924461402403}. Best is trial 53 with value: 0.014006529751446698.
[I 2026-10-14 15:42:19,968] Trial 117 finished with value: 0.014008226937293984 and parameters: {'alpha': 0.0007418548542171023, 'l1_ratio': 0.8714057538406101}. Best is trial 53 with value: 0.014006529751446698.

[ 0.         -0.00274722 -0.         -0.01015094 -0.         -0.00310722
  0.01073875  0.02788307 -0.01195531  0.          0.03715251]
72

[I 2026-10-14 15:42:21,410] Trial 26 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.008361657442463075, 'l1_ratio': 0.34377576579647945}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,418] Trial 27 finished with value: 0.008251645022286482 and parameters: {'alpha': 0.0007648224302565945, 'l1_ratio': 0.18800663387130861}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,425] Trial 28 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.024151916841160626, 'l1_ratio': 0.34683875805719133}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,435] Trial 29 finished with value: 0.008273169422058265 and parameters: {'alpha': 3.865308995607826e-06, 'l1_ratio': 0.06537368319148712}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,443] Trial 30 finished with value: 0.008200781774179818 and parameters: {'alpha': 5.647603174941089, 'l1_ratio': 0.24767343909252587}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,449] Trial 31 finished with value: 0.008200781774179818 and parameters: {'alpha': 11.289057101593633, 'l1_ratio': 0.6425230072653689}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,458] Trial 32 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.6481417522216003, 'l1_ratio': 0.4882363380321183}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,467] Trial 33 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.1191608809742656, 'l1_ratio': 0.7405195946185481}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,475] Trial 34 finished with value: 0.008200781774179818 and parameters: {'alpha': 84.61727149971163, 'l1_ratio': 0.8701490993179026}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,483] Trial 35 finished with value: 0.008249803280270595 and parameters: {'alpha': 0.0004352939850147982, 'l1_ratio': 0.37515383318963363}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,491] Trial 36 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.016128991110784235, 'l1_ratio': 0.44672231858471073}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,501] Trial 37 finished with value: 0.008271554931649595 and parameters: {'alpha': 1.6458582377246858e-05, 'l1_ratio': 0.6016819330224048}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,509] Trial 38 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.24157487297487265, 'l1_ratio': 0.1765672938161842}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,516] Trial 39 finished with value: 0.008200781774179818 and parameters: {'alpha': 15.832220960085955, 'l1_ratio': 0.29430290780699586}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,525] Trial 40 finished with value: 0.008200781774179818 and parameters: {'alpha': 1.9838479724840228, 'l1_ratio': 0.002715462948933045}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,533] Trial 41 finished with value: 0.008200781774179818 and parameters: {'alpha': 2.8136486293145913, 'l1_ratio': 0.05736349165305499}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,541] Trial 42 finished with value: 0.008200781774179818 and parameters: {'alpha': 1.7312828720552385, 'l1_ratio': 0.04841749377434898}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,549] Trial 43 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.05001409098222154, 'l1_ratio': 0.13513694232876367}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,560] Trial 44 finished with value: 0.008273224380672897 and parameters: {'alpha': 6.285072020487626e-09, 'l1_ratio': 0.2584821514615524}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,569] Trial 45 finished with value: 0.008250948917430868 and parameters: {'alpha': 0.004465908348803816, 'l1_ratio': 0.019507796543279308}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,578] Trial 46 finished with value: 0.008200781774179818 and parameters: {'alpha': 12.257012786442312, 'l1_ratio': 0.8245663700700439}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,587] Trial 47 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.6581572749891181, 'l1_ratio': 0.1645187842722648}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,595] Trial 48 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.1654282116803599, 'l1_ratio': 0.09279986032753684}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,610] Trial 49 finished with value: 0.00827322466436789 and parameters: {'alpha': 1.9019481786172727e-10, 'l1_ratio': 0.2169070753582513}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,617] Trial 50 finished with value: 0.008200781774179818 and parameters: {'alpha': 4.929998317919908, 'l1_ratio': 0.5497278165144953}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,624] Trial 51 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.07269772338613704, 'l1_ratio': 0.24725292753370737}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,632] Trial 52 finished with value: 0.008200781774179818 and parameters: {'alpha': 92.25143305659056, 'l1_ratio': 0.42421957686070944}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,640] Trial 53 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.01962937608615008, 'l1_ratio': 0.35698561327569084}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,648] Trial 54 finished with value: 0.008241870377023279 and parameters: {'alpha': 0.0007689771420723063, 'l1_ratio': 0.2868564190064267}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,655] Trial 55 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.6021260508373532, 'l1_ratio': 0.09936911101216109}. Best is trial 25 with value: 0.00819340846267534.
[I 2026-10-14 15:42:21,662] Trial 56 finished with value: 0.008190765355304368 and parameters: {'alpha': 0.003717677177435096, 'l1_ratio': 0.3243351954589784}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,670] Trial 57 finished with value: 0.008199976446784165 and parameters: {'alpha': 0.0015820799385240804, 'l1_ratio': 0.9625481159416295}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,678] Trial 58 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.0021935315406550085, 'l1_ratio': 0.954273055573329}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,686] Trial 59 finished with value: 0.008258921895234994 and parameters: {'alpha': 0.00015212722536576593, 'l1_ratio': 0.6678138565238609}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,694] Trial 60 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.009293516357789224, 'l1_ratio': 0.7060777796192856}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,703] Trial 61 finished with value: 0.008269574347253164 and parameters: {'alpha': 6.880300123117267e-05, 'l1_ratio': 0.31201182661887106}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,711] Trial 62 finished with value: 0.008200781774179818 and parameters: {'alpha': 28.02246952112322, 'l1_ratio': 0.9107015117984204}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,721] Trial 63 finished with value: 0.008224504969372227 and parameters: {'alpha': 0.0007820044692117418, 'l1_ratio': 0.47872390796801534}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,733] Trial 64 finished with value: 0.008273179212053026 and parameters: {'alpha': 3.489007014253578e-07, 'l1_ratio': 0.7650523568685563}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,742] Trial 65 finished with value: 0.008260523729222735 and parameters: {'alpha': 0.00021847899122731017, 'l1_ratio': 0.39211772948745033}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,750] Trial 66 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.007419794464797314, 'l1_ratio': 0.4536829295117133}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,759] Trial 67 finished with value: 0.008271323120103263 and parameters: {'alpha': 2.1364942982369314e-05, 'l1_ratio': 0.5266990930324367}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,767] Trial 68 finished with value: 0.008223304404842896 and parameters: {'alpha': 0.001763228567720466, 'l1_ratio': 0.21257204576602107}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,774] Trial 69 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.042809177179838995, 'l1_ratio': 0.3291908582060621}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,782] Trial 70 finished with value: 0.008200781774179818 and parameters: {'alpha': 5.163930835093642, 'l1_ratio': 0.5951584356324728}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,792] Trial 71 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.4709529375611997, 'l1_ratio': 0.2718559450879256}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,802] Trial 72 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.15887669958201117, 'l1_ratio': 0.035454040152490554}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,811] Trial 73 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.9402011548797977, 'l1_ratio': 0.15240667487585446}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,820] Trial 74 finished with value: 0.008200781774179818 and parameters: {'alpha': 32.15089698866265, 'l1_ratio': 0.3665506379350724}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,829] Trial 75 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.079954094249812, 'l1_ratio': 0.40989784165982945}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,837] Trial 76 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.28314108006200384, 'l1_ratio': 0.0889526242027262}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,847] Trial 77 finished with value: 0.008200781774179818 and parameters: {'alpha': 3.4602785318874925, 'l1_ratio': 0.23040047396677293}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,856] Trial 78 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.013976424557542872, 'l1_ratio': 0.1883742241196251}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,864] Trial 79 finished with value: 0.008200781774179818 and parameters: {'alpha': 13.126410196250701, 'l1_ratio': 0.3283251525774488}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,873] Trial 80 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.0039048793550539324, 'l1_ratio': 0.9835341134908555}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,882] Trial 81 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.03910814725355219, 'l1_ratio': 0.38940944772607133}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,891] Trial 82 finished with value: 0.008198454244164224 and parameters: {'alpha': 0.0016461804161505057, 'l1_ratio': 0.43209612605605674}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,900] Trial 83 finished with value: 0.008259098054746825 and parameters: {'alpha': 0.00030610799299077534, 'l1_ratio': 0.3143913135424466}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,907] Trial 84 finished with value: 0.008199891562195154 and parameters: {'alpha': 0.0016279622046877855, 'l1_ratio': 0.42024759702092107}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,916] Trial 85 finished with value: 0.00823539173295797 and parameters: {'alpha': 0.0005671797200193439, 'l1_ratio': 0.49227282394153804}. Best is trial 56 with value: 0.008190765355304368.
[I 2026-10-14 15:42:21,924] Trial 86 finished with value: 0.008189424987016967 and parameters: {'alpha': 0.002659964348346188, 'l1_ratio': 0.4281283106787384}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,933] Trial 87 finished with value: 0.008211005927146544 and parameters: {'alpha': 0.0011675038762831973, 'l1_ratio': 0.44248890129505997}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,941] Trial 88 finished with value: 0.008189673088383172 and parameters: {'alpha': 0.00203042990421912, 'l1_ratio': 0.470941852726647}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,949] Trial 89 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.00524570643443037, 'l1_ratio': 0.4149343490334148}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,958] Trial 90 finished with value: 0.008193100562351407 and parameters: {'alpha': 0.0029010368064588256, 'l1_ratio': 0.4549068513894464}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,966] Trial 91 finished with value: 0.008190830302542975 and parameters: {'alpha': 0.0019207160925650171, 'l1_ratio': 0.47167583869467816}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,973] Trial 92 finished with value: 0.008189553677554109 and parameters: {'alpha': 0.0020796776499249136, 'l1_ratio': 0.4631563060817815}. Best is trial 86 with value: 0.008189424987016967.
[I 2026-10-14 15:42:21,981] Trial 93 finished with value: 0.00818901842619263 and parameters: {'alpha': 0.001955960381071671, 'l1_ratio': 0.5077143724338742}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:21,988] Trial 94 finished with value: 0.008199786461762127 and parameters: {'alpha': 0.002933124734983556, 'l1_ratio': 0.5168596279869552}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:21,995] Trial 95 finished with value: 0.008200522935680677 and parameters: {'alpha': 0.0030125573411774495, 'l1_ratio': 0.5150249677859822}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,002] Trial 96 finished with value: 0.008252114890696053 and parameters: {'alpha': 0.00031785119991390424, 'l1_ratio': 0.46589509342533947}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,009] Trial 97 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.011068509332136588, 'l1_ratio': 0.56312982224503}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,017] Trial 98 finished with value: 0.008268178426415633 and parameters: {'alpha': 6.145532672144122e-05, 'l1_ratio': 0.5029538519755171}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,025] Trial 99 finished with value: 0.008209730290748856 and parameters: {'alpha': 0.0009888679602962204, 'l1_ratio': 0.540773164148669}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,034] Trial 100 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.0062667118351182475, 'l1_ratio': 0.5766532375247135}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,043] Trial 101 finished with value: 0.00819335060439233 and parameters: {'alpha': 0.001913663467715808, 'l1_ratio': 0.4322987749499755}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,054] Trial 102 finished with value: 0.008191115576362094 and parameters: {'alpha': 0.002653568465128365, 'l1_ratio': 0.4667329207902509}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,062] Trial 103 finished with value: 0.008239661638443745 and parameters: {'alpha': 0.0005216430863431298, 'l1_ratio': 0.4660852485476683}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,070] Trial 104 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.02543683472262888, 'l1_ratio': 0.4269636108238482}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,078] Trial 105 finished with value: 0.008190096346013644 and parameters: {'alpha': 0.0025432704272019633, 'l1_ratio': 0.46621393150904905}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,086] Trial 106 finished with value: 0.008201741410990027 and parameters: {'alpha': 0.003556372824594995, 'l1_ratio': 0.4546535838018667}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,095] Trial 107 finished with value: 0.008263471329866717 and parameters: {'alpha': 0.00016354309808582884, 'l1_ratio': 0.38387239699663844}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,104] Trial 108 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.01305003242873471, 'l1_ratio': 0.47669096740979583}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,113] Trial 109 finished with value: 0.008266611435123446 and parameters: {'alpha': 7.631808932189409e-05, 'l1_ratio': 0.542851740038113}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,122] Trial 110 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.005798546119192207, 'l1_ratio': 0.5057013575504238}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,129] Trial 111 finished with value: 0.00820318372273997 and parameters: {'alpha': 0.0014175473808227727, 'l1_ratio': 0.4432717007577132}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,137] Trial 112 finished with value: 0.00819738960063865 and parameters: {'alpha': 0.001978864010837, 'l1_ratio': 0.369938468625402}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,145] Trial 113 finished with value: 0.008253969729269372 and parameters: {'alpha': 0.00036668133860507735, 'l1_ratio': 0.36451129276194594}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,155] Trial 114 finished with value: 0.008192321461619263 and parameters: {'alpha': 0.0025062474483932913, 'l1_ratio': 0.34276967443945267}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,164] Trial 115 finished with value: 0.008227062377027507 and parameters: {'alpha': 0.0010222951031130488, 'l1_ratio': 0.3396641642024045}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,170] Trial 116 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.008324039039814038, 'l1_ratio': 0.48795833397289456}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,178] Trial 117 finished with value: 0.008200781774179818 and parameters: {'alpha': 0.022293294690658095, 'l1_ratio': 0.2821486746011381}. Best is trial 93 with value: 0.00818901842619263.
[I 2026-10-14 15:42:22,186] Trial 118 finished with value: 0.008188992554245463 and parameters: {'alpha': 0.0027542973689545984, 'l1_ratio': 0.3994177850296313}. Best is trial 118 with value: 0.008188992554245463.
[I 2026-10-14 15:42:22,197] Trial 119 finished with value: 0.00823956228788052 and parameters: {'alpha': 0.0006029494965991815, 'l1_ratio': 0.4024935884777214}. Best is trial 118 with value: 0.008188992554245463.

[ 0.         -0.         -0.         -0.0045844  -0.         -0.
  0.0034092   0.00802231 -0.          0.          0.01521543]

In [39]:
results_df

            date  stock_id  R1M_Usd    y_pred
0     2012-11-30         3    0.034  0.013231
1     2012-11-30         9   -0.026  0.013231
2     2012-11-30        24    0.048  0.013231
3     2012-11-30        32    0.005  0.013231
4     2012-11-30        46    0.011  0.013231
...          ...       ...      ...       ...
11687 2018-12-31      1149    0.044  0.009463
11688 2018-12-31      1192    0.190  0.011021
11689 2018-12-31      1200    0.071  0.008790
11690 2018-12-31      1203    0.061  0.008083
11691 2018-12-31      1212    0.222  0.014068

[11692 rows x 4 columns]

In [40]:
hyperparameters_df

         date      alpha  l1_ratio  validation_mse
0  2012-11-30   0.004578  0.479754        0.029045
1  2013-05-31   0.002307  0.861447        0.025799
2  2013-11-30   0.012907  0.135443        0.011937
3  2014-05-31   0.005213  0.329978        0.010277
4  2014-11-30   0.004027  0.488781        0.010065
5  2015-05-31   0.002959  0.502094        0.006427
6  2015-11-30  11.678579  0.892923        0.007783
7  2016-05-31   0.240084  0.005038        0.013991
8  2016-11-30   0.015746  0.033074        0.014950
9  2017-05-31   0.000713  0.864584        0.014815
10 2017-11-30   0.001269  0.793443        0.014809
11 2018-05-31   0.001877  0.255200        0.014007
12 2018-11-30   0.002006  0.534578        0.008189

In [41]:
# Include random walk benchmark
# Random walk benchmark
results_df = results_df.merge(data_ml_selected_lags[['date', 'stock_id', 'Lag1_R1M_Usd']], on=['date', 'stock_id'], how='left')
results_df

            date  stock_id  R1M_Usd    y_pred  Lag1_R1M_Usd
0     2012-11-30         3    0.034  0.013231        -0.047
1     2012-11-30         9   -0.026  0.013231         0.036
2     2012-11-30        24    0.048  0.013231         0.052
3     2012-11-30        32    0.005  0.013231        -0.112
4     2012-11-30        46    0.011  0.013231        -0.114
...          ...       ...      ...       ...           ...
11687 2018-12-31      1149    0.044  0.009463        -0.049
11688 2018-12-31      1192    0.190  0.011021        -0.101
11689 2018-12-31      1200    0.071  0.008790        -0.054
11690 2018-12-31      1203    0.061  0.008083        -0.079
11691 2018-12-31      1212    0.222  0.014068        -0.125

[11692 rows x 5 columns]

In [42]:
print(f'EN model:{mean_squared_error(results_df['y_pred'], results_df['R1M_Usd'])}')
print(f'RW model:{mean_squared_error(results_df['Lag1_R1M_Usd'], results_df['R1M_Usd'])}')

EN model:0.010902449445878426
RW model:0.021978956979131034